policy/flask/access_vectors
policy/flask/security_classes

Add xdp_socket security class and access vectors

---

policy/modules/system/unconfined.if

Addresses https://github.com/SELinuxProject/refpolicy/issues/18

unconfined: add a note about DBUS

---

policy/modules/services/dovecot.te

Add dovecot_can_connect_db boolean. Grant connect dovecot_auth_t to DBs by dovecot_can_connect_db boolean.

Add dovecot_can_connect_db boolean.

---

config/appconfig-mcs/default_contexts
config/appconfig-mcs/root_default_contexts
config/appconfig-mcs/staff_u_default_contexts
config/appconfig-mcs/unconfined_u_default_contexts
config/appconfig-mcs/user_u_default_contexts
config/appconfig-mls/default_contexts
config/appconfig-mls/root_default_contexts
config/appconfig-mls/staff_u_default_contexts
config/appconfig-mls/unconfined_u_default_contexts
config/appconfig-mls/user_u_default_contexts
config/appconfig-standard/default_contexts
config/appconfig-standard/root_default_contexts
config/appconfig-standard/staff_u_default_contexts
config/appconfig-standard/unconfined_u_default_contexts
config/appconfig-standard/user_u_default_contexts
policy/modules/system/init.if
policy/modules/system/init.te
policy/modules/system/mount.if
policy/modules/system/systemd.if
policy/modules/system/systemd.te
policy/modules/system/unconfined.if
policy/modules/system/unconfined.te
policy/modules/system/userdomain.if

This is just a start; it does not cover all uses.

systemd: Add initial policy for systemd --user.

---

policy/modules/services/networkmanager.if

Create interfaces to allow start/stop, enable/disable and status of NetworkManager systemd unit

create interfaces for NetworkManager unit

---

policy/modules/services/dovecot.te

Mails can be injected in dovecot directly using LMTP

Add dovecot to listen to LMTP port

---

Makefile

Makefile: Avoid regenerating the iftemplates at everyrun

---

INSTALL
policy/flask/access_vectors

Add watch access vectors.

---

policy/modules/kernel/devices.te
policy/modules/kernel/files.if
policy/modules/kernel/files.te
policy/modules/kernel/kernel.te
policy/modules/system/init.if
policy/modules/system/init.te

Add interface similar to files_mountpoint() and add a conditional which
allows mount on non_security_file_type.

init: Revise systemd bind mounts.

---

policy/modules/apps/pulseaudio.te

Update the pulseaudio application module with a few user domain file read and management permissions.
---
policy/modules/apps/pulseaudio.te |    1 +
1 file changed, 1 insertions(+)

Update the pulseaudio application module

---

policy/modules/services/networkmanager.fc
policy/modules/services/networkmanager.te

Consider iwd equivalent to NetworkManager etc.

---

policy/modules/apps/mozilla.te
policy/modules/apps/wm.if
policy/modules/services/networkmanager.if
policy/modules/system/getty.te
policy/modules/system/miscfiles.if
policy/modules/system/userdomain.if

Add further "watch" permissions.
Modified/updated modules:
- userdomain
- wm
- mozilla
- getty

Add further "watch" permissions

---

policy/modules/apps/java.if
policy/modules/services/lpd.if

Signed-off-by: Daniel Burgener <Daniel.Burgener@microsoft.com>

Change incorrect template definitions into interface definitions

---

.gitignore

Ignore temporary documentation file directory in git

---

policy/modules/services/spamassassin.if

fix require from 5b78c1c86bedf322fa6a08e5d68e7e8a6b85f026

---

support/gennetfilter.py

Generate rules for SECMARKing ICMP and ICMPv6 packets as
icmp_packet_t.

gennetfilter: add rules for ICMP/ICMPv6 packets

---

support/genhomedircon.py

genhomedircon: Drop Python 2 compatibility code.

---

policy/modules/kernel/kernel.te

Resolve neverallow failure introduced in #273

---

policy/modules/services/chronyd.fc

Signed-off-by: Daniel Burgener <dburgener@linux.microsoft.com>

Fix typo in comment

---

policy/modules/system/systemd.if
policy/modules/system/systemd.te

Two minor fixes to be merged that were discovered while trying to get RHEL7 building again.  
Signed-off-by: Dave Sugar <dsugar100@gmail.com>

Minor Fixes

---

policy/modules/admin/kismet.if
policy/modules/apps/seunshare.if

Have these ever worked?
Fix parameters so that role clause gets role parameter and so on.

fix: Mixed order

---

policy/modules/kernel/files.if
policy/modules/services/ssh.if
policy/modules/services/xserver.if

Several interfaces were missing requires.

cleanup: Missing requires

---

policy/modules/services/cvs.te

policy/modules/services/cvs.te: make inetd optional

---

policy/modules/services/obfs4proxy.fc
policy/modules/services/obfs4proxy.if
policy/modules/services/obfs4proxy.te
policy/modules/services/tor.fc
policy/modules/services/tor.if
policy/modules/services/tor.te

Added policy for obfs4proxy and added bool to allow Tor to run it.
https://blog.torproject.org/tor-heart-bridges-and-pluggable-transports/

Added obfs4proxy policy

---

policy/modules/kernel/files.if
policy/modules/services/mta.if
policy/modules/services/ssh.if
policy/modules/services/ssh.te
policy/modules/system/fstools.if
policy/modules/system/init.if
policy/modules/system/init.te
policy/modules/system/logging.te
policy/modules/system/lvm.te
policy/modules/system/modutils.fc
policy/modules/system/systemd.fc
policy/modules/system/systemd.if
policy/modules/system/systemd.te
policy/modules/system/userdomain.if
policy/support/misc_patterns.spt

- Add systemd-homed and systemd-userdbd.
- Various other systemd fixes.
The systemd-homed policy has only had the most basic testing and is just a starting point.

Systemd updates including systemd-homed and systemd-userdbd.

---

Makefile
policy/modules/admin/consoletype.if
policy/modules/admin/netutils.te
policy/modules/admin/portage.te
policy/modules/admin/prelink.if
policy/modules/admin/prelink.te
policy/modules/admin/sudo.if
policy/modules/admin/usermanage.if
policy/modules/apps/gpg.te
policy/modules/apps/seunshare.if
policy/modules/apps/seunshare.te
policy/modules/kernel/domain.te
policy/modules/services/abrt.te
policy/modules/services/apache.te
policy/modules/services/dbus.if
policy/modules/services/mta.te
policy/modules/services/samba.te
policy/modules/services/virt.te
policy/modules/system/iptables.if
policy/modules/system/iptables.te
policy/modules/system/libraries.te
policy/modules/system/mount.te
policy/modules/system/selinuxutil.te
policy/modules/system/sysnetwork.te
support/Makefile.devel

These blocks are always enabled.

Make hide_broken_symptoms unconditional.

---

SECURITY.md

Add a vulnerability handling process.

---

.github/workflows/tests.yml
Makefile
udica-templates/base_container.cil
udica-templates/config_container.cil
udica-templates/home_container.cil
udica-templates/log_container.cil
udica-templates/net_container.cil
udica-templates/tmp_container.cil
udica-templates/tty_container.cil
udica-templates/virt_container.cil
udica-templates/x_container.cil

This is a reopen of #474 to add base container templates for [udica](https://github.com/containers/udica). Additional comments can be found in the previous PR.

Add udica templates

---

policy/mcs

- Collapse overlapping constraints with same expressions.
- Add additional SysV IPC constraints.
- Add additional socket constraints.

Add additional MCS constraints.

---

policy/modules/admin/cloudinit.fc
policy/modules/admin/cloudinit.if
policy/modules/admin/cloudinit.te
policy/modules/admin/usermanage.fc
policy/modules/kernel/corecommands.fc
policy/modules/kernel/corenetwork.if.in
policy/modules/services/ssh.fc
policy/modules/services/ssh.if
policy/modules/system/libraries.if
policy/modules/system/sysnetwork.te
policy/modules/system/systemd.te

This is used by cloud providers to set up VMs during deployment.
https://github.com/canonical/cloud-init

Add cloud-init.

---

policy/modules/services/tpm2.te

node=localhost type=AVC msg=audit(1662410789.964:19770): avc:  denied  { create } for  pid=1370 comm="tpm2-abrmd" scontext=system_u:system_r:tpm2_abrmd_t:s0 tcontext=system_u:system_r:tpm2_abrmd_t:s0 tclass=unix_dgram_socket permissive=1
node=localhost type=AVC msg=audit(1662410789.964:19771): avc:  denied  { write } for  pid=1370 comm="tpm2-abrmd" scontext=system_u:system_r:tpm2_abrmd_t:s0 tcontext=system_u:system_r:tpm2_abrmd_t:s0 tclass=unix_dgram_socket permissive=1
node=localhost type=AVC msg=audit(1662410789.964:19771): avc:  denied  { search } for  pid=1370 comm="tpm2-abrmd" name="journal" dev="tmpfs" ino=12582 scontext=system_u:system_r:tpm2_abrmd_t:s0 tcontext=system_u:object_r:syslogd_runtime_t:s0 tclass=dir permissive=1
node=localhost type=AVC msg=audit(1662410789.964:19771): …

tpm2-abrmd: allow to send syslog messages

---

policy/modules/roles/guest.te

This is just a clone of the `xguest_connect_network` boolean for the guest role.

Clone `xguest_connect_network` for guest role

---

.github/workflows/tests.yml

* ci: update dependencies
- Update checkout action to v3
- Update python-setup action to v4
Also print basic output from apt-get to debug potential flaky failures.
* ci: build SELint from source
Disable newly added check C-008:
usermanage.te:      581: (C): Identifier samba_domain_controller in expression for conditional block not found in own module, but in module samba (candidate for global declaration or interface) (C-008)
mplayer.te:         122: (C): Identifier xserver_allow_dri in expression for conditional block not found in own module, but in module xserver (candidate for global declaration or interface) (C-008)
nscd.te:            125: (C): Identifier samba_domain_controller in expression for conditional block not found in own module, but in module samba (candidate for global …

CI: update and build SELint from source

---

policy/modules/kernel/devices.te
policy/modules/kernel/files.te
policy/modules/kernel/filesystem.te
policy/modules/kernel/kernel.te
policy/modules/kernel/storage.te

This permission is only used for auditing purposes. It is a no-op for allows.

Drop audit_access allows.

---

policy/modules/system/fstools.te

fstools: Move lines.

---

policy/modules/admin/portage.fc

This PR is mean to remove difference between gentoo policy and upstream one.

Gentoo port portagefc

---

policy/modules/system/sysnetwork.if

modified:   policy/modules/system/sysnetwork.if

Added interface: sysnet_dontaudit_rw_dhcpc_unix_dgram_sockets

---

policy/modules/kernel/filesystem.if
policy/modules/kernel/filesystem.te
policy/modules/services/ntp.te
policy/modules/system/init.te
policy/modules/system/logging.te
policy/modules/system/systemd.te
policy/modules/system/udev.te

See: https://github.com/systemd/systemd/blob/main/docs/MEMORY_PRESSURE.md

Add support for memory pressure notifications protocol

---

policy/modules/apps/wm.if
policy/modules/apps/xscreensaver.fc
policy/modules/apps/xscreensaver.if
policy/modules/apps/xscreensaver.te

Update the xscreensaver module for the latest version of the application (tested with version 6.06).
policy/modules/apps/wm.if           |    4 +++
policy/modules/apps/xscreensaver.fc |    1
policy/modules/apps/xscreensaver.if |   46 ++++++++++++++++++++++++++++++++++++
policy/modules/apps/xscreensaver.te |   17 +++++++++++--
4 files changed, 66 insertions(+), 2 deletions(-)

Update the xscreensaver module in order to work with the latest version

---

policy/modules/admin/logrotate.te
policy/modules/system/logging.if
policy/modules/system/mount.if

Miscellaneous fixes to tighten security

Miscellaneous fixes

---

policy/modules/system/logging.te

Improve a previous syslog tunable policy change.

Improve a previous syslog tunable policy change

---

policy/modules/services/dbus.if
policy/modules/services/dbus.te

Session-bus equivalent of the following pull request:
https://github.com/SELinuxProject/refpolicy/pull/667
Also introduce a new boolean to control insecure TCP/IP networking features.

Dbus also creates Unix domain sockets in session mode but has insecure networking code

---

policy/modules/apps/openoffice.te

Let openoffice perform temporary file transitions on link files and manage them
policy/modules/apps/openoffice.te |    3 ++-
1 file changed, 2 insertions(+), 1 deletion(-)

Let openoffice perform temporary file transitions on link files and manage them

---

policy/modules/system/selinuxutil.fc
policy/modules/system/selinuxutil.if
policy/modules/system/selinuxutil.te

The dbus selinux interface comes from policycoreutils-dbus package

Setup domain for dbus selinux interface

---

policy/modules/admin/bootloader.te
policy/modules/kernel/devices.if
policy/modules/kernel/files.if
policy/modules/services/asterisk.te
policy/modules/services/container.if
policy/modules/services/container.te
policy/modules/services/crio.te
policy/modules/services/dovecot.te
policy/modules/services/fail2ban.te
policy/modules/services/kubernetes.te
policy/modules/services/matrixd.te
policy/modules/services/podman.te
policy/modules/services/postgresql.te
policy/modules/services/ssh.if
policy/modules/system/authlogin.if
policy/modules/system/authlogin.te
policy/modules/system/init.if
policy/modules/system/init.te
policy/modules/system/raid.te
policy/modules/system/selinuxutil.te
policy/modules/system/systemd.te
policy/modules/system/userdomain.if

More various fixes across the board.

Various fixes

---

policy/modules/roles/sysadm.te
policy/modules/services/haproxy.fc
policy/modules/services/haproxy.if
policy/modules/services/haproxy.te

Add an initial policy for haproxy, a TCP/HTTP reverse proxy for high availability environments.

Initial policy for haproxy

---

.github/workflows/build-userspace.yml
.github/workflows/tests.yml
Makefile
Rules.modular
Rules.monolithic
config/appconfig-mcs/userhelper_context
config/appconfig-mls/userhelper_context
config/appconfig-standard/lxc_contexts
config/appconfig-standard/userhelper_context
support/validate-appconfig.py

Initial implementation only covers files with full contexts.
Fix invalid contexts this found:
* userhelper_context
* lxc_contexts

Add tool for validating contexts in appconfig files.

---

policy/modules/services/virt.if
policy/modules/services/virt.te

Make qemu policy module be optional in virt module.

Make qemu optional in virt

---

policy/modules/system/init.if
policy/modules/system/systemd.if

Reverts SELinuxProject/refpolicy#822

Revert "systemd: Fix systemd_write_notify_socket()."

---

policy/modules/admin/bootloader.te
policy/modules/services/networkmanager.fc
policy/modules/system/logging.te
policy/modules/system/lvm.te
policy/modules/system/systemd.te

Commit messages have more information

Misc fixes

---

policy/modules/services/knot.if
policy/modules/services/knot.te

See https://github.com/SELinuxProject/refpolicy/pull/867#issuecomment-2696704152

use init_use_script_ptys for knotc in initscript

---

policy/modules/services/xserver.if
policy/modules/services/xserver.te

Usability fixes for the Qt library used by some graphical applications.

xserver: usability fixes for the Qt library

---

policy/modules/services/seatd.fc
policy/modules/services/seatd.if
policy/modules/services/seatd.te

May need one or two more rules in the future as I've only tested on one compositor I have policy for, but should be pretty much ready to go.

seatd: new policy module

---

policy/modules/system/systemd.te

systemd: Add syslog access to systemd-notify.

---

testing/check_fc_files.py

Fixes issue in PR #1025 github check.

check_fc_files.py: Add a version suffix match.
