policy/modules/system/iscsi.te
For the 2nd patch, I'm not sure if it's better to allow libvirt to connect to the socket or to add a domain for iscsiadm and allow the transition to that domain
Edit: I removed the 2nd patch, this was not enough, it's probably better to go for a private type for iscsiadm as it's requires more permissions (capability, creation of a lock file in /run/lock,...)
=> Bug fixes for Iscsi

policy/modules/system/lvm.te
On musl libc system lvm requires map permission.
=> Add map permission to lvm_t on lvm_metadata_t.

policy/modules/services/ssh.if
When creating a session for a new user, sshd performs a stat() call
somewhere:
type=AVC msg=audit(1502951786.649:211): avc:  denied  {
dac_read_search } for  pid=274 comm="sshd" capability=2
scontext=system_u:system_r:sshd_t tcontext=system_u:system_r:sshd_t
tclass=capability permissive=1
type=SYSCALL msg=audit(1502951786.649:211): arch=c000003e syscall=4
success=no exit=-2 a0=480e79b300 a1=7ffe0e09b080 a2=7ffe0e09b080
a3=7fb2aa321b20 items=0 ppid=269 pid=274 auid=1000 uid=0 gid=0
euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1
comm="sshd" exe="/usr/bin/sshd" subj=system_u:system_r:sshd_t
key=(null)
type=PROCTITLE msg=audit(1502951786.649:211):
proctitle=737368643A2076616772616E74205B707269765D
=> ssh: use dac_read_search instead of dac_override

policy/modules/system/selinuxutil.te
When restorecond calls selinux_restorecon(), libselinux scans /proc/mounts in a function named exclude_non_seclabel_mounts with the following comment (https://github.com/SELinuxProject/selinux/blob/libselinux-2.8/libselinux/src/selinux_restorecon.c#L224-L230):
/*
* This is called once when selinux_restorecon() is first called.
* Searches /proc/mounts for all file systems that do not support extended
* attributes and adds them to the exclude directory table.  File systems
* that support security labels have the seclabel option, return
* approximate total file count.
*/
The "approximate total file count" is computed using statvfs(), which results in a system call to statfs().
The cgroup filesystem supports security label (/proc/mounts shows "seclabel") so restorecond uses statfs to try …
=> selinuxutil: allow restorecond to try counting the number of files in cgroup fs

policy/modules/system/init.if, policy/modules/system/logging.te
type=AVC msg=audit(1546723651.696:2091): avc:  denied  { read } for
pid=240 comm="systemd-journal" name="invocation:user@1000.service"
dev="tmpfs" ino=17614 scontext=system_u:system_r:syslogd_t
tcontext=system_u:object_r:init_var_run_t tclass=lnk_file
permissive=0
type=AVC msg=audit(1546723651.799:2092): avc:  denied  { read } for
pid=240 comm="systemd-journal" name="invocation:dbus.service"
dev="tmpfs" ino=12542 scontext=system_u:system_r:syslogd_t
tcontext=system_u:object_r:init_var_run_t tclass=lnk_file
permissive=0
``ls -lZ`` on these files gives:
lrwxrwxrwx. 1 root root system_u:object_r:init_var_run_t 32
/run/systemd/units/invocation:user@1000.service -> a12344e990e641d9a43065b2d1e115a7
lrwxrwxrwx. 1 root root system_u:object_r:init_var_run_t 32 …
=> Allow systemd-journald to read systemd unit symlinks

policy/modules/services/cgmanager.fc, policy/modules/services/gssproxy.fc
For some services, the program responsible for the service has a file context which is defined only when it is installed in `/usr/sbin`. This does not work on Arch Linux, where every program is in `/usr/bin` (`/usr/sbin` is a symlink to `/usr/bin`).
Add relevant file contexts for `/usr/bin/$PROG` when `/usr/sbin/$PROG` exists.
=> Label service binaries in /usr/bin like /usr/sbin

policy/modules/admin/logrotate.te, policy/modules/apps/userhelper.te, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/logging.te, policy/modules/system/systemd.te
The name of these interfaces is clearer that way.
This comes from a suggestion from https://lore.kernel.org/selinux-refpolicy/dedf3ce8-4e9f-2313-6799-bbc9dc3a8124@ieee.org/
=> init: rename *_pid_* interfaces to use "runtime"

policy/modules/system/selinuxutil.te
As restorecond dereferences symlinks when it encounters them in user home directories, allow this access.
=> selinuxutil: allow restorecond to read symlinks

policy/modules/system/selinuxutil.te
restorecond uses libselinux's selinux_restorecon() to relabel files, which dereferences symlinks in a useless call to statfs(). This produces AVC denials which are noisy.
Fixes: https://github.com/SELinuxProject/refpolicy/pull/22
=> selinuxutil: restorecond is buggy when it dereferencies symlinks

policy/modules/services/dbus.te
When using a systemd service with dynamic UID, dbus-daemon reads symlinks in `/run/systemd/dynamic-uid/`:
type=SYSCALL msg=audit(1547313774.993:373): arch=c000003e
syscall=257 success=yes exit=12 a0=ffffff9c a1=7f7ccdc6ec72 a2=90800
a3=0 items=0 ppid=1 pid=282 auid=4294967295 uid=81 gid=81 euid=81
suid=81 fsuid=81 egid=81 sgid=81 fsgid=81 tty=(none) ses=4294967295
comm="dbus-daemon" exe="/usr/bin/dbus-daemon"
subj=system_u:system_r:system_dbusd_t key=(null)
type=AVC msg=audit(1547313774.993:373): avc:  denied  { read } for
pid=282 comm="dbus-daemon" name="dynamic-uid" dev="tmpfs" ino=12688
scontext=system_u:system_r:system_dbusd_t
tcontext=system_u:object_r:init_var_run_t tclass=dir permissive=1
type=SYSCALL msg=audit(1547313774.993:374): arch=c000003e
syscall=267 success=yes exit=7 …
=> dbus: allow using dynamic UID

policy/modules/roles/sysadm.te
On a virtual machine using haveged daemon, running ``ps`` from a ``sysadm_t`` user leads to the following output:
$ ps -eH -o label,user,pid,cmd
...
system_u:system_r:init_t        root         1 /sbin/init
system_u:system_r:syslogd_t     root       223   /usr/lib/systemd/systemd-journald
system_u:system_r:lvm_t         root       234   /usr/bin/lvmetad -f
system_u:system_r:udev_t        root       236   /usr/lib/systemd/systemd-udevd
system_u:system_r:entropyd_t    65306      266   /usr/bin/haveged --Foreground --verbose=1
User 65306 is a dynamic user attributed by systemd:
$ cat /var/run/systemd/dynamic-uid/65306
haveged
Running ``ps`` leads to the following log:
type=USER_AVC msg=audit(1549830356.959:1056): pid=278 uid=81
auid=4294967295 ses=4294967295 …
=> sysadm: allow resolving dynamic users

policy/modules/kernel/corenetwork.te.in, policy/modules/services/stubby.fc, policy/modules/services/stubby.if, policy/modules/services/stubby.te
Stubby is a DNS resolver that encrypts DNS queries and transmits them to
a resolver in a TLS channel. It therefore requires less permissions than
a traditionnal DNS resolver such as named or unbound (provided by module
"bind").
DNS-over-TLS uses TCP port 853, which does not seem to conflict with
existing ports.
cf. https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby
This program is packaged for Arch Linux, Debian, etc.
=> Add policy for stubby DNS resolver

policy/modules/system/logging.if
Since systemd 241, systemd-journald is using `kill(pid, 0)` in order to find dead processes and reduce its cache. The relevant commit is https://github.com/systemd/systemd/commit/91714a7f427a6c9c5c3be8b3819fee45050028f3 ("journald: periodically drop cache for all dead PIDs"). This commit added a call to `pid_is_unwaited(c->pid)`, which is a function implemented in https://github.com/systemd/systemd/blob/v241/src/basic/process-util.c#L936 :
```c
bool pid_is_unwaited(pid_t pid) {
/* Checks whether a PID is still valid at all, including a zombie */
if (pid < 0)
return false;
if (pid <= 1) /* If we or PID 1 would be dead and have been waited for, this code would not be running */
return true;
if (pid == getpid_cached())
return true;
if (kill(pid, 0) >= 0)
return true;
return errno != ESRCH;
} …
```
=> Allow systemd-journald to use kill(pid, 0) on every process

policy/modules/system/selinuxutil.te
When the policy for restorecond was introduced, it contained a rule which allowed restorecond to read every file except `shadow_t` (cf. https://github.com/SELinuxProject/refpolicy/commit/724925579d2933ab642e0104b2fa7aaded9a7ceb#diff-301316a33cafb23299e43112dc2bf2deR439):
auth_read_all_files_except_shadow(restorecond_t)
Since 2006, the policy changed quite a bit, but this access remained. However restorecond does not need to read every available file.
This is related to this comment: https://github.com/SELinuxProject/refpolicy/pull/22#issuecomment-454976379
=> Remove a broad read-files rule for restorecond

policy/modules/system/systemd.fc, policy/modules/system/systemd.te
systemd-update-done sends logs to journald like other services, as shown by the following AVC:
type=AVC msg=audit(1550865504.453:76): avc:  denied  { sendto } for
pid=277 comm="systemd-update-" path="/run/systemd/journal/socket"
scontext=system_u:system_r:systemd_update_done_t
tcontext=system_u:system_r:syslogd_t tclass=unix_dgram_socket
permissive=1
type=AVC msg=audit(1550865504.453:76): avc:  denied  { write } for
pid=277 comm="systemd-update-" name="socket" dev="tmpfs" ino=10729
scontext=system_u:system_r:systemd_update_done_t
tcontext=system_u:object_r:devlog_t tclass=sock_file permissive=1
type=AVC msg=audit(1550865504.453:76): avc:  denied  { connect } for
pid=277 comm="systemd-update-"
scontext=system_u:system_r:systemd_update_done_t
tcontext=system_u:system_r:systemd_update_done_t …
=> Update systemd-update-done policy

support/genhomedircon.py
Fixes errors like this:
```
Traceback (most recent call last):
File "support/genhomedircon.py", line 490, in <module>
errorExit("Options Error " + error)
TypeError: Can't convert 'GetoptError' object to str implicitly
```
=> genhomedircon.py: Fix top-level exception handling.

policy/modules/kernel/kernel.te, policy/modules/system/init.te, policy/modules/system/systemd.te, policy/modules/system/udev.te
Remove use of kernel_unconfined() by systemd_nspawn and udev write to its own executable.
=> Misc system fixes.

policy/modules/system/init.if
The role transition for directly executing an init script should only
happen if direct_sysadm_daemon is enabled and only on non-systemd
systems.
@perfinion 
@bigon 
@fishilico 
@bachradsusi
=> init: Revise conditions in init_startstop_service().

policy/modules/services/xserver.if
The Qt library version 5 requires to write xserver_tmp_t files upon starting up applications (tested on version 5.12.1).
---
policy/modules/services/xserver.if |    1 +
1 file changed, 1 insertion(+)
=> Qt library version 5 requires unprivileged users to write xserver_tmp_t

policy/modules/kernel/devices.if, policy/modules/kernel/kernel.te, policy/modules/services/plymouthd.if, policy/modules/services/xserver.te
I made some changes to the policy to get plymouth working in enforcing.  I have noticed that since plymouthd is started very early during boot it is running as kernel_t.  Some of the permissions are for kernel_t even though they are for the plymouthd process.
This is rebased on top of recent changes.
=> Resolve issues with plymouth in enforcing

policy/modules/admin/logrotate.te
fail2ban logrotate configuration runs "fail2ban-client flushlogs" after
rotating the logs
=> Allow logrotate to execute fail2ban-client

Makefile, support/Makefile.devel
Without this fix, building a custom module in a directory that contains
a file with special characters in its name (e.g. '(') triggers a syntax
error:
```
$ cat >foo.te <<EOF
module foo 1.0;
require {
class file entrypoint;
type shell_exec_t;
type vmtools_unconfined_t;
}
allow vmtools_unconfined_t shell_exec_t : file entrypoint;
EOF
$ touch "my broken (file)"
$ make -f /usr/share/selinux/devel/Makefile foo.pp
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `find anaconda-ks.cfg my broken (file) vncserver.strace systemd.strace rhel-server-7.6-x86_64-boot.iso rt_minimal.c vnc.cil foo.te rsyslog tmp virt-install.log evil_banner.sh livemedia.log program.log foo.if rhel7-minimal.ks TestZip.java TestZip.class foo.fc sudoloop foo.pp strace.log -maxdepth 0 -type …
```
=> Fix find commands in Makefiles

policy/modules/services/ulogd.fc, policy/modules/services/ulogd.te
While installing Debian on a server, I encountered some issues with the firewall logging. Since Debian 10, nftables is used instead of the traditional iptables, and a logging service seems to be required in order to log packets that match some rules. ulogd is such a service, but it is missing a few things in order to start properly on my server.
This Pull Request aims at fixing a few things in order for ulogd to start in enforcing mode.
For information, I switched between permissive and enforcing mode so I do not know whether these changes are enough for ulogd to start from a clean boot.
=> Adjust ulogd policy for Debian

policy/modules/services/entropyd.te
haveged listens to commands using a Unix socket (at path `"\0/sys/entropy/haveged"` according to https://github.com/jirka-h/haveged/blob/1.9.4/src/havegecmd.h#L34).
The implementation of this server is available on https://github.com/jirka-h/haveged/blob/1.9.4/src/havegecmd.c .
This fixes the following denial:
type=AVC msg=audit(1551002989.396:27): avc:  denied  { listen } for
pid=262 comm="haveged"
path=002F7379732F656E74726F70792F68617665676564
scontext=system_u:system_r:entropyd_t
tcontext=system_u:system_r:entropyd_t tclass=unix_stream_socket
permissive=1
=> entropyd: allow haveged to create a Unix socket to received commands

policy/modules/services/ulogd.fc
The pattern only matched `/run/ulog`, not its content.
=> ulogd: fix pattern for /run/ulog directory

policy/modules/services/monit.fc
This seems to be a misspelling, and there is no reason which would explain why monit's init script would be labeled with a different sensitivity while the main binary uses `s0`.
=> monit: use s0 instead of s9

policy/modules/apps/java.fc
The following pattern seems to match much more than intended:
/usr/(.*/)?bin/java[^-]*
According to the commit which introduced it (https://github.com/TresysTechnology/refpolicy/commit/0190325c18c30d31145950c1eaf80d12fa6c9db3), the aim was to match `java1.4`, `java5`, `java6`, and not `java-config` nor `java-check-environment`. The issue is that the pattern also matches sub-directories such as:
/usr/share/my-application/bin/java/myfile
Prevent this by adding `/` in the character blacklist of the pattern.
=> java: reduce the scope of the pattern in for java entry points

policy/modules/system/libraries.fc
Patterns using this have a small issue:
/opt/Adobe/Reader.?/Reader/intellinux
The issue is that the dot can also match a slash. A bettern pattern would be:
/opt/Adobe/Reader[^/]?/Reader/intellinux
In this specific case, the intent is to match digits (like `/opt/Adobe/Reader9`). Use `[0-9]` for this.
=> libraries: match a digit in Adobe Reader directories

policy/modules/services/drbd.fc
In order to match `/usr/lib/ocf/resource.d/linbit/drbd`, the dot needs to be escaped, not the `d`.
=> drbd: fix pattern for /usr/lib/ocf/resource.d/linbit/drbd

policy/modules/services/rpcbind.fc
There are two patterns that define file contexts for `/run/rpc.statd.pid`:
* in `policy/modules/services/rpcbind.fc`:
/run/rpc.statd\.pid	--	gen_context(system_u:object_r:rpcbind_var_run_t,s0)
* in `policy/modules/services/rpc.dc`:
/run/rpc\.statd\.pid	--	gen_context(system_u:object_r:rpcd_var_run_t,s0)
They coexist even though their labels differ because the first one uses a unescaped dot. As it does not seem to exist other files matching the first pattern, remove it in order to only keep the second one.
=> rpcbind: remove redundant file context for /run/rpc.statd.pid

policy/modules/kernel/files.fc
The pattern that matches /usr/include uses a dot, in order probably to avoid calling m4's function `include()`. This also matches other paths such as `/usr/inclu/e`. Such a side-effect can be avoided by using a more restrictive pattern such as `/usr/includ[e](/.*)?`.
Mailing-list discussion: https://lore.kernel.org/selinux-refpolicy/CAJfZ7=krh_TaCBQzFxLM394Sc5-82ZO0DdcfvWON-RXu-wqBVw@mail.gmail.com/t/#u
=> files: reduce the scope of the pattern matching /usr/include

policy/modules/admin/portage.fc, policy/modules/admin/rpm.fc, policy/modules/apps/chromium.fc, policy/modules/apps/mozilla.fc, policy/modules/kernel/corecommands.fc, policy/modules/kernel/files.fc, policy/modules/services/apache.fc, policy/modules/services/boinc.fc, policy/modules/services/cgmanager.fc, policy/modules/services/dirmngr.fc, policy/modules/services/dovecot.fc, policy/modules/services/gssproxy.fc, policy/modules/services/hostapd.fc, policy/modules/services/mon.fc, policy/modules/services/nx.fc, policy/modules/services/pkcs.fc, policy/modules/services/policykit.fc, policy/modules/services/virt.fc, policy/modules/system/ipsec.fc, policy/modules/system/libraries.fc, policy/modules/system/logging.fc, policy/modules/system/miscfiles.fc, policy/modules/system/modutils.fc, policy/modules/system/udev.fc
In a pattern, a dot can match any character, including slash. It makes sense when it is combined with `?`, `+` or `*`, but makes little sense when left alone.
Most of the time, the label was for file containing dots, where the dot was not escaped. A few times, the dot was really intended to match any character. In such case, `[^/]` better suits the intent.
=> Remove unescaped single dot from the policy

policy/modules/services/entropyd.te, policy/modules/system/systemd.if
When a service is configured with `PrivateDevices=yes`, its `/dev` directory has label `tmpfs_t`. This requires allowing more accesses in order for the service to use `/dev`.
This is related to https://github.com/SELinuxProject/refpolicy/pull/61
=> systemd: introduce a new attribute for services using PrivateDevices=yes

policy/modules/kernel/corecommands.fc, policy/modules/services/ssh.te, policy/modules/system/authlogin.fc, policy/modules/system/authlogin.if, policy/modules/system/authlogin.te, policy/modules/system/init.fc, policy/modules/system/locallogin.te
Debian's PAM configuration uses a patched `pam_motd` module that runs files in `/etc/update-motd.d/` in order to generate a dynamic Message Of The Day (MOTD). By default, there is only one script:
$ cat /etc/update-motd.d/10-uname
#!/bin/sh
uname -snrvm
According to https://wiki.debian.org/motd, the script is executed through `run-parts`:
```C
if (!system("/usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
run-parts --lsbsysinit /etc/update-motd.d > /run/motd.dynamic.new"))
rename("/run/motd.dynamic.new", "/run/motd.dynamic");
```
This requires allowing `pam_motd` users to execute `bin_t` commands (`/usr/bin/env`) and shells (`/bin/sh`), and to manage `/run/motd.dynamic*` files.
Allow relevant accesses for Debian-based systems.
In order for this to fully …
=> Allow Debian to generate a dynamic motd when users log in

policy/modules/system/libraries.fc
In libraries.fc:
- `(/.*?)` is very likely a misspelling for `(/.*)?`
- `sidecars/*` with `--` as file type is very likely a misspelling for `sidecars/.+`, in order to match files that are shared libraries.
- `/opt/netbeans(.*/)?jdk` matches `/opt/netbeansjdk`, which is buggy.
In Apache NetBeans 11.1 downloaded from https://netbeans.apache.org/download/nb111/nb111.html, there are files such as `profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so`.
Several websites document installing NetBeans in directories such as `/opt/netbeans-11.1/`, so the installed `.so` files are probably installed in `/opt/netbeans-11.1/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so`.
There is thus an issue with the current pattern:
/opt/netbeans(.*/)?jdk.*/linux/.+\.so(\.[^/]*)*
This …
=> libraries: fix some misspellings in patterns

policy/modules/apps/java.fc
`/usr/lib/jvm/java(.*/)bin(/.*)?` uses misleading parentheses around `.*/`. In some cases, a pattern with `(.*/)` is a misspelling to `(.*/)?`, but not here (`/usr/lib/jvm/javabin/` never exists).
Moreover, using `.*` here is right, as the pattern matches the content of subdirectories of `/usr/lib/jvm/` which names are prefixed by `java`. More precisely, the pattern matches for example:
- programs in `/usr/lib/jvm/java-10-openjdk/bin`
- programs in `/usr/lib/jvm/java-8-openjdk/jre/bin`
In the end, the pattern does not have any error, but the parentheses are misleading. Remove them.
=> java: remove unnecessary parentheses in pattern

Vagrantfile
When debugging issues on Debian's policy, it is useful to have a minimal Debian install in a virtual machine. Vagrant provides a straightforward way of configuring such a virtual machine, using base images and provisioning scripts.
There were already a `Vagrantfile` in the repository with Fedora 24. This PR updates it to Fedora 30 and adds a machine for Debian.
For you information, I have been using a VM to help packaging SELinux tools and test refpolicy on Arch Linux for 3.5 years. My configuration of this machine is available on https://github.com/archlinuxhardened/selinux/tree/master/_vagrant.
=> Upgrade Vagrant VM to Fedora 30 and add a Debian 10 VM

policy/modules/services/ntp.te
`systemd-timesyncd` uses `network_is_online()` [1], which calls `sd_network_get_operational_state()` [2], which reads `/run/systemd/netif/state` [3]:
```C
r = parse_env_file(NULL, "/run/systemd/netif/state", "OPER_STATE", &s);
```
On a Debian virtual machine created with Vagrant, `/run/systemd/netif/state` contains:
```sh
OPER_STATE=routable
DNS=192.168.121.1 172.28.128.1
```
`systemd-timesyncd`'s access produces the following logs:
type=AVC msg=audit(1567359197.660:323): avc:  denied  { read } for
pid=230 comm="systemd-timesyn" name="state" dev="tmpfs" ino=24564
scontext=system_u:system_r:ntpd_t
tcontext=system_u:object_r:systemd_networkd_var_run_t tclass=file
permissive=1
type=AVC msg=audit(1567359197.660:324): avc:  denied  { open } for
pid=230 comm="systemd-timesyn" …
=> ntp: allow systemd-timesyncd to read network status

policy/modules/services/cups.fc
The pattern `/opt/brother/Printers(.*/)?inf(/.*)?` matches the content of directories such as `/opt/brother/Printersinf/`, which seems buggy. On several systems, `/opt/brother/Printers/` is a directory that contains directories named as printer models.
Add a `/` before `(.*/)?` in order to make sure subdirectories of `/opt/brother/Printers` named `inf` are matched by the pattern.
=> cups: add a slash to match /opt/brother/Printers/

policy/modules/admin/apt.te
On a Debian 10 virtual machine, when running `apt-get update`, the following messages are logged to `audit.log`, several times:
type=AVC msg=audit(1567717969.162:1639): avc:  denied  {
nnp_transition } for  pid=5538 comm="apt-config"
scontext=sysadm_u:sysadm_r:apt_t tcontext=sysadm_u:sysadm_r:dpkg_t
tclass=process2 permissive=0
type=SELINUX_ERR msg=audit(1567717969.162:1639):
op=security_bounded_transition seresult=denied
oldcontext=sysadm_u:sysadm_r:apt_t
newcontext=sysadm_u:sysadm_r:dpkg_t
type=SYSCALL msg=audit(1567717969.162:1639): arch=c000003e
syscall=59 success=yes exit=0 a0=55ebb33d7780 a1=55ebb33ed610
a2=7ffedd210980 a3=0 items=0 ppid=5537 pid=5538 auid=1000 uid=100
gid=65534 euid=100 suid=100 fsuid=100 egid=65534 sgid=65534
fsgid=65534 tty=(none) ses=45 comm="dpkg" …
=> apt: allow transition from apt_t to dpkg_t with NNP

policy/modules/admin/apt.te
Since `apt` 1.8.1 (more precisely since commit https://salsa.debian.org/apt-team/apt/commit/60cc44d160af02c49614653c97bfa3e4e5c9601d), `apt` calls D-Bus method `Inhibit` of interface `org.freedesktop.login1.Manager` in order to prevent a shutdown from happening while installing software.
The call from `apt` to `systemd-logind` was already allowed through `unconfined_dbus_send(apt_t)`, but not the reply, which triggered the following audit log:
type=USER_AVC msg=audit(1567780304.196:651): pid=287 uid=105
auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t
msg='avc:  denied  { send_msg } for msgtype=method_return
dest=:1.137 spid=290 tpid=29557
scontext=system_u:system_r:systemd_logind_t
tcontext=sysadm_u:sysadm_r:apt_t tclass=dbus permissive=0
exe="/usr/bin/dbus-daemon" …
=> apt: allow preventing shutdown by calling a systemd-logind D-Bus method

policy/modules/system/authlogin.fc
When starting `tmux` on Debian, the following audit log appears:
type=AVC msg=audit(1567781766.314:820): avc:  denied  {
execute_no_trans } for  pid=6686 comm=746D75783A20736572766572
path="/usr/lib/x86_64-linux-gnu/utempter/utempter" dev="vda1"
ino=545302 scontext=sysadm_u:sysadm_r:sysadm_screen_t
tcontext=system_u:object_r:lib_t tclass=file permissive=0
`/usr/lib/x86_64-linux-gnu/utempter/utempter` is indeed labeled as `system_u:object_r:lib_t`, which is wrong.
=> authlogin: label utempter correctly on Debian

policy/modules/apps/irc.fc, policy/modules/apps/irc.te
WeeChat is an extensible IRC client: https://weechat.org/
* Label WeeChat program and configuration files like other IRC clients
* Allow WeeChat to create a pipe in `~/.weechat/weechat_fifo`
* Allow WeeChat to read `/proc/sys/crypto/fips_enabled`
* Allow WeeChat to use a Unix datagram socket with its forked children
* Allow other accesses
=> irc: add WeeChat policy

policy/modules/system/systemd.te
When bringing up a Wireguard interface with `wg-quick up wg0` from a `sysadm_u:sysadm_r:sysadm_t` session, `systemd --user` spams the logs with this event repeated between 100 and 200 times per second:
type=AVC msg=audit(1567798007.591:138076): avc:  denied  { read }
for  pid=711 comm="systemd"
scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=sysadm_u:sysadm_r:sysadm_systemd_t
tclass=netlink_kobject_uevent_socket permissive=0
=> systemd: allow systemd --user to receive messages from netlink_kobject_uevent_socket

policy/modules/roles/sysadm.te, policy/modules/services/wireguard.fc, policy/modules/services/wireguard.if, policy/modules/services/wireguard.te
WireGuard is a fast, modern, secure VPN tunnel, according to https://www.wireguard.com/. In order to install it, the mostly documented way consists in building and installing an out-of-tree kernel module and using userland tools to configure this module (`wg` and `wg-quick`).
* WireGuard is like `ip`: the userland tool communicates with the kernel module through a netlink socket.
* WireGuard is like `iptables`: there is no daemon, but some distributions ship systemd units that restores a WireGuard configuration when started.
* WireGuard is like other services: its configuration files are in `/etc` and it can use `/run` and `/tmp`.
Create a new policy module which handles all of this.
=> Add a policy module for WireGuard VPN

policy/modules/system/modutils.te
When installing `wireguard-dkms` on Debian 10 (with refpolicy `master` in enforcing mode), `apt` encountered a fatal error when configuring WireGuard's kernel module, because it was not allowed to read `/boot/System.map-4.19.0-5-amd64`.
Moreover, `depmod` and `modprobe` were not allowed to use the pseudo-tty provided by `apt` when these commands are run when installing software.
Here are two commits that fix these issues.
=> modutils: make installing DKMS package work on Debian

policy/modules/system/systemd.te
`systemd-modules-load.service` needs to read file `/sys/module/${MODULE}/initstate` for each `${MODULE}` defined in `/etc/modules-load.d/`. These files are labeled `sysfs_t`.
This fixes:
type=AVC msg=audit(1567804818.331:138713): avc:  denied  { read }
for  pid=31153 comm="systemd-modules" name="initstate" dev="sysfs"
ino=14778 scontext=system_u:system_r:systemd_modules_load_t
tcontext=system_u:object_r:sysfs_t tclass=file permissive=0
=> systemd: allow systemd-modules-load.service to read sysfs

policy/modules/admin/sudo.if
When `/etc/sudoers` contains `Defaults use_pty`, `sudo` creates a new pseudo-pty when running a command. This is currently denied from a `sysadm_u` session:
type=AVC msg=audit(1567807315.843:13300): avc:  denied  { read write
} for  pid=5053 comm="sudo" name="ptmx" dev="devtmpfs" ino=1108
scontext=sysadm_u:sysadm_r:sysadm_sudo_t
tcontext=system_u:object_r:ptmx_t tclass=chr_file permissive=0
As it seems logical for the newly-created pty to be labeled `user_devpts_t`, use `userdom_create_user_pty()` to allow this.
Then, a new denial appears:
type=AVC msg=audit(1567808670.441:13341): avc:  denied  { setattr }
for  pid=30256 comm="sudo" name="9" dev="devpts" ino=12
scontext=sysadm_u:sysadm_r:sysadm_sudo_t
tcontext=sysadm_u:object_r:user_devpts_t tclass=chr_file
permissive=0
type=SYSCALL …
=> sudo: allow using use_pty flag

policy/modules/services/hostapd.fc, policy/modules/services/knot.fc, policy/modules/services/tpm2.fc
Some recent modifications added patterns in `.fc` files for programs in `/usr/sbin` without adding the patterns for `/usr/bin`. On Arch Linux, where `/usr/sbin` is a symlink to `/usr/bin`, such patterns are never matched.
Add the missing patterns.
=> Label programs in /usr/bin like /usr/sbin

policy/modules/services/ulogd.te
On a Debian 10 system, I saw denials for `ulogd` service:
It uses a pipe with itself:
type=AVC msg=audit(1567874422.328:13744): avc:  denied  { write }
for pid=11416 comm="ulogd" path="pipe:[29006]" dev="pipefs"
ino=29006 scontext=system_u:system_r:ulogd_t
tcontext=system_u:system_r:ulogd_t tclass=fifo_file permissive=0
It enumerates users in `/run/systemd/dynamic-uid/` when changing to the `ulog` user (which is not dynamic):
type=AVC msg=audit(1567874512.576:13748): avc:  denied  { read } for
pid=18290 comm="ulogd" name="dynamic-uid" dev="tmpfs" ino=16527
scontext=system_u:system_r:ulogd_t
tcontext=system_u:object_r:init_var_run_t tclass=dir permissive=0
It connects to the system D-Bus socket in order to call `GetDynamicUser`:
type=AVC msg=audit(1567875114.147:13761): avc:  denied  { …
=> ulogd: adjust policy for Debian

policy/modules/services/bitlbee.te
On Debian 10, starting bitlbee daemon leads to:
type=AVC msg=audit(1567941717.044:14204): avc:  denied  { search }
for  pid=5704 comm="bitlbee" name="dbus" dev="tmpfs" ino=13798
scontext=system_u:system_r:bitlbee_t
tcontext=system_u:object_r:system_dbusd_var_run_t tclass=dir
permissive=0
type=AVC msg=audit(1567941717.044:14205): avc:  denied  { read } for
pid=5704 comm="bitlbee" name="direct:64707" dev="tmpfs" ino=16529
scontext=system_u:system_r:bitlbee_t
tcontext=system_u:object_r:init_var_run_t tclass=lnk_file
permissive=0
type=AVC msg=audit(1567941756.020:14208): avc:  denied  { search }
for  pid=6363 comm="bitlbee" name="dbus" dev="tmpfs" ino=13798
scontext=system_u:system_r:bitlbee_t
tcontext=system_u:object_r:system_dbusd_var_run_t tclass=dir
permissive=0
type=AVC …
=> bitlbee: allow using GetDynamicUser on Debian

policy/modules/apps/chromium.fc
Arch Linux installs Chromium in `/usr/lib/chromium/` like Debian. Instead of adding a new ``ifdef(`distro_arch')`` block, remove the restriction in `chromium.fc`.
=> chromium: remove distro-specific ifdef

policy/modules/system/systemd.te
Since systemd 237 (commit https://github.com/systemd/systemd/commit/05d0c2e3cfb5aac8bc14b68a12a6c3ef3e88e3a3), `systemd-networkd` requires a generic netlink socket in order to start. Otherwise, it fails to start and systemd's journal contains:
audit[19262]: AVC avc:  denied  { create } for  pid=19262
comm="systemd-network" scontext=system_u:system_r:systemd_networkd_t
tcontext=system_u:system_r:systemd_networkd_t
tclass=netlink_generic_socket permissive=0
audit[19262]: SYSCALL arch=c000003e syscall=41 success=no exit=-13
a0=10 a1=80803 a2=10 a3=20 items=0 ppid=1 pid=19262 auid=4294967295
uid=102 gid=103 euid=102 suid=102 fsuid=102 egid=103 sgid=103
fsgid=103 tty=(none) ses=4294967295 comm="systemd-network"
exe="/usr/lib/systemd/systemd-networkd"
subj=system_u:system_r:systemd_networkd_t …
=> systemd-networkd: allow creating a generic netlink socket

policy/modules/admin/sudo.if
When resizing the X11 window of a terminal running `sudo` on a remote Debian 10 system (through `ssh`), `sudo` receives signal `SIGWINCH` and forwards it to its children.
Here are two commits in order to allow such forwarding in two cases:
* when `sudo` is used to gain `root` privileges from another user (which is associated with `sysadm_u`)
* and when `sudo` is used by `root` to get a shell as an unprivileged user.
=> Allow sudo to transmit SIGWINCH

policy/modules/system/systemd.te, policy/modules/system/udev.te
Since systemd 242 (commit https://github.com/systemd/systemd/commit/6c8a2c679313f8283514923daf65f5e9d050d94c), systemd and its services read `/proc/sys/kernel/osrelease` in order to detect whether they are running in Microsoft's WSL (Windows Subsystem for Linux).
This leads to logs such as:
type=AVC msg=audit(1568445663.990:10): avc:  denied  { read } for
pid=401 comm="systemd-modules" name="osrelease" dev="proc" ino=13319
scontext=system_u:system_r:systemd_modules_load_t
tcontext=system_u:object_r:sysctl_kernel_t tclass=file permissive=1
type=AVC msg=audit(1568445663.990:10): avc:  denied  { open } for
pid=401 comm="systemd-modules" path="/proc/sys/kernel/osrelease"
dev="proc" ino=13319
scontext=system_u:system_r:systemd_modules_load_t
tcontext=system_u:object_r:sysctl_kernel_t …
=> systemd: allow detecting Windows Subsystem for Linux

policy/modules/system/systemd.te
When `systemd-netwokd` receives DHCP option 12 (hostname), it changes the hostname by calling method `SetHostname` from interface `org.freedesktop.hostname1` provided by `systemd-hostnamed`: https://github.com/systemd/systemd/blob/v243/src/network/networkd-manager.c#L1946
This access is currently denied and reported:
type=USER_AVC msg=audit(1568403789.952:36): pid=288 uid=105
auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t
msg='avc:  denied  { send_msg } for msgtype=method_call
interface=org.freedesktop.hostname1 member=SetHostname
dest=org.freedesktop.hostname1 spid=233 tpid=317
scontext=system_u:system_r:systemd_networkd_t
tcontext=system_u:system_r:systemd_hostnamed_t tclass=dbus
permissive=1  exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=?
terminal=?'
=> systemd-networkd: allow communicating with hostnamed

policy/modules/system/selinuxutil.te
Commit 61b72e0796d9 ("selinuxutil: adjustments") removed negative permission
matching for newrole_t:process. One of the removed permission was setcap which
is needed by newrole as it tries to drop capabilities:
$ newrole -r sysadm_r
Sorry, newrole failed to drop capabilities
: Permission denied
type=PROCTITLE msg=audit(09/06/2019 15:07:01.908:10821) : proctitle=newrole -r sysadm_r
type=SYSCALL msg=audit(09/06/2019 15:07:01.908:10821) : arch=x86_64
syscall=capset success=no exit=EACCES(Permission denied) a0=0x7fbe17d4cb6c
a1=0x7fbe17d4cb74 a2=0x7fbe17d4d5d0 a3=0x0 items=0 ppid=4981 pid=7255
auid=admin uid=admin gid=admin euid=admin
suid=admin fsuid=admin egid=admin sgid=admin fsgid=admin tty=tty1 ses=6
comm=newrole exe=/usr/bin/newrole subj=staff_u:staff_r:newrole_t:s0
key=(null)
type=AVC …
=> newrole: allow newrole to use setcap to drop capabilities

policy/modules/admin/portage.te
All callers of `consoletype_exec()` put it in an `optional_policy()` block but `portage`. This makes `consoletype` module mandatory when module `portage` is loaded, even when `consoletype` is not installed.
Fix this issue by introducing an `optional_policy()` block.
=> portage: really make consoletype module optional

policy/modules/system/systemd.if
`systemd --user` spawns programs from `/usr/lib/systemd/user-environment-generators/` in order to gather environment variables. On a Debian 10 virtual machine with gnupg, this directory contains:
$ ls -Z /usr/lib/systemd/user-environment-generators
system_u:object_r:bin_t 30-systemd-environment-d-generator
system_u:object_r:bin_t 90gpg-agent
For `sysadm`, these programs are run as `sysadm_t` (because there is a transition in `systemd_role_template()` in `systemd.if`: `corecmd_bin_domtrans($1_systemd_t, $3)`) but use file descriptors created by their parent process, which runs as `sysadm_systemd_t`. This leads to:
type=AVC msg=audit(1569756917.537:244): avc:  denied  { use } for
pid=9713 comm="30-systemd-envi"
path=2F6D656D66643A33302D73797374656D642D656E7669726F6E6D656E742D642D67656E657261 …
=> systemd: allow user environment helpers to communicate with systemd --user

policy/modules/system/systemd.te
`systemd --user` needs to:
* run `statfs()` on `/sys/fs/cgroup`, which is a `tmpfs` on Debian 10:
type=AVC msg=audit(1568544950.691:309): avc:  denied  { getattr }
for  pid=10128 comm="systemd" name="/" dev="tmpfs" ino=9656
scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:tmpfs_t tclass=filesystem permissive=0
type=SYSCALL msg=audit(1568544950.691:309): arch=c000003e
syscall=137 success=no exit=-13 a0=7f96e8b23ddb a1=7ffefbffb410
a2=7f96e7b3c2a0 a3=0 items=0 ppid=1 pid=10128 auid=1000 uid=1000
gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000
fsgid=1000 tty=(none) ses=14 comm="systemd"
exe="/usr/lib/systemd/systemd"
subj=sysadm_u:sysadm_r:sysadm_systemd_t key=(null)
type=PROCTITLE msg=audit(1568544950.691:309): …
=> systemd: allow more accesses to systemd --user

policy/modules/kernel/filesystem.if
`fs_read_cgroup_files()` grants access to reading files and to following symlinks (with `read_lnk_files_pattern($1, cgroup_t, cgroup_t)`). `fs_rw_cgroup_files()` does not include such a rule, which is needed in order to transparently use symlinks such as `/sys/fs/cgroup/cpu`. This access is currently denied, for example to `systemd --user` daemon:
type=AVC msg=audit(1569756917.537:242): avc:  denied  { getattr }
for  pid=9710 comm="systemd" path="/sys/fs/cgroup/cpu" dev="tmpfs"
ino=9683 scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:cgroup_t tclass=lnk_file permissive=0
type=SYSCALL msg=audit(1569756917.537:242): arch=c000003e
syscall=262 success=no exit=-13 a0=ffffff9c a1=7ffc605b1f70
a2=7ffc605b1ea0 a3=100 items=0 ppid=1 pid=9710 auid=1000 uid=1000
gid=1000 …
=> filesystem: allow following symlinks with fs_rw_cgroup_files()

INSTALL, testing/check_fc_files.py
Writing `.fc` files without any mistake is quite hard. Sometimes a regular expression pattern compiles fine but it does not match what is intended.
Add a script that detects some issues in `.fc` files. When this script is used directly (`./testing/check_fc_files.py`), it checks the content of `policy/`. The path to `policy/` can also be provided by option `-p`.
This is a first draft of the file, which has already found many issues in the policy, some of which have been fixed by recent Pull Requests.
=> Check the .fc files for common typos

.travis.yml
python3.5 is the oldest available one on bionic (though refpolicy requires only 3.4)
Also print the python3 (not 2) version during build
=> travis: force the use of python3.5

.travis.yml
Now that all issues reported by `testing/check_fc_files.py` have been fixed, call this script in Travis-CI in order to prevent common errors from being introduced in `.fc` files.
This follows https://github.com/SELinuxProject/refpolicy/pull/74.
=> .travis.yml: check the .fc files in CI

Makefile
Currently policy module directories must have a same ending.
Reproduce with:
```
mv policy/modules/admin/ policy/modules/adminapps
make conf
```
Results in:
```
...
cat policy/modules/adminapps/metadata.xml policy/modules/apps/metadata.xml > tmp/apps.xml
...
doc/policy.xml:4332: element layer: validity error : Element layer content does not follow the DTD, expecting (summary , module+), got (summary summary module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module module )
Document doc/policy.xml does …
```
=> fix Makefile for policy-module directories with same ending

policy/modules/apps/gpg.te
On Debian 10, when gpg-agent starts, it reads  `crypto.fips_enabled`:
type=AVC msg=audit(1569958604.280:42): avc:  denied  { open } for
pid=329 comm="gpg-agent" path="/proc/sys/crypto/fips_enabled"
dev="proc" ino=14687 scontext=sysadm_u:sysadm_r:gpg_agent_t
tcontext=system_u:object_r:sysctl_crypto_t tclass=file permissive=1
type=AVC msg=audit(1569958604.280:42): avc:  denied  { read } for
pid=329 comm="gpg-agent" name="fips_enabled" dev="proc" ino=14687
scontext=sysadm_u:sysadm_r:gpg_agent_t
tcontext=system_u:object_r:sysctl_crypto_t tclass=file permissive=1
=> gpg: allow gpg-agent to read crypto.fips_enabled sysctl

policy/modules/system/systemd.te
On Arch Linux, `/proc/sys/kernel/core_pattern` contains:
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
When a crash happens in a userspace application, this setting makes the kernel spawn `/usr/lib/systemd/systemd-coredump` from `kernel_t`:
type=AVC msg=audit(1569910108.877:336): avc:  denied  { execute }
for  pid=1087 comm="kworker/u2:3" name="systemd-coredump" dev="vda1"
ino=406365 scontext=system_u:system_r:kernel_t
tcontext=system_u:object_r:systemd_coredump_exec_t tclass=file
permissive=1
Introduce a transition to `systemd_coredump_t` to handle this.
=> systemd: make the kernel spawn systemd-coredump with a context transition

policy/modules/system/init.if, policy/modules/system/unconfined.te
Use the full init_pgm_spec_user_daemon_domain() to ensure correct
permissions.
=> unconfined: Fix systemd --user rule.

testing/check_fc_files.py
Some systemd units use `@` in their names.
Fixes: https://github.com/SELinuxProject/refpolicy/issues/131
=> testing/check_fc_files: allow @ character in file context patterns

Vagrantfile, support/vagrant-vm.cil
Hi,
Currently, `Vagrantfile` is configured to use `unconfined_u` for user `vagrant`. In order to test a system without `unconfined`, it is possible to use `sysadm_u` instead, but this triggers several issues.
* The most important one is caused by the way Vagrant syncs files when `vagrant rsync` is used. It runs `sudo rsync`, which makes a first transition to `sysadm_sudo_t` and then tries to execute `rsync_exec_t`, which does not work well. This issue can be solved by adding a transition to `sysadm_t` to the policy for this specific situation.
* Another issue comes from the fact that `vagrant` does not allocate a pseudo-terminal when running provisioning scripts. So every command that is run wants to use `sshd_t` `fifo_file`. This can also be solved by adding rules to the policy. I tried …
=> Allow using sysadm_u with Vagrantfile configuration

policy/modules/apps/cryfs.fc, policy/modules/apps/cryfs.if, policy/modules/apps/cryfs.te, policy/modules/roles/sysadm.te
CryFS (https://www.cryfs.org/) is a software that can be run by non-root users that have access to `/dev/fuse`. Its command is directly used to mount a directory (`/usr/bin/cryfs basedir mountpoint`), like command `mount`. Unmounting a mountpoint is done with `fusermount -u mountpoint`, `/usr/bin/fusermount` being a setuid-`root` program labeled `mount_exec_t`.
EncFS (https://www.arg0.net/encfs) is a similar software that has been considered insecure since a security audit in 2014 found vulnerabilities that are not yet fixed (like https://github.com/vgough/encfs/issues/9).
gocryptfs (https://nuetzlich.net/gocryptfs/) is a similar software that has been inspired by EncFS.
Allow users with role `sysadm` to use all these projects.
=> Add policy for CryFS, encfs and gocryptfs

policy/modules/kernel/devices.if, policy/modules/system/init.te
When spawning services such as `systemd-timedated` with systemd 244, systemd now mounts an inaccessible directory on `/dev/kmsg` and `/proc/kmsg`:
type=AVC msg=audit(1576535711.579:363): avc:  denied  { mounton }
for  pid=1497 comm="(imedated)"
path="/run/systemd/unit-root/dev/kmsg" dev="devtmpfs" ino=9055
scontext=system_u:system_r:init_t
tcontext=system_u:object_r:kmsg_device_t tclass=chr_file
permissive=1
type=AVC msg=audit(1576535711.583:364): avc:  denied  { getattr }
for  pid=1497 comm="(imedated)"
path="/run/systemd/unit-root/proc/kmsg" dev="proc" ino=4026532027
scontext=system_u:system_r:init_t
tcontext=system_u:object_r:proc_kmsg_t tclass=file permissive=1
type=AVC msg=audit(1576535711.589:365): avc:  denied  { mounton }
for  pid=1497 comm="(imedated)" …
=> init: allow systemd to mount over /dev/kmsg and /proc/kmsg

policy/modules/system/mount.if
In order to be able to invoke `/usr/bin/mount`, `/usr/bin/fusermoun`t, etc. callers need to be able to search `/usr/bin`. Otherwise, such denials are recorded:
type=AVC msg=audit(1576534518.220:1320): avc:  denied  { search }
for  pid=24067 comm="cryfs" name="bin" dev="vda1" ino=524829
scontext=sysadm_u:sysadm_r:cryfs_t tcontext=system_u:object_r:bin_t
tclass=dir permissive=0
=> mount: allow callers of mount to search /usr/bin

policy/modules/roles/sysadm.te
Command `hostnamectl` communicates with `systemd_hostnamed_t` through DBUS:
type=USER_AVC msg=audit(1576535282.679:345): pid=285 uid=81
auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t
msg='avc:  denied  { send_msg } for msgtype=method_call
interface=org.freedesktop.DBus.Properties member=GetAll
dest=org.freedesktop.hostname1 spid=1449 tpid=1450
scontext=sysadm_u:sysadm_r:sysadm_t
tcontext=system_u:system_r:systemd_hostnamed_t tclass=dbus
permissive=1  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=?
terminal=?'
type=USER_AVC msg=audit(1576535282.683:347): pid=285 uid=81
auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t
msg='avc:  denied  { send_msg } for msgtype=method_return
dest=:1.269 spid=1450 tpid=1449 …
=> sysadm: allow using hostnamectl

policy/modules/kernel/corecommands.fc
(ifupdown2)[https://github.com/CumulusNetworks/ifupdown2] is an alternative of `ifupdown` written in python.
This means that the `ifup` and friends are symlinks to the actual entry point (`/usr/share/ifupdown2/__main__.py`).
Currently the entry point has the label `lib_t`, when it should be `bin_t`
=> fix ifupdown2 executable mislabeled as lib_t

policy/modules/kernel/filesystem.fc, policy/modules/kernel/filesystem.te
/sys/fs/bpf is still unlabeled, which is problematic for a confined system.
**TODO:**
=> added bpf_t filesystem label

policy/modules/admin/sudo.if, policy/modules/system/selinuxutil.if
Expected behavior:
```bash
staff_u:staff_r:staff_t
$ id -Z
staff_u:sysadm_r:sysadm_t
```
Instead `sudo` fails to read the default context for `sysadm_r`
The change in `sudo.if` should be syntactic sugar.
=> fix: sudo can't determine default type for sysadm_r

policy/modules/services/virt.te
When using libvirt to manage virtual machines, `libvirt_leaseshelper` wants to:
* read `/etc/libnl/classid`
* list the content of `/sys/devices/system/node/` in order to read files such as `/sys/devices/system/node/node0/meminfo`
* use `getsched`
=> virt: allow more accesses to libvirt_leaseshelper

policy/modules/system/systemd.te
Since systemd 244, systemd can parse EFI variable `SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67` like `/proc/cmdline` in order to find options. systemd's `NEWS` file [1] states:
systemd will also read configuration options from the EFI variable
SystemdOptions. This may be used to configure systemd behaviour when
modifying the kernel command line is inconvenient, but configuration
on disk is read too late, for example for the options related to
cgroup hierarchy setup. 'bootctl systemd-efi-options' may be used to
set the EFI variable.
In practice, all callers of `log_parse_environment()` read this EFI variable, because:
* `log_parse_environment()` is a macro which is expanded to  `log_parse_environment_realm(LOG_REALM)` [2].
* `log_parse_environment_realm()` calls …
=> systemd: allow reading options from EFI variable SystemdOptions

policy/modules/admin/netutils.fc, policy/modules/admin/netutils.te
`mtr` executes `mtr-packet` to do the actuall testing and communicates with it over a fifo.
=> netutils: allow mtr to communicate with mtr-packet

Vagrantfile
Since commit 210b64f10a44 ("Remove shell automatic domain transitions to unconfined_t from various pam login programs"), setting `ssh_sysadm_login` is mandatory in order to allow `vagrant` user to use SSH while using `unconfined_u` or `sysadm_u`.
=> Vagrantfile: allow unconfined and sysadm SSH login

support/vagrant-vm.cil
When provisioning a Debian test virtual machine with VirtualBox (using the main `Vagrantfile`), `vagrant` runs commands `dhclient` and `ip` from a ssh session because of this directive:
debian.vm.network "private_network", type: "dhcp"
This triggers:
type=AVC msg=audit(1578749426.820:68): avc:  denied  { write } for
pid=541 comm="dhclient" path="pipe:[14006]" dev="pipefs" ino=14006
scontext=unconfined_u:unconfined_r:dhcpc_t
tcontext=system_u:system_r:sshd_t tclass=fifo_file permissive=1
type=PROCTITLE msg=audit(1578749426.820:68):
proctitle=2F7362696E2F6468636C69656E74002D34002D76002D69002D72002D
7066002F72756E2F6468636C69656E742E657468312E706964002D6C66002F7661
722F6C69622F646863702F6468636C69656E742E657468312E6C6561736573002D
49002D6466002F7661722F6C69622F646863702F6468636C69656E74362E65 …
=> Vagrant: allow VirtualBox provisionning to use dhclient and ip

policy/modules/system/unconfined.te
When an unconfined user runs wine, there is an issue because `wine_domtrans()` causes a transition to `unconfined_u:unconfined_r:wine_t` without `unconfined_r` being associated with `wine_t`:
type=SELINUX_ERR msg=audit(1579963774.148:1047):
op=security_compute_sid
invalid_context="unconfined_u:unconfined_r:wine_t"
scontext=unconfined_u:unconfined_r:wine_t
tcontext=system_u:object_r:wine_exec_t tclass=process
This is fixed with `roleattribute unconfined_r wine_roles;`, which is provided by interface `wine_run()`.
=> Associate role unconfined_r to wine_t

policy/modules/system/logging.fc
Looking at all audit versions in gentoo (2.8.5 to 2.6.4) every single one of them has `var/log/audit` as a directory and not as a file.
Tested on gentoo.
=> Remove obsolete gentoo specific rule

policy/modules/admin/usermanage.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
On a Debian 10 test virtual machine, when installing packages adds a group, the following AVC occurs:
type=USER_AVC msg=audit(1578863991.588:575): pid=381 uid=104
auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t
msg='avc:  denied  { send_msg } for msgtype=method_call
interface=org.freedesktop.systemd1.Manager
member=LookupDynamicUserByName dest=org.freedesktop.systemd1
spid=13759 tpid=1 scontext=unconfined_u:unconfined_r:groupadd_t
tcontext=system_u:system_r:init_t tclass=dbus permissive=1
exe="/usr/bin/dbus-daemon" sauid=104 hostname=? addr=? terminal=?'
Allow `groupadd` to call DBUS method `LookupDynamicUserByName()`.
=> usermanage: add groupadd to lookup dynamic users from systemd

policy/modules/system/userdomain.if
Allow userdomain to read and write the wireless devices (for
example for querying their state, enabling and/or disabling
them using userspace tools such as "rfkill" from util-linux):
this is tunable policy.
See also:
https://wireless.wiki.kernel.org/en/users/documentation/rfkill
Make the same access tunable throughout the rest of the policy
as it is generally controlled directly and interactively by
the user.
--
policy/modules/admin/blueman.te           |    5 ++++-
policy/modules/apps/wm.te                 |    5 ++++-
policy/modules/kernel/devices.te          |    9 +++++++++
policy/modules/services/bluetooth.te      |    5 ++++-
policy/modules/services/hostapd.te        |    5 ++++-
policy/modules/services/networkmanager.te |    5 ++++-
policy/modules/system/systemd.te          |    5 …
=> Allow user domains to read/write the wireless devices (e.g. rfkill)

policy/modules/kernel/storage.if, policy/modules/system/systemd.te
`systemd-logind` exposes several properties reload to the bootloader. One of them is `BootLoaderEntries` [1], which scans the disks using util-linux's blkid in order to find the ESP (EFI System Partition) [2][3].
This triggers the following logs in `audit.log` (where `/dev/sda1` is the ESP, mounted on `/boot`):
type=AVC msg=audit(1577692922.834:310): avc:  denied  { getattr }
for  pid=690 comm="systemd-logind" name="/" dev="sda1" ino=1
scontext=system_u:system_r:systemd_logind_t
tcontext=system_u:object_r:dosfs_t tclass=filesystem permissive=1
type=AVC msg=audit(1577692922.841:311): avc:  denied  { search } for
pid=690 comm="systemd-logind" name="/" dev="sda1" ino=1
scontext=system_u:system_r:systemd_logind_t
tcontext=system_u:object_r:dosfs_t tclass=dir permissive=1
type=AVC …
=> systemd-logind: allow using BootLoaderEntries DBUS property

policy/flask/access_vectors, policy/flask/security_classes
=> Add perf_event access vectors.

policy/modules/services/wireguard.te, policy/modules/system/systemd.te
Signed-off-by: Daniel Burgener <dburgener@tresys.com>
=> Remove unneeded semicolons after interface and macro calls

policy/modules/apps/pulseaudio.te, policy/modules/kernel/devices.if
Modifications required for the new SELinux **watch** permission.
=> Add a new device interface and apps permissions to watch device directories

policy/modules/system/mount.fc
libfuse 3.0 renamed `fusermount` to `fusermount3` in order to allow both libfuse 2 and libfuse 3 to be installed together: https://github.com/libfuse/libfuse/commit/695e45a4de50a9164766a7d73656b1afc9244a56
=> mount: label fusermount3 like fusermount

policy/modules/system/init.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.te
Implementing a policy for systemd-fstab-generator instead of allowing `initrc_t` to write to `init_runtime_t`.
Tested on:
Comments are appreciated.
=> policy for systemd-fstab-generator

policy/modules/apps/loadkeys.te, policy/modules/services/consolesetup.fc, policy/modules/services/consolesetup.if, policy/modules/services/consolesetup.te, policy/modules/system/udev.fc, policy/modules/system/udev.te
This is a helper script on debian to setup the console font / keymap.
=> Add policy for console-setup on debian

policy/modules/services/ntp.te
This is required after linux 5.4
=> ntp: watch systemd networkd runtime dirs

policy/modules/services/entropyd.fc, policy/modules/services/entropyd.te
Also allow jitterentropy (or rather some libs) to read
/proc/crypto/fips_enabled.
=> Consider jitterentropy to belong to entropyd family

policy/modules/system/systemd.fc, policy/modules/system/systemd.te
A policy for `systemd-user-runtime-dir`, this is to avoid adding:
```
userdom_search_user_runtime_root(systemd_user_runtime_dir_t)
userdom_user_runtime_root_filetrans_user_runtime(systemd_user_runtime_dir_t, dir)
userdom_manage_user_runtime_dirs(systemd_user_runtime_dir_t)
userdom_mounton_user_runtime_dirs(systemd_user_runtime_dir_t)
userdom_relabelto_user_runtime_dirs(systemd_user_runtime_dir_t)
```
to `initrc_t`
=> systemd-user-runtime-dir: add policy

policy/modules/roles/auditadm.te, policy/modules/roles/secadm.te, policy/modules/roles/staff.te, policy/modules/roles/sysadm.if, policy/modules/roles/sysadm.te
Allows `staff_r:staff_t`, `auditadm_r:auditadm_t`, secadm_r:secadm_t` access to inherited pipes (sudo with pipes).
e.g:
```bash
staff_u:staff_r:staff_t:s0
1234
```
=> sysadm: allow usage of inherited pipes from role changing domains

policy/modules/kernel/terminal.fc
This exception goes back 14 years to commit 85c20af3c10867e3d62afa4326ea3d0f5dec4e41 and 11a0508edeaa33538abdb74bb5ba033742a77a07.
The tts exception is covered by a distro agnostic rule further up, and the udev rule doesn't even work (it's supposed to be /lib/udev/ not /usr/lib/udev on gentoo) so I seriously doubt anyone is going to miss them.
=> Remove old exception

policy/modules/kernel/devices.if
/dev/ipmi is labeled, but no interfaces exist to grant access to the device.
Adding interface for read/write access, I'm not sure of read-only access is usefull. ipmitool seems to only read and write
I'm seeing the following denials.
type=AVC msg=audit(1581618155.319:786): avc:  denied  { read write } for pid=4498 comm="ipmitool" name="ipmi0" dev="devtmpfs" ino=10460 scontext=system_u:system_r:ipmi_t:s0 tcontext=system_u:object_r:ipmi_device_t:s0 tclass=chr_file permissive=1
type=AVC msg=audit(1581618155.319:786): avc:  denied  { open } for pid=4498 comm="ipmitool" path="/dev/ipmi0" dev="devtmpfs" ino=10460 scontext=system_u:system_r:ipmi_t:s0 tcontext=system_u:object_r:ipmi_device_t:s0 tclass=chr_file permissive=1
type=AVC msg=audit(1581618155.320:787): avc:  denied  { ioctl } for …
=> Add interface to read/write /dev/ipmi

policy/modules/system/logging.te
Denial:
```
----
time->Sun Mar 15 13:57:17 2020
type=AVC msg=audit(1584280637.279:10537): avc:  denied  { unlink } for  pid=62717 comm="systemd-journal" name="io.systemd.journal" dev="tmpfs" ino=12399 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:syslogd_runtime_t:s0 tclass=sock_file permissive=0
```
Required by `systemd-journald` when restarting the service.
=> logging: allow syslogd to remove stale socket file

policy/modules/admin/usbguard.fc, policy/modules/admin/usbguard.if, policy/modules/admin/usbguard.te, policy/modules/system/userdomain.if
Usbguard enforces the USB device authorization policy for all USB
devices. Users can be authorized to manage rules and make device
authorization decisions using a command line tool.
Add rules for usbguard. Optionally, allow authorized users to control
the daemon, which requires usbguard-daemon to be able modify its rules
in /etc/usbguard.
=> Add usbguard

policy/modules/kernel/devices.if, policy/modules/system/userdomain.if
This patch improves a previous commit by restricting down
the permissions to write the wireless device in order to
prevent a possible Denial of Service (DoS) attack from an
unprivileged process bringing down the wireless interfaces.
Only administrative users can now enable/disable the wireless
interfaces, while normal users can only read their status.
---
policy/modules/kernel/devices.if    |   18 ++++++++++++++++++
policy/modules/system/userdomain.if |    3 ++-
2 files changed, 20 insertions(+), 1 deletion(-)
=> Restrict down wireless device permissions to prevent DoS attack

policy/modules/system/systemd.te
When getting dumps from a crash in a mount namespace, systemd wants to run stat on the root in that namespace
Signed-off-by: Daniel Burgener <Daniel.Burgener@microsoft.com>
=> Allow systemd-coredump to stat mountpoints.

Rules.modular, Rules.monolithic
Allow class sets , e.g. defined in policy/support/obj_perm_sets.spt, to
be used in default_* statements in the file policy/context_defaults
=> Rules: allow the usage of class sets in context_defaults

policy/modules/system/systemd.te
systemd-user-runtime-dir reads /proc/sys/kernel/osrelease and the
selinux config
Missed these in #183 or they where required by a recent upgrade of my server from debian stable to unstable.
=> systemd-user-runtime-dir: add missed required permissions

policy/modules/services/dbus.te
D-Bus services wanting to pass file descriptors for
tun/tap devices need to read/write privileges to /dev/tun.
Without this privilege the following denial will happen:
type=AVC msg=audit(1582227542.557:3045): avc:  denied  { read write } for  pid=1741 comm="dbus-daemon" path="/dev/net/tun" dev="devtmpfs" ino=486 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:tun_tap_device_t:s0 tclass=chr_file permissive=0
This is needed by OpenVPN 3 Linux, where an unprivileged
process (openvpn3-service-client) requests a tun device
from a privileged service (openvpn3-service-netcfg) over
the D-Bus system bus.
GitHub-Issue: #190
Signed-off-by: David Sommerseth <davids@openvpn.net>
=> dbus: Add tunable - dbus_can_pass_tuntap_fd

policy/modules/system/init.te
These denials only ocure if the `unconfined` module is removed during boot with `systemd` but they're required for correct functioning.
=> allow init_t to use the linux keyring

policy/modules/system/init.te, policy/modules/system/modutils.te
kmod_t should have been an init_system_daemon in the first place.
=> modutils: allow init to execute kmod with nnp

policy/modules/apps/mozilla.te
See https://wiki.mozilla.org/Security/Sandbox/Specifics#Linux for reference.
=> mozilla: allow firefox to use user namespaces for sandboxing

Makefile
Use a separate directory for files generated my 'make conf', so the clean targets from Rules.* do not remove them.
=> Makefile: generate temporary documentation files in separate directory 

Vagrantfile
When testing issues in older versions of refpolicy (for example when git-bisecting a regression), the newer policy modules are kept in `/usr/share/selinux/refpolicy/` and trigger errors when they fail to be loaded by `semodule -s refpolicy -i /usr/share/selinux/refpolicy/*.pp`.
Avoid this situation by removed old modules from `/usr/share/selinux/refpolicy/` before running `make install`.
=> Vagrantfile: remove older installed modules before "make install"

policy/modules/services/dbus.te, policy/modules/services/tpm2.fc, policy/modules/services/tpm2.if, policy/modules/services/tpm2.te
The various /bin/tpm2_* binaries use dbus to communicate
with tpm2-abrmd and also can directly access /dev/tpmrm0.  This
seems like a way to help limit access to the TPM by running the
tpm_* binaries in their own domain.
I setup this domain because I have a process that needs to use
tpm2_hmac to encode something, but didn't want that domain to
have direct access to the TPM.  I did some basic testing to verify
that the other tpm2_* binaries have basically the same access needs.
But it wasn't through testing of all the tpm2_* binaries.
=> Setup domain for tpm2_* binaries

support/gennetfilter.py
Use raw string constants to avoid errors from python3.8:
```
NETPORT = re.compile("^network_port\(\s*\w+\s*(\s*,\s*\w+\s*,\s*\w+\s*,\s*\w+\s*)+\s*\)\s*(#|$)")
^
SyntaxError: invalid escape sequence \(
```
=> Python string fix

support/gennetfilter.py
Don't ignore port ranges. For example:
```
network_port(amanda, udp,10080-10082,s0, tcp,10080-10083,s0)
```
can be used to generate:
```
base -A selinux_new_input -p udp --dport 10080:10082 -j SECMARK --selctx system_u:object_r:amanda_server_packet_t:s0
base -A selinux_new_input -p tcp --dport 10080:10083 -j SECMARK --selctx system_u:object_r:amanda_server_packet_t:s0
base -A selinux_new_output -p udp --dport 10080:10082 -j SECMARK --selctx system_u:object_r:amanda_client_packet_t:s0
base -A selinux_new_output -p tcp --dport 10080:10083 -j SECMARK --selctx system_u:object_r:amanda_client_packet_t:s0
```
=> gennetfilter: handle port ranges

support/gennetfilter.py
Optionally generate Netfilter NFT tables. Sample output:
```
flush ruleset
table inet security {
secmark default_input_packet {
"system_u:object_r:server_packet_t:s0"
}
secmark default_output_packet {
"system_u:object_r:client_packet_t:s0"
}
secmark afs_bos_input {
"system_u:object_r:afs_bos_server_packet_t:s0"
}
secmark afs_bos_output {
"system_u:object_r:afs_bos_client_packet_t:s0"
}
...
chain INPUT {
type filter hook input priority 0; policy accept;
ct state new meta secmark set "default_input_packet"
ct state new udp dport 7007 meta secmark set "afs_bos_input"
...
ct state new ct secmark set meta secmark
ct state established,related meta secmark set ct secmark
}
chain FORWARD {
type filter hook forward priority 0; policy accept;
}
chain OUTPUT {
type filter hook output priority 0; …
```
=> gennetfilter: generate nft tables with --nft

policy/modules/system/systemd.te
On Debian 10, ``systemd --user`` runs some generators in `/usr/lib/systemd/user-environment-generators` when a user session starts. Here is what is logged in audit.log for a `sysadm` user.
type=AVC msg=audit(1586962888.516:65): avc:  denied  { getattr } for
pid=309 comm="(sd-executor)"
path="/usr/lib/systemd/user-environment-generators/90gpg-agent"
dev="vda1" ino=662897 scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:systemd_generator_exec_t tclass=file
permissive=1
type=AVC msg=audit(1586962888.516:66): avc:  denied  { map } for
pid=310 comm="30-systemd-envi"
path="/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator"
dev="vda1" ino=655822 scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:systemd_generator_exec_t …
=> systemd: make systemd --user run generators without transition

policy/modules/kernel/devices.fc, policy/modules/kernel/devices.if, policy/modules/kernel/devices.te
`sysdig` is a tool that enables introspecting the system, debugging it, etc. It uses a driver that creates `/dev/sysdig0`. Define a specific label in order to be able to allow using it.
=> devices: label /dev/sysdig0

policy/modules/system/systemd.te
When ``systemd --user`` runs helper programs in order to generate user environment variables, it reads memfd temporary files, which are labeled `tmpfs_t`:
type=AVC msg=audit(1569787627.183:487): avc:  denied  { getattr }
for  pid=19182 comm="(sd-executor)"
path=2F6D656D66643A33302D73797374656D642D656E7669726F6E6D656E742D642D67656E657261746F72202864656C6574656429
dev="tmpfs" ino=50062 scontext=sysadm_u:sysadm_r:sysadm_systemd_t
tcontext=sysadm_u:object_r:tmpfs_t tclass=file permissive=1
type=SYSCALL msg=audit(1569787627.183:487): arch=c000003e syscall=5
success=yes exit=0 a0=a a1=7ffd324679d0 a2=7ffd324679d0 a3=4 items=0
ppid=19180 pid=19182 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000
fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=28
comm="(sd-executor)" …
=> systemd: allow sd-executor to read memfd files

Rules.modular, Rules.monolithic
During normal m4 parsing, m4 outputs a blank line for each define() call.  This results in the first roughly 500 lines of the .tmp files for each module being largely blank lines.  Adding divert() calls to the m4 generation for generated_definitions redirects this output, so the beginning of the actual policy appears near the top of the .tmp files.
Signed-off-by: Daniel Burgener <Daniel.Burgener@microsoft.com>
=> Add divert to generated_definitions creation.

policy/modules/kernel/corenetwork.if.m4, policy/modules/kernel/corenetwork.te.in, policy/modules/kernel/corenetwork.te.m4, policy/modules/system/systemd.te
Allow systemd-networkd to send and receive ICMPv6 Router Solicitation
and Router Advertisement packets (in reality all unlabeled packets)
and DHCP client packets.
=> Allow systemd-networkd to handle ICMP and DHCP packets

policy/modules/apps/wm.fc, policy/modules/apps/wm.te
Add KWin to list of window managers and allow it to mmap wm_tmpfs_t
files to avoid a crash. Related audit event:
type=AVC msg=audit(04/24/2020 15:39:25.287:679) : avc:  denied  { map } for  pid=1309 comm=kwin_x11 path=/memfd:JSVMStack:/lib/x86_64-linux-gnu/libQt5Qml.so.5 (deleted) dev="tmpfs" ino=45261 scontext=user_u:user_r:user_wm_t:s0 tcontext=user_u:object_r:wm_tmpfs_t:s0 tclass=file permissive=0
=> wm: add KWin

policy/modules/services/ssh.fc, policy/modules/services/ssh.if
debian ships a wrapper script that moves the ssh-agent socket to
/run/user/$UID/openssh_agent
=> ssh: fix for debian wrapper script

policy/modules/system/systemd.if
This can be used to e.g. create temporary units under `systemd --user`
=> Allow users to use systemd run

.gitignore, Makefile, Rules.modular, Rules.monolithic
Build SECMARK rules for iptables and NFT, install them as
/etc/selinux/$NAME/contexts/netfilter_contexts{,.nft}.
=> Build and install Netfilter rules

policy/modules/admin/netutils.te
Let ping send and receive ICMP packets when Netfilter SECMARK packet
labeling is active.
=> netutils: allow ping to send and receive ICMP packets

policy/modules/services/stunnel.te
a require was fixed back in 2011, so using corenet_tcp_bind_stunnel_port
would be an option now, but stunnel_t already has
corenet_tcp_bind_all_ports, so this access is redundant.
=> Remove out of date "hack" from stunnel.  The underlying problem needing

policy/modules/kernel/domain.if, policy/modules/kernel/kernel.if
I have been working to support IMA/EVM on a system.  It
requires having keys added to the kernel keyring.  Keys
added with keyctl and evmctl.  I am creating keys in the
ima_key_t type.  Once the keys are created, many domains
then need search permission on the type of the key.  The
following changes are needed to get things to work.
Need to add keys to the kernel keyring (keyctl).
type=AVC msg=audit(1585420717.704:1868): avc:  denied  { write } for pid=8622 comm="keyctl" scontext=system_u:system_r:cleanup_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=key permissive=1
Allow all domains to search key
type=AVC msg=audit(1587936822.802:556): avc:  denied  { search } for  pid=5963 comm="kworker/u16:6" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:ima_key_t:s0 …
=> Interfaces needed to support IMA/EVM keys

Rules.modular, Rules.monolithic
Do not keep interfaces from previous builds.
Fixes: #235
=> Override old all_interfaces.conf.tmp file

policy/modules/kernel/filesystem.if, policy/modules/system/sysnetwork.fc, policy/modules/system/sysnetwork.te, policy/modules/system/userdomain.if
When using network namespaces with `ip netns`, command `ip` creates files in `/run/netns` that are mountpoints for `nsfs`. For example:
$ ip netns add VPN
$ ls -Z /run/netns/VPN
system_u:object_r:nsfs_t /run/netns/VPN
$ findmnt /run/netns/VPN
TARGET         SOURCE                 FSTYPE OPTIONS
/run/netns/VPN nsfs[net:[4026532371]] nsfs   rw
/run/netns/VPN nsfs[net:[4026532371]] nsfs   rw
From a shell CLI, it is possible to retrieve the name of the current network namespace:
$ ip netns exec VPN bash
$ ip netns identify $$
VPN
This requires reading `/proc/$PID/ns/net`, which is labelled as a user domain. Allow this access using `userdom_read_all_users_state()`.
=> Allow using "ip netns"

policy/modules/services/ntp.te
Adds missing watch permissions required for correct functionality after linux 5.4
=> ntpd: fixes for systemd-timesyncd after linux 5.4

policy/flask/access_vectors, policy/flask/security_classes
This was introduced in the merge b1dba2473114588be3df916bf629a61bdcc83737 in the linux kernel.
=> define lockdown class and access

policy/modules/system/application.te
For example ansible uses `ssh localhost sudo id` to become root.
This doesn't appear to be necessary in redhat due to https://src.fedoraproject.org/rpms/openssh/blob/master/f/openssh-6.6p1-privsep-selinux.patch
=> application: applications can be executed from ssh without pty

doc/example.te, policy/modules/admin/portage.if, policy/modules/admin/portage.te, policy/modules/apps/chromium.fc, policy/modules/apps/chromium.te, policy/modules/kernel/files.fc, policy/modules/services/consolesetup.if, policy/modules/services/samba.if, policy/modules/services/tpm2.if, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/libraries.fc, policy/modules/system/logging.fc, policy/modules/system/miscfiles.fc, policy/modules/system/systemd.if, policy/modules/system/unconfined.if
* samba: fix wrong interface context smbd_runtime_t
* chromium: drop dead conditional block
* example: use module name matching file name
* consolesetup: drop unused requires
* unconfined: clarify unconfined_t stub usage in unconfined_domain_noaudit()
* portage: drop bizarre conditional TODO blocks
* init/systemd: move systemd_manage_all_units to init_manage_all_units
* tpm2: small fixes
* xserver: declare all callers of template xserver_common_x_domain_template as template
* files/logging: move var_run_t filecontext to defining module
* files/miscfiles: move usr_t filecontext to defining module
* chromium/libraries: move lib_t filecontext to defining module
=> Misc cleanup

policy/support/misc_macros.spt, policy/support/misc_patterns.spt
The file misc_macros.spt is due heavy usage of the m4 language
hard to parse for third party tools.
Move the macro can_exec() to misc_patterns.spt, which contains
only interface like define blocks.
=> can_exec(): move from misc_macros to misc_patterns

Makefile
With the removal of fc_sort there are no more .c files in the repository.
=> Makefile: remove obsolete .SUFFIXES

policy/modules/services/apache.if
The content types are named httpd_user_rw_content_t and
httpd_user_ra_content_t not httpd_user_content_rw_t and
httpd_user_content_ra_t in apache_content_template()
=> apache: use correct content types in apache_manage_all_user_content()

policy/modules/kernel/domain.te, policy/modules/system/setrans.if
This partially reverts commit 65da822c1b5c70bd1ff7eca645f5f9fd74fa949e
Connecting to setransd is still very much necessary for any domain that
uses SELinux labels in any way.
=> setrans: allow label translation for all domains.

policy/modules/system/init.te, policy/modules/system/logging.if
A number of changes necessary to allow debian (and probably other systemd based installations) to boot without the unconfined module.
=> Confined debian fixes

policy/modules/kernel/devices.if, policy/modules/kernel/devices.te, policy/modules/kernel/files.te, policy/modules/kernel/filesystem.te, policy/modules/kernel/kernel.te, policy/modules/kernel/terminal.if, policy/modules/services/ntp.te, policy/modules/system/init.te, policy/modules/system/logging.if, policy/modules/system/systemd.te
Without the `unconfined` module present, systemd will fail to boot due to various sandboxing options, e.g. ProtectKernelModules=yes (in https://github.com/systemd/systemd/blob/master/units/systemd-logind.service.in#L43).
A few other things also prevent a successful boot and have been fixed.
These changes should allow a minimal debian unstable install to boot successfully without the `unconfined` module.
=> Confined debian fixes2

policy/modules/admin/dpkg.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
Running a system without the unconfined module, this is another service that needs additional privileges (modifying /etc/shadow and friends).
This is blocked by #246 but open for comments.
=> systemd-sysusers: add policy

policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
If these processes are compromised they can write units to do malicious
actions, so trying to tightly protect the resources for each generator
is not effective.
Made the fstools_exec() optional, although it is unlikely that a system
would not have the module.
Only aliases for removed types in previous releases are added.  The
systemd_unit_generator() interface and systemd_generator_type attribute
were not released and are dropped without deprecation.
Signed-off-by: Chris PeBenito <pebenito@ieee.org>
=> systemd: Merge generator domains.

policy/modules/services/tpm2.if
Add interfaces tpm2_use_fds, tpm2_dontaudit_use_fds, and tpm2_read_pipes
Signed-off-by: David Sugar <dsugar@tresys.com>
=> Interfaces for tpm2

Rules.modular, Rules.monolithic, support/comment_move_decl.sed
This will allow user definitions in modules to work for monolithic policies
and base module.
=> Move user definitions to the right place during compilation.

policy/modules/admin/apt.fc, policy/modules/admin/rpm.fc
The daemon has now moved from /usr/lib/packagekit/packagekitd to
/usr/libexec/packagekitd
Signed-off-by: Laurent Bigonville <bigon@bigon.be>
=> Label /usr/libexec/packagekitd as apt_exec_t on debian

Makefile, policy/modules/system/init.if
Revise to use ifelse to have a clear set of criteria for enabling the
various options.  Additionally, if no options are enabled, run_init
permissions are provided as a default.
=> init: Revise init_startstop_service() build option blocks.

.travis.yml
root: duplicate key: matrix
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs
=> travis: resolve Linter tags

policy/modules/services/postfixpolicyd.te
The rule uses the permission manage_file_perms on the classes file and
sock_file.  This won't result in a change in the actual policy
generated, but if the definitions of macros are changed going forward,
the mismatches could cause issues.
Found by SELint
=> postfixpolicyd: split multi-class rule

policy/modules/services/acpi.te
acpi.te: Allow acpid_t to shutdown the system - this is required to handle shutdown calls from libvirt. Fixes #298.
=> acpi.te: Allow acpid_t to shutdown the system

policy/modules/system/modutils.te
Adding map permission back, seeing the following denial:
localhost kernel: type=1400 audit(1598497795.109:57): avc:  denied  { map } for  pid=1054 comm="modprobe" path="/usr/lib/modules/3.10.0-1127.19.1.el7.x86_64/modules.dep.bin" dev="dm-0" ino=23711 scontext=system_u:system_r:kmod_t:s0 tcontext=system_u:object_r:modules_dep_t:s0 tclass=file permissive=0
Signed-off-by: Dave Sugar <dsugar100@gmail.com>
=> Looks like this got dropped in pull request #294

policy/modules/system/userdomain.if
...so usbguard may be excluded.
Thanks to Dominick Grift for helping me pin-point this.
Signed-off-by: Jonathan Davies <jpds@protonmail.com>
=> userdomain.if: Marked usbguard user modify tunable as optional

policy/modules/admin/rpm.te, policy/modules/kernel/selinux.if, policy/modules/system/init.te, policy/modules/system/systemd.te
systemd v247 will access the SELinux status page.
see https://github.com/systemd/systemd/pull/16821
=> init: allow systemd to map the SELinux status page

policy/modules/system/sysnetwork.te
The dhcpcd needs to create socket file under /run/dhcpcd directory.
Fixes:
AVC avc:  denied  { create } for  pid=331 comm="dhcpcd" name="eth0.sock"
scontext=system_u:system_r:dhcpc_t:s0-s15:c0.c1023
tcontext=system_u:object_r:dhcpc_runtime_t:s0 tclass=sock_file
permissive=0
AVC avc:  denied  { setattr } for  pid=331 comm="dhcpcd"
name="eth0.sock" dev="tmpfs" ino=19153
scontext=system_u:system_r:dhcpc_t:s0-s15:c0.c1023
tcontext=system_u:object_r:dhcpc_runtime_t:s0 tclass=sock_file
permissive=0
AVC avc:  denied  { sendto } for  pid=331 comm="dhcpcd"
scontext=system_u:system_r:dhcpc_t:s0-s15:c0.c1023
tcontext=system_u:system_r:dhcpc_t:s0-s15:c0.c1023
tclass=unix_dgram_socket permissive=0
=> sysnet: allow dhcpcd to create socket file

policy/modules/kernel/corecommands.fc, policy/modules/services/dbus.if, policy/modules/system/locallogin.te, policy/modules/system/logging.te, policy/modules/system/sysnetwork.if, policy/modules/system/systemd.te, policy/modules/system/udev.te
Hello,
While working on adding SELinux support in [Buildroot](https://buildroot.org) (a tool widely used to generate small or embedded Linux systems), I came across multiple denied actions when using the refpolicy. I made tests using a small image, with systemd as the init and was not able to boot properly and to go up to the login prompt. As a result, I patched the refpolicy and (most of) those changes ended up in this PR.
The reason I made this PR is I'd like more systems to be supported by the refpolicy, and this PR will at least help to start the discussion on how to do that properly. Many of the changes that were required for the Buildroot generated image seem to also be part of the [changes](https://git.yoctoproject.org/cgit/cgit.cgi/meta-selinux/tree/recipes-security/refpolicy/refpo …
=> Set of fixes made while using a minimal Buildroot generated system

policy/modules/services/snmp.te
Oct  1 16:11:49 localhost audispd: node=virtual type=AVC msg=audit(1601568708.950:2198): avc:  denied  { getattr } for  pid=4114 comm="snmpd" path="/usr/share/hwdata/pci.ids" dev="dm-0" ino=76435 scontext=system_u:system_r:snmpd_t:s0 tcontext=system_u:object_r:hwdata_t:s0 tclass=file permissive=1
Oct  1 16:11:49 localhost audispd: node=virtual type=AVC msg=audit(1601568708.950:2197): avc:  denied  { read } for  pid=4114 comm="snmpd" name="pci.ids" dev="dm-0" ino=76435 scontext=system_u:system_r:snmpd_t:s0 tcontext=system_u:object_r:hwdata_t:s0 tclass=file permissive=1
Oct  1 16:11:49 localhost audispd: node=virtual type=AVC msg=audit(1601568708.950:2197): avc:  denied  { open } for  pid=4114 comm="snmpd" path="/usr/share/hwdata/pci.ids" dev="dm-0" ino=76435 …
=> Allow snmpd to read hwdata

policy/modules/services/ntp.te, policy/modules/system/systemd.te
Hello,
This PR includes more fixes needed to get a working systemd image generated with [Buildroot](https://buildroot.org/). All the fixes are related to systemd, except the last patch. Those changes should also benefit to other build systems such as OE/Yocto.
Thanks!
Antoine
=> More fixes for systemd systems generated with Buildroot

policy/modules/kernel/devices.if, policy/modules/kernel/filesystem.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.te
systemd-pstore is a service to archive contents of pstore.
Signed-off-by: Deepak Rawat <drawat.floss@gmail.com>
=> Add selinux-policy for systemd-pstore service

policy/modules/services/corosync.fc, policy/modules/services/corosync.if, policy/modules/services/corosync.te, policy/modules/services/pacemaker.fc, policy/modules/services/pacemaker.te
Sorry for so many related patches.  But I think it will be easier to review and comment on and to see why some of things are being proposed.
I'm happy to squash into a single commit once everything is ready to be merged.
I think the controversial pieces are going to be the proposed interface init_filetrans_unit which is to dynamically create directories/files in systemd_unit_t directories with a filetrans to a new type (intended for /run/systemd/system/ ) so the domain creating unit files (pacemaker in this case) don't need to have full read/write access to all systemd_unit_t files.
The other one is the new interface corosync_mmap_rw_tmpfs which is to map/read/write corosync tmpfs file.  I thought it was better than changing the existing corosync_rw_tmpfs interface.  Though thinking about …
=> Corosync & pacemaker changes to work in enforcing

policy/flask/access_vectors
Updated location of capability definitions to point to current location within kernel source code.
CAP_BPF and CAP_PERFMON mainlined in: cb8e59cc87201af93dfbb6c3dccc8fcad72a09c2, original commit: a17b53c4a4b55ec322c132b6670743612229ee9c
CAP_CHECKPOINT_RESTORE mainlined in: 74858abbb1032222f922487fd1a24513bbed80f9, original commit: 124ea650d3072b005457faed69909221c2905a1f
The missing capabilities were noticed on archlinux with kernel 5.8.14-arch1-1.
=> access_vectors: Add new capabilities to cap2

policy/modules/system/lvm.te
Add LVM module permissions needed to open cryptsetup devices.
---
policy/modules/system/lvm.te |    2 ++
1 file changed, 2 insertions(+)
=> Add LVM module permissions needed to open cryptsetup devices.

policy/modules/services/dbus.te
In portable profiles, systemd bind mounts the system bus into process
namespaces
Signed-off-by: Daniel Burgener <Daniel.Burgener@microsoft.com>
=> Allow init to mount over the system bus

policy/modules/system/init.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
People are stumbling upon a tool provided by systemd that does not work on a SELinux enabled system due to a missing policy for the tool (e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1868949).  I am using the proposed rules for [3 years now](https://dmitry.khlebnikov.net/2017/01/13/nginx-a-backend-with-a-dynamic-ip-eg-aws-elb/), so decided to contribute back to a wider community :).
=> added policy for systemd-socket-proxyd

policy/modules/kernel/kernel.te, policy/modules/system/modutils.te
I was seeing the following errors from systemd-modules-load without this search permission.
Dec  7 14:36:19 systemd-modules-load: Failed to insert 'nf_conntrack_ftp': Required key not available
Dec  7 14:36:19 kernel: Request for unknown module key 'Red Hat Enterprise Linux kernel signing key: 3ffb026dadef6e0bc404752a7e7c29095a68eab7' err -13
Dec  7 14:36:19 systemd: systemd-modules-load.service: main process exited, code=exited, status=1/FAILURE
Dec  7 14:36:19 audispd: node=loacalhost type=PROCTITLE msg=audit(1607351779.441:3259): proctitle="/usr/lib/systemd/systemd-modules-load"
Dec  7 14:36:19 systemd: Failed to start Load Kernel Modules.
This is the denial:
Dec  7 15:56:52 audispd: node=localhost type=AVC msg=audit(1607356612.877:3815): avc:  denied { search } for  pid=11715 …
=> Allow systemd-modules-load to search kernel keys

policy/modules/kernel/selinux.if
Allow the caller to read the state of selinuxfs booleans.
Signed-off-by: Peter Morrow <pemorrow@linux.microsoft.com>
=> selinux: add selinux_get_all_booleans() interface

policy/modules/system/authlogin.te, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
This only addresses the scenario where `userdb` is disabeled, e.g. debian.
Partially Fixes #246 
`init_unix_stream_socket_connectto` is used because `init_stream_connect` was already taken and grants additional (unwanted) access that is not necessary.
=> Systemd userdb

policy/modules/kernel/kernel.te, policy/modules/services/xserver.te
This is reported in a new SELint check in soon to be released selint version 1.2.0
Signed-off-by: Daniel Burgener <dburgener@linux.microsoft.com>
=> Use self keyword when an AV rule source type matches destination

policy/modules/services/corosync.fc, policy/modules/services/corosync.if, policy/modules/services/pacemaker.fc, policy/modules/services/pacemaker.te
create corosync_read_state interface, used by pcs_snmp_agent policy
update file context list for corosync to include corosync-cmapctl, this allows pcs_snmp_agent to domtrans when calling it
denial for execmem
type=AVC msg=audit(1610036202.427:3772): avc:  denied  { execmem } for  pid=10875 comm="ruby" scontext=system_u:system_r:pcs_snmp_agent_t:s0 tcontext=system_u:system_r:pcs_snmp_agent_t:s0 tclass=process permissive=1
create contexts for pcs_snmp_agent_t and allow it some self permissions
allow pcs_snmp_agent_t to create allows and transision context of those logs
allow pcs_snmp_agent_t to read kernel sysctls
allow pcs_snmp_agent_t to exec bin_t
allow pcs_snmp_agent_t to access pacemaker's cluster information base (cib)
type=AVC msg=audit(1610037438.918:4524): avc:  denied  { read …
=> add policy for pcs_snmp_agent

policy/modules/kernel/devices.if, policy/modules/services/virt.te
A feature of qemu allows users to pass through input devices directly into the virtual guest. When this is enabled, a user can press both CTRL keys at the same time, at which point the input devices specified on the qemu commandline have their input events sent directly to the guest. This is done via the IOCTL permission on the specified devices. This merge adds a boolean to allow this feature to be enabled.
=> Add tunable to allow evdev passthrough with qemu

policy/modules/services/fail2ban.te
fail2ban can be configured to use the systemd journal, where the mmap permission is needed on the journal files.
=> fail2ban: allow reading systemd journal

policy/modules/services/stunnel.te
stunnel can be configured to log to its own log files. This commit adds the type and rules needed for this functionality.
=> stunnel: add log type and rules

policy/modules/services/apache.if
This is needed by some webservers such as nginx when autoindexing is
enabled.
=> apache: add interface for list dir perms on httpd content

policy/modules/services/spamassassin.fc, policy/modules/services/spamassassin.te
Additional rules are required to enable rspamd support. This commit adds
file contexts for rspamd's files and adds a tunable that enables the
additional rules needed for rspamd to function.
=> spamassassin: add rspamd support and tunable

policy/modules/services/pacemaker.te
Jan 27 18:16:51 audispd: node=virtual type=AVC msg=audit(1611771411.553:9337): avc:  denied  { search } for  pid=13880 comm="cibadmin" name="qb-6671-13880-13-bRhDEX" dev="tmpfs" ino=88809 scontext=system_u:system_r:pcs_snmp_agent_t:s0 tcontext=system_u:object_r:pacemaker_tmpfs_t:s0 tclass=dir permissive=0
Jan 27 19:53:46 audispd: node=virtual type=AVC msg=audit(1611777226.144:25975): avc:  denied  { getattr } for  pid=29489 comm="systemctl" name="/" dev="tmpfs" ino=14072 scontext=system_u:system_r:pcs_snmp_agent_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
=> pcs_snmpd_agent_t fix denials to allow it to read needed queues

config/file_contexts.subs_dist
Units can be created and configured in `/etc/systemd/system`. This commit labels these files appropriately as `systemd_unit_t`.
=> init: label systemd units in /etc

policy/modules/apps/gpg.te, policy/modules/system/userdomain.if
These two cases I see when building on a system without graphical interface.
Move userdom_xdg_user_template into optional block
gpg module doesn't require a graphical front end, move xdg_read_data_files into optional block
=> Work with xdg module disabled

policy/modules/services/certbot.fc, policy/modules/services/certbot.te
acme.sh is an alternative to cerbot written in pure Unix shell.
=> certbot: add support for acme.sh

policy/modules/apps/screen.fc, policy/modules/apps/screen.te
tmux attempts to read `~/.config/tmux/tmux.conf` and displays a permission denied error without this addition.
=> Added support for tmux xdg config path

.gitignore, Rules.monolithic, build.conf, support/genhomedircon.py
Generate substituted file contexts for templated paths containing `%{USERNAME}` or `%{USERID}`, like semodules's genhomedircon.
Example:
```
/run/user/%{USERID}  -d  gen_context(system_u:object_r:user_runtime_t,s0)
```
into
```
/run/user/[0-9]+  -d  gen_context(user_u:object_r:user_runtime_t,s0)
/run/user/0  -d  gen_context(root:object_r:user_runtime_t,s0)
```
=> Improve monolithic policy build support

policy/modules/system/lvm.te
cryptsetup uses tmpfs when performing some operations on encrypted
volumes such as changing keys.
=> lvm: add lvm_tmpfs_t type and rules

policy/modules/kernel/kernel.if, policy/modules/services/dovecot.te, policy/modules/services/mta.if, policy/modules/services/ssh.te, policy/modules/system/authlogin.te, policy/modules/system/selinuxutil.te
Allow dovecot to watch the mail spool, and add various dontaudit rules
for several other domains.
=> Various fixes

policy/modules/services/dovecot.if, policy/modules/services/postfix.te
postfix_pipe_t requires reading dovecot configuration and connecting to
dovecot stream sockets if configured to use dovecot for local mail
delivery.
=> dovecot, postfix: add missing accesses

policy/modules/kernel/files.if, policy/modules/kernel/filesystem.if, policy/modules/kernel/kernel.if, policy/modules/services/dbus.te, policy/modules/system/authlogin.te, policy/modules/system/init.te, policy/modules/system/logging.if, policy/modules/system/logging.te, policy/modules/system/lvm.te, policy/modules/system/selinuxutil.te, policy/modules/system/sysnetwork.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te, policy/modules/system/udev.te
Fix a number of issues related to systemd start-up in enforced mode, primarily focused on `systemd-tmpfilesd` and `systemd-networkd`.
Notable changes include:
* Support for systemd-powered initrd (dracut). This is related to a feature in systemd, which allows it to pass certain socket file descriptors from the initrd's systemd daemon into the main systemd process. Since these are opened before the SELinux policy is loaded, all of them use the default label, which causes a number of denials, as the policy expects them to be labelled. This behaviour is controlled by a new global tunable `init_reuse_initrd_sockets`.
* Support for factory template files in `systemd-tmpfilesd`.
* `systemd-networkd` start-up fixes.
=> Assortment of systemd-related denial fixes

policy/modules/kernel/selinux.if, policy/modules/kernel/selinux.te
Enabling this will disable all permissions for setting SELinux Booleans,
even for unconfined domains.
This does not affect setenforce.  Enable `secure_mode_policyload` along with
`secure_mode_setbool` to fully lock the SELinux security interface.
Fixes #354
=> selinux: Add a secure_mode_setbool Boolean.

config/file_contexts.subs_dist, policy/modules/roles/auditadm.te, policy/modules/roles/dbadm.te, policy/modules/roles/guest.te, policy/modules/roles/logadm.te, policy/modules/roles/secadm.te, policy/modules/roles/webadm.te, policy/modules/services/dbus.if, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/logging.te, policy/modules/system/mount.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te, policy/modules/system/userdomain.if
This finishes up a lot of the work originally started on systemd --user
support including interacting with user units, communicating with the
user's systemd instance, and reading the system journal.
Here is a brief summary of the most important changes:
- there are 3 new types for systemd units, each a different type of user unit: `systemd_user_unit_t` (for user units that are installed system-wide), `systemd_user_conf_home_t` (units that can be created and modified by users), and `systemd_user_runtime_unit_t` (transient and other such units)
- users can now access the system journal and their own user journals, provided that the configured POSIX ACLs allow it
- users can interact with their own systemd user instance
- users can manage and interact with user units and services
Fixes #329
=> systemd --user fixes and additional support

Rules.modular, Rules.monolithic, policy/modules/kernel/files.if, policy/modules/kernel/kernel.te, policy/modules/kernel/selinux.if, policy/modules/kernel/selinux.te
* Change default Boolean type to boolean_t. This will prevent other security_t writers from setting Boolean pending values, which could be activated unwittingly by setbool processes.
* Add dontaudits for secure_mode* Booleans.
Related to #354
=> Secure_mode Boolean improvements

policy/modules/roles/staff.te
This is needed when libvirtd is configured with:
```
unix_sock_group = "wheel"
unix_sock_rw_perms = "0770"
```
to allow non-root users to access the libvirt sockets remotely over SSH.
=> staff.te: Allow staff access to the virt stream

policy/modules/kernel/devices.te, policy/modules/kernel/files.te, policy/modules/services/dbus.te, policy/modules/system/authlogin.te, policy/modules/system/lvm.te, policy/modules/system/miscfiles.te, policy/modules/system/systemd.if
systemd-tmpfiles can manage various file classes but the permission vary depending on the class.
=> systemd: Drop second parameter in systemd_tmpfilesd_managed().

policy/modules/kernel/filesystem.te
The ubifs in linux kernel supported the security xattr handler as early
as version 3.19.0 -rc6. Now add ubifs to the filesystem policy.
Signed-off-by: Xiongwei Song <xiongwei.song@windriver.com>
=> Add ubifs to filesystem policy

policy/modules/admin/kismet.if, policy/modules/apps/gnome.if, policy/modules/apps/qemu.if, policy/modules/apps/wm.if, policy/modules/services/dbus.if, policy/modules/services/git.if, policy/modules/services/rlogin.if, policy/modules/system/userdomain.if
Following the guideline of interfaces not allowed to declare anything and not use prefix parameters, declare interfaces doing so as templates.
Also declare templates not using those features and not calling templates themselves as interfaces.
These changes originate from the discussion in https://github.com/TresysTechnology/selint/issues/205 and are found by new proposed SELint checks at https://github.com/TresysTechnology/selint/pull/206.
=> Use correct interface or template declaration

policy/modules/system/init.te
This will enable su_restricted_domain_template where it was meant to be
enabled before, but was not actually.
Signed-off-by: Markus Linnala <Markus.Linnala@cybercom.com>
=> fix: policy: init: there is no enabled_mls, it is enable_mls

policy/modules/apps/chromium.if, policy/modules/apps/gnome.if, policy/modules/apps/gpg.if, policy/modules/kernel/devices.if, policy/modules/kernel/files.if
Change some interface documents to have common name for file_type.
Add missing parameter documentations. Drop extra parameter documentation.
=> cleanup: Interface docs

policy/modules/services/avahi.if
Even if interface is deprecated, still use all documented parameters.
Signed-off-by: Markus Linnala <Markus.Linnala@cybercom.com>
=> cleanup: policy avahi: avahi_filetrans_pid: doc: add missing params

policy/modules/admin/dmesg.te
Some distros store terminfo data in `/etc/terminfo/`, allow dmesg to read the directory for these.
=> dmesg.te: Added files_read_etc_files()

policy/modules/kernel/devices.fc, policy/modules/roles/sysadm.te
Added character devices and sysadm read/write access to those character devices so userspace tooling in dom0 can function.
=> xen: device and sysadm fixes

policy/modules/services/dhcp.te, policy/modules/services/radvd.te, policy/modules/system/sysnetwork.te
DHCP client needs to handle ICMPv6 packets required for router solicitation when combined with secmark:
```
dhcpcd[2258]: ipv6nd_sendrsprobe: Connection refused
kernel: audit: type=1400 audit(1625835757.027:410): avc:  denied  { send } for  pid=2258 comm="dhcpcd" saddr=... daddr=ff02::2 netif=eno1 scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:object_r:icmp_packet_t:s0 tclass=packet permissive=0
```
=> ICMPv6 secmark fixes

policy/modules/services/virt.fc, policy/modules/services/virt.te
For the new common/system.token file in libvirt 4.7.0 and added permissions to virtd_t and virtlogd_t.
Modelled on: https://github.com/fedora-selinux/selinux-policy/commit/1f761d0bbdc08d21a91cdcbd1909ddb53858e354
libvirt change introducing this: https://gitlab.com/libvirt/libvirt/-/commit/cbfebfc74741a00bddf67b7fa10892b757fffd6
=> virt: Defined virt_runtime_common_t type

policy/modules/services/minidlna.te
Make xdg optional to avoid the following build failure:
```
Compiling targeted policy.28
env LD_LIBRARY_PATH="/home/buildroot/autobuild/instance-1/output-1/host/lib:/home/buildroot/autobuild/instance-1/output-1/host/usr/lib" /home/buildroot/autobuild/instance-1/output-1/host/usr/bin/checkpolicy -c 28 -U deny -S -O -E policy.conf -o policy.28
policy/modules/services/minidlna.te:85:ERROR 'unknown type xdg_music_t' at token ';' on line 146109:
#line 85
allow minidlna_t xdg_music_t:dir { getattr search open };
Rules.monolithic:78: recipe for target 'policy.28' failed
```
Fixes:
- http://autobuild.buildroot.org/results/52490172afd9b72b08a7deb0bd3c2124398bbffa/build-end.log
Signed-off-by: Fabrice Fontaine …
=> policy/modules/services/minidlna.te: make xdg optional

policy/modules/services/ftp.te
Make ssh optional to avoid the following build failure:
```
Compiling targeted policy.30
env LD_LIBRARY_PATH="/home/fabrice/buildroot/output/host/lib:/home/fabrice/buildroot/output/host/usr/lib" /home/fabrice/buildroot/output/host/usr/bin/checkpolicy -c 30 -U deny -S -O -E policy.conf -o policy.30
policy/modules/services/ftp.te:484:ERROR 'type ssh_home_t is not within scope' at token ';' on line 92051:
allow sftpd_t ssh_home_t:dir { open read getattr lock search ioctl add_name remove_name write };
#line 484
```
=> policy/modules/services/ftp.te: make ssh optional

policy/modules/services/ifplugd.te
Make netutils optional to avoid the following build failure:
```
Compiling targeted policy.30
env LD_LIBRARY_PATH="/tmp/instance-3/output-1/host/lib:/tmp/instance-3/output-1/host/usr/lib" /tmp/instance-3/output-1/host/usr/bin/checkpolicy -c 30 -U deny -S -O -E policy.conf -o policy.30
policy/modules/services/ifplugd.te:62:ERROR 'type netutils_exec_t is not within scope' at token ';' on line 73694:
#line 62
allow ifplugd_t netutils_exec_t:file { getattr open map read execute ioctl };
```
Fixes:
- http://autobuild.buildroot.org/results/1e27f5b193d40dfb7c73fbe15d1bef91cb92c27d
=> policy/modules/services/ifplugd.te: make netutils optional

policy/modules/apps/wireshark.te
Make xdg optional to fix the following build failure:
```
Compiling targeted policy.31
env LD_LIBRARY_PATH="/tmp/instance-0/output-1/host/lib:/tmp/instance-0/output-1/host/usr/lib" /tmp/instance-0/output-1/host/usr/bin/checkpolicy -c 31 -U deny -S -O -E policy.conf -o policy.31
policy/modules/apps/wireshark.te:96:ERROR 'unknown type xdg_downloads_t' at token ';' on line 645315:
#line 96
allow wireshark_t xdg_downloads_t:dir { getattr search open };
make[1]: *** [Rules.monolithic:79: policy.31] Error 1
```
Fixes:
- http://autobuild.buildroot.org/results/dfbc667e0c17072ddab89a03244f572d5234da50
=> policy/modules/apps/wireshark.te: make xdg optional

policy/modules/services/samba.te
Make crack optional to avoid the following build failure:
```
Compiling targeted policy.31
env LD_LIBRARY_PATH="/tmp/instance-5/output-1/host/lib:/tmp/instance-5/output-1/host/usr/lib" /tmp/instance-5/output-1/host/usr/bin/checkpolicy -c 31 -U deny -S -O -E policy.conf -o policy.31
policy/modules/services/samba.te:399:ERROR 'type crack_db_t is not within scope' at token ';' on line 360232:
allow smbd_t crack_db_t:dir { getattr search open };
#line 399
```
Fixes:
- http://autobuild.buildroot.org/results/ab7098948d1920e42fa587e07f0513f23ba7fc74
=> policy/modules/services/samba.te: make crack optional

policy/modules/services/chronyd.te
This is required for its `hwtimestamp` option, which otherwise returns:
ioctl(SIOCSHWTSTAMP) failed : Operation not permitted
=> chronyd.te: Grant chronyd_t access to the net_admin capability

policy/modules/apps/wm.if, policy/modules/system/systemd.if, policy/modules/system/userdomain.if
This addresses the issue raised in #365. With the advent of `systemd --user` support, we should support users running various applications through user units and other means. The problem is that any other such applications normally started by a user that transition to their own domain (i.e. `user_systemd_t`) do not have the proper permissions to run other applications.
Many applications' policies have their own way of granting run access to users. Some policies grant access directly with `myapp_domtrans`, `myapp_run`, or by granting an attribute. I think the best way to do this would be to streamline all such interfaces and templates to take exactly 3 parameters: the role prefix, the role, and the type of the user domain. This way we can have a single "proper" way to declare interfaces …
=> Add an attribute for user applications to run other applications

policy/modules/services/rpc.te
There is no fs_manage_nfsd_fs interface.
=> rpc: remove obsolete comment line

policy/modules/services/wireguard.te
Make iptables optional to avoid the following build failure raised since version 2.20210908 and https://github.com/SELinuxProject/refpolicy/commit/7f1a7b1cacd5d211077ce62fbb4e91890e65c820:
```
Compiling targeted policy.33
env LD_LIBRARY_PATH="/tmp/instance-0/output-1/host/lib:/tmp/instance-0/output-1/host/usr/lib" /tmp/instance-0/output-1/host/usr/bin/checkpolicy -c 33 -U deny -S -O -E policy.conf -o policy.33
policy/modules/services/wireguard.te:66:ERROR 'type iptables_exec_t is not within scope' at token ';' on line 591892:
#line 66
allow wireguard_t iptables_exec_t:file { getattr open map read execute ioctl };
make[1]: *** [Rules.monolithic:79: policy.33] Error 1
```
Fixes:
- …
=> policy/modules/services/wireguard.te: make iptables optional

policy/modules/roles/staff.te, policy/modules/roles/unprivuser.te, policy/modules/services/git.fc, policy/modules/services/git.if, policy/modules/services/git.te, policy/modules/services/ssh.if, policy/modules/system/userdomain.if
The git application cannot normally be used by confined users as it requires the `map` permission on files in a repository. To address this, create a policy for the application and allow users to transition to it. `git_client_role_template()` is used to create the access needed for users, and the permissions for the git client are separate from those of the git daemon and git CGI.
=> git: add policy for git application

policy/modules/services/apache.fc
Nginx cache files should have the httpd_cache_t context.
=> File context for nginx cache files

policy/modules/system/userdomain.if
Fixes:
$ newrole -r secadm_r -- -c "sesearch -A -s mount_t -t shell_exec_t -c file"
[Errno 13] Permission denied: '/sys/fs/selinux/policy'
avc:  denied  { read_policy } for  pid=575 comm="python3"
scontext=root:secadm_r:secadm_t:s0-s15:c0.c1023
tcontext=system_u:object_r:security_t:s15:c0.c1023 tclass=security
permissive=0
=> secadm: allow secadm to read selinux policy

policy/modules/kernel/devices.te, policy/modules/kernel/filesystem.if, policy/modules/kernel/filesystem.te
<del>`noxattrfs` is an attribute given to filesystems and mountpoints that do not or should not support/have extended attributes. Unfortunately, the interfaces that grant access to these types of files are way too permissive and can result in, for example, unprivileged users having complete read access to things such as the EFI variable filesystem or container files.</del>
<del>This PR adds corresponding interfaces to manage access to each of these types of filesystems and splits calls to them, where appropriate. The result is mostly unchanged from the previous behavior, with the only noticeable effect being that some domains no longer have access to VM files, container files, or the EFI variable filesystem.</del>
Split noxattrfs out into filesystems which are pseudo filesystems and …
=> Split noxattrfs access

policy/modules/kernel/filesystem.te
Enable extended attributes for inodes on ramfs filesystems, similar to
tmpfs filesystems.
For example systemd uses ramfs for service credentials[1], and xattr
support is needed for per service based labeling[2].
[1]: https://www.freedesktop.org/software/systemd/man/systemd-creds.html
[2]: systemd/systemd#21158
/cc @doverride
=> filesystem: add fs_use_trans for ramfs

policy/modules/services/bind.fc, policy/modules/services/bind.te
* add fcontext for /etc/rc.d/init.d/bind and /etc/bind/rndc.conf
* add getsched for named process
Fixes:
avc: denied { getsched } for pid=418 comm="named"
scontext=system_u:system_r:named_t tcontext=system_u:system_r:named_t
tclass=process permissive=0
=> bind: fixes for bind

policy/modules/admin/usermanage.te
We encountered a passwd runtime error with selinux 3.3:
$ passwd user1
passwd: avc.c:73: avc_context_to_sid_raw: Assertion `avc_running'
failed.
Aborted
Fixes:
avc: denied { map } for pid=325 comm="passwd"
path="/sys/fs/selinux/status" dev="selinuxfs" ino=19 scontext=root:
sysadm_r:passwd_t tcontext=system_u:object_r:security_t tclass=file
permissive=1
=> passwd: allow passwd to map SELinux status page

Makefile
Use install(1) with explicit permission to create directories and
files.  In case umask(2) is set too strict the installed files will
otherwise not be readable by unprivileged users.
=> Ignore umask on when installing headers

policy/modules/services/git.if
I missed this in my original PR for the git private type. This ensures that userdomains can execute git hooks instead of `git_home_t` files.
=> git: fix typo in git hook exec access

policy/support/loadable_module.spt
Duplicate definition of interface or template should only be a warning,
since it does not block the compilation.
The warning should also specify which file contains the original
definition.
Old:
ipa.if:284: Error: duplicate definition of
ipa_cert_filetrans_named_content(). Original definition on 284.
New:
ipa.if:284: Warning: duplicate definition of
ipa_cert_filetrans_named_content(). Original definition on
/usr/share/selinux/devel/include/contrib/ipa.if:284.
Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
=> Report warning on duplicate definition of interface

policy/mcs, policy/modules/admin/rpm.te, policy/modules/admin/tmpreaper.te, policy/modules/kernel/corenetwork.te.in, policy/modules/kernel/mcs.if, policy/modules/services/policykit.te, policy/modules/services/postfix.te, policy/modules/services/watchdog.te, policy/modules/system/init.te, policy/modules/system/systemd.te, policy/modules/system/udev.te, policy/modules/system/unconfined.te
Pull in some changes from the Fedora policy's MCS constraints.
Most notably, the MCS override attributes were deprecated in favor of `mcs_constrained_type`. This means that domains will have unchecked access to objects with categories UNLESS the domain is `mcs_constrained_type`. This alleviates confusion between the MCS overrides and `mcs_constrained_type` to imply that a domain must be MCS-constrained to have MCS checks at all.
Other changes include additional constraints to miscellaneous IPC objects, node "write" operations, and netif egress/ingress operations.
=> mcs: pull in changes from Fedora policy

policy/modules/apps/wine.if
Missed this in the last PR since this template does not have any callers in refpolicy and so the build problem went unnoticed.
It does, however, have callers in Gentoo's policy which is where a build error was encountered.
=> wine: fix roleattribute statement

policy/modules/system/ipsec.fc, policy/modules/system/ipsec.te
* Add fcontext for charon-systemd
* Allow ipsec_mgmt_t to list ipsec_conf_file_t dir
* Allow ipsec_mgmt_t to read cert files
Fixes:
avc:  denied  { search } for  pid=372 comm="swanctl" name="strongswan.d"
dev="vda" ino=1461
scontext=system_u:system_r:ipsec_mgmt_t:s0-s15:c0.c1023
tcontext=system_u:object_r:ipsec_conf_file_t:s0 tclass=dir permissive=0
avc:  denied  { read } for  pid=372 comm="swanctl" name="strongswan.d"
dev="vda" ino=1461
scontext=system_u:system_r:ipsec_mgmt_t:s0-s15:c0.c1023
tcontext=system_u:object_r:ipsec_conf_file_t:s0 tclass=dir permissive=0
avc:  denied  { getattr } for  pid=323 comm="swanctl"
path="/etc/ssl/openssl.cnf" dev="vda" ino=1463
scontext=system_u:system_r:ipsec_mgmt_t
tcontext=system_u:object_r:cert_t tclass=file permissive=0
avc:  denied  { open } for …
=> ipsec: fixes for strongswan

policy/modules/services/ntp.te, policy/modules/services/ssh.if, policy/modules/system/logging.te, policy/modules/system/miscfiles.if, policy/modules/system/systemd.te
* fips_enabled sysctl access
* Unit generator fixes
* Revise tmpfilesd to allow writing of all config files
* User runtime dir reads cgroups
* Journald uses audit_control
=> Various systemd fixes

testing/check_fc_files.py
Allow '@' to be a valid ending character in the file context checker. This allows the usage of `/path/to/myservice@.*` instead of only `/path/to/myservice@\.service` and similar.
=> testing: accept '@' as a valid ending character in filecon checker

policy/modules/system/systemd.te
Seeing the following errors (based on what is in /etc/sysctl.d/*)
Nov 30 13:38:07 localhost systemd-sysctl: Failed to write '1' to '/proc/sys/kernel/kptr_restrict': Operation not permitted
Nov 30 13:38:07 localhost systemd-sysctl: Failed to write '1' to '/proc/sys/kernel/dmesg_restrict': Operation not permitted
Nov 30 13:38:07 localhost systemd-sysctl: Failed to write '1' to '/proc/sys/kernel/yama/ptrace_scope': Operation not permitted
Nov 30 13:38:07 localhost systemd: systemd-sysctl.service: main process exited, code=exited, status=1/FAILURE
I saw the following denials (didn't save the one for sys_ptrace when setting kenel.yama.ptrace_scope):
2021-11-29T15:26:37-05:00 localhost audispd: node=localhost type=AVC msg=audit(1638199548.807:52): avc:  denied  { sys_admin } for  pid=1038 …
=> systemd: resolve error with systemd-sysctl

policy/modules/services/ssh.te
Fixes:
avc:  denied  { read } for  pid=353 comm="ssh-keygen" name="filesystems"
dev="proc" ino=4026532078 scontext=system_u:system_r:ssh_keygen_t
tcontext=system_u:object_r:proc_t tclass=file permissive=0
=> ssh: do not audit attempts by ssh-keygen to read proc

policy/modules/admin/samhain.te, policy/modules/apps/vmware.te, policy/modules/services/abrt.te, policy/modules/services/cron.te, policy/modules/services/cups.te, policy/modules/services/dbus.te, policy/modules/services/ftp.te, policy/modules/services/inetd.te, policy/modules/services/oddjob.te, policy/modules/services/sanlock.te, policy/modules/services/ssh.te, policy/modules/services/virt.te, policy/modules/services/xserver.te, policy/modules/system/locallogin.if, policy/modules/system/setrans.te, policy/modules/system/udev.te, policy/users
Remove MCS categories from the default users and remove most MCS ranged transitions as a result.
I didn't see any ranged transitions that I think needed to stay, as none of the domains I removed them from are `mcs_constrained()`.
Fixes #453
=> Remove MCS categories from default users

policy/modules/system/systemd.fc
Fixes issues like this: audit(1640354247.630:3): op=security_validate_transition seresult=denied oldcontext=system_u:object_r:systemd_journal_t:s15:c0.c1023 newcontext=system_u:object_r:systemd_journal_t:s0 taskcontext=system_u:system_r:systemd_tmpfiles_t:s0-s15:c0.c1023 tclass=file
Fixes #460
=> systemd: Change journal file context to MLS system high.

policy/modules/services/snmp.fc
I believe this missing ? in the .fc file must be a bug.
=> snmp: Fix typo in /var/net-snmp rule

policy/modules/services/docker.if, policy/modules/services/docker.te
Avoid a potential build error and circular dependency by making rootlesskit optional. Note that rootlesskit is still required in order for rootless docker to function.
=> docker: make rootlesskit optional

.github/workflows/tests.yml
This reverts commit 5781a2393cfbc6592cf52abff1eda08afb15c898.
SELint 1.2.1 supports the new policy_module syntax.
=> Revert "tests.yml: Disable policy_module() selint checks."

policy/modules/services/docker.te
Looks like I forgot to add this back at some point while reworking. Oops...
=> docker: add missing call to init_daemon_domain()

policy/modules/services/node_exporter.fc, policy/modules/services/node_exporter.if, policy/modules/services/node_exporter.te
Policy for https://github.com/prometheus/node_exporter (also goes with https://github.com/prometheus/node_exporter/pull/2205).
@0xC0ncord also tested this on systemd for me.
=> node_exporter: Added initial policy

policy/modules/kernel/domain.te
The checks for this class were removed in 5.16.  This object class will be removed in the future.
For more info:
https://lore.kernel.org/selinux/163243191040.178880.4295195865966623164.stgit@olly
=> domain: Allow lockdown for all domains.

policy/modules/services/podman.te
Ensure that when conmon is started, it runs in s0 and is able to
communicate with the container.
This is in support of https://github.com/containers/podman/pull/13093
=> podman: add explicit range transition for conmon

policy/modules/services/dbus.te, policy/modules/services/docker.te, policy/modules/services/podman.te, policy/modules/services/policykit.if, policy/modules/system/init.fc, policy/modules/system/init.if, policy/modules/system/init.te
Add a separate type for systemd runtime units and add tunables to control access to using dbus-broker as the systemd dbus daemon.
The `dbus_broker_system_bus` tunable adds the rules necessary to allow dbus-broker to be used as the system dbus daemon, and `dbus_broker_run_runtime_units` controls whether dbus-broker is allowed to run systemd runtime units. The latter tunable was added to address dbus-broker's default behavior of creating and running arbitrary units itself (instead of asking systemd) if the requested service doesn't exist.
=> Add type for systemd runtime units and add dbus-broker support

policy/modules/admin/sudo.if, policy/modules/kernel/files.if, policy/modules/services/networkmanager.te, policy/modules/system/authlogin.te, policy/modules/system/getty.te, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/locallogin.te, policy/modules/system/systemd.if, policy/modules/system/systemd.te, policy/modules/system/udev.te, policy/modules/system/unconfined.te
Various scattered fixes, mostly systemd-related.
Some of these are:
- Allow init to `nnp_transition` to any init daemon domain (systemd's `NoNewPrivileges` unit option)
- Allowing domains which can use nsswitch to read resolvconf symlinks (for systemd-resolved's stub configuration)
- Polyinstantiation fixes
- Various dontaudits
=> Various fixes, mostly systemd-related

policy/modules/system/systemd.if
Some objects in the `/run/systemd/userdb/` directory are symlinks and `sudo` does not function without this access.
```
audit[438]: AVC avc:  denied  { read } for  pid=438 comm="sudo" name="io.systemd.DropIn" dev="tmpfs" ino=450 scontext=staff_u:staff_r:staff_sudo_t tcontext=system_u:object_r:systemd_userdbd_runtime_t tclass=lnk_file permissive=0
```
=> systemd.if: Allowed reading symlinks in systemd_stream_connect_userdb()

policy/modules/services/container.if, policy/modules/services/container.te, policy/modules/services/podman.if, policy/modules/services/podman.te, policy/modules/system/init.te
A batch of various fixes for the newly added container policies. Of note:
- new tunables to allow containers to access public content
- fixes for containers that request pseudoterminals. There were issues that prevented these from starting up if they were started as systemd units and also issues that prevented them from properly communicating with conmon
- allow podman to create container config files. New behavior in podman 4.0 maintains a lock file in `/etc/cni`.
- fixed role associations. The conmon type was not associated with any roles.
... and a few others. Additional comments can be found in the commit messages.
=> Various container fixes

policy/modules/roles/sysadm.te, policy/modules/services/container.te, policy/modules/services/podman.te
Missed this in my last PR. If the tunables for containers to access public content are enabled, also allow adding a watch on public content directories.
=> container: minor additions

config/appconfig-mcs/seusers, config/appconfig-mls/seusers, config/appconfig-standard/seusers
This breaks systems that do not have the xserver module.
This partially reverts 6e5a6bffdb09992f962a6ecb09a0a90fe3e76269.
Fixes #488
=> seusers: Remove sddm.

policy/modules/services/git.fc
Add missing file contexts for `.git-credentials` in the user's home directory and the git client.
=> git: add missing file contexts

policy/modules/services/docker.te, policy/modules/services/podman.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
Add a separate type for systemd user transient units and rename the interfaces for working with user runtime units such that they are consistent with the naming in the init module.
=> Add a separate type for systemd user transient units, rename interfaces

policy/modules/services/podman.fc, policy/modules/services/podman.if, policy/modules/services/podman.te
This is to lay some groundwork for an upcoming kubernetes policy module, specifically with CRI-O. CRI-O also uses conmon to monitor container processes, but currently this has the side effect of conmon transitioning back to `podman_t` when it executes `runc`, a generic container engine.
To fix this, rework the current conmon policy rules to use a template to generate conmon types. This is so that `podman_t`, `podman_user_t`, and eventually `crio_t` get their own conmon types that transition back to the proper source domain.
This has the side effect of renaming `podman_conmon_user_t` to `podman_user_conmon_t`, ~~but there hasn't been a release with the container module yet so this is OK,~~ and I like the new name better.
Also, add a file context for conmon in `/usr/libexec/conmon` which …
=> Rework conmon rules

policy/modules/services/container.if, policy/modules/system/unconfined.te
Add an unconfined role template for unconfined users such that these users can use container resources but without transitioning to the container engine domains. Containers created by unconfined users will still transition as expected.
This PR also consolidates some of the required role access into their own interfaces for convenience, namely access for container files and container home content.
=> Do not transition to container engines for unconfined users

policy/modules/services/podman.te
Missed this one in #504. `podman_conmon_exec_t` was renamed to `conmon_exec_t`. Add a typealias for this definition.
=> podman: add alias for conmon executable

policy/modules/kernel/filesystem.if, policy/modules/services/container.te
For moving secrets around in various environments, I'm finding ecryptfs to be a workable approach.  This adds a boolean that will permit my containers to access the filesystem if enabled.
=> container: Boolean for ecryptfs

policy/modules/services/ssh.te
With RHEL9 /etc/crypto-policies/back-ends are symlinks to /usr/share/crypto-policies/*/*
node=localhost type=AVC msg=audit(1661303919.946:335): avc:  denied  { getattr } for  pid=1025 comm="ssh-keygen" path="/usr/share/crypto-policies/FIPS/opensslcnf.txt" dev="dm-0" ino=396589 scontext=system_u:system_r:ssh_keygen_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1661303919.946:336): avc:  denied  { read } for  pid=1025 comm="ssh-keygen" name="opensslcnf.txt" dev="dm-0" ino=396589 scontext=system_u:system_r:ssh_keygen_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1661303919.946:336): avc:  denied  { open } for  pid=1025 comm="ssh-keygen" …
=> ssh: allow ssh_keygen to read /usr/share/crypto-policies/

policy/modules/admin/usbguard.te
node=localhost type=AVC msg=audit(1661391275.238:339): avc:  denied  { search } for  pid=1031 comm="usbguard-daemon" name="crypto" dev="proc" ino=20463 scontext=system_u:system_r:usbguard_t:s0 tcontext=system_u:object_r:sysctl_crypto_t:s0 tclass=dir permissive=1
node=localhost type=AVC msg=audit(1661391275.238:339): avc:  denied  { read } for  pid=1031 comm="usbguard-daemon" name="fips_enabled" dev="proc" ino=20464 scontext=system_u:system_r:usbguard_t:s0 tcontext=system_u:object_r:sysctl_crypto_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1661391275.238:339): avc:  denied  { open } for  pid=1031 comm="usbguard-daemon" path="/proc/sys/crypto/fips_enabled" dev="proc" ino=20464 scontext=system_u:system_r:usbguard_t:s0 tcontext=system_u:object_r:sysctl_crypto_t:s0 …
=> usbguard: Allow to read fips_enabled sysctl

Makefile
egrep has been deprecated since 2007 and with version 3.8 calling this commands issues a warning.
=> Replace deprecated egrep usage

policy/modules/system/systemd.if
Fixes:
avc:  denied  { watch } for  pid=329 comm="systemd" path="/etc"
dev="vda" ino=176 scontext=root:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:etc_t tclass=dir permissive=0
systemd[329]: Failed to create timezone change event source: Permission denied
=> systemd: allow systemd user to watch /etc directories

.github/workflows/tests.yml, policy/modules/kernel/files.if, policy/modules/kernel/kernel.if, policy/modules/system/init.if, policy/modules/system/init.te
For non-security mounting, only dir and file access are added, as these are the only ones allowed in the mounton call.
=> init: Add tunable for systemd to create all its mountpoints.

policy/modules/services/firewalld.te, policy/modules/services/networkmanager.te, policy/modules/system/libraries.if
Seeing a bunch of dir watch denials from firewalld_t and NetworkManager_t spamming audit log.
=> fix some denials spamming audit log

policy/modules/admin/fapolicyd.fc, policy/modules/admin/fapolicyd.if, policy/modules/admin/fapolicyd.te, policy/modules/kernel/files.if, policy/modules/roles/sysadm.te
Initial policy for fapolicyd running on RHEL9.  Looked a bit at the RHEL9 policy, but here I have setup different domains for the fapolicyd daemon vs. the fapolicyd-cli vs. fagenpolicy (tool to regen the policy)
I'm sure there will be comments and if there are specific rules in question I'm happy to gather denials.  This was a bit of work and lots of denials while making progress.
Signed-off-by: Dave Sugar <dsugar100@gmail.com>
=> fapolicyd: Initial SELinux policy

policy/modules/system/init.te
Seeing long delay during shutdown saying: 'A stop job is running for Restore /run/initramfs on shutdown'
These were the denials in audit.log related to this
node=localhost type=AVC msg=audit(1663379349.428:5081): avc:  denied  { write } for  pid=3594 comm="cpio" name="initramfs" dev="tmpfs" ino=18 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=1 node=localhost type=AVC msg=audit(1663379349.428:5081): avc:  denied  { add_name } for  pid=3594 comm="cpio" name="bin" scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=1 node=localhost type=AVC msg=audit(1663379349.429:5083): avc:  denied  { create } for  pid=3594 comm="cpio" name="dev" scontext=system_u:system_r:initrc_t:s0 …
=> init_t: fix long delay during shutdown

policy/modules/kernel/devices.if, policy/modules/roles/sysadm.te, policy/modules/services/opensm.fc, policy/modules/services/opensm.if, policy/modules/services/opensm.te
Add a policy for [OpenSM](https://github.com/linux-rdma/opensm), a software implementation of an InfiniBand subnet manager.
=> Add a policy for OpenSM

policy/modules/services/radius.te
* Add dac_read_search capability to radiusd_t
* Add getcap, ptrace and execmem to radiusd_t process
Fixes:
avc: denied { dac_read_search } for pid=473 comm="radiusd" capability=2 scontext=system_u:system_r:radiusd_t
tcontext=system_u:system_r:radiusd_t tclass=capability permissive=1
avc: denied { getcap } for pid=473 comm="radiusd"
scontext=system_u:system_r:radiusd_t
tcontext=system_u:system_r:radiusd_t tclass=process permissive=1
avc: denied { ptrace } for pid=474 comm="radiusd"
scontext=system_u:system_r:radiusd_t
tcontext=system_u:system_r:radiusd_t tclass=process permissive=1
avc: denied { execmem } for pid=475 comm="radiusd" scontext=system_u:system_r:radiusd_t
tcontext=system_u:system_r:radiusd_t tclass=process permissive=1
=> radius: fixes for freeradius

policy/modules/system/logging.te
Fixes:
avc:  denied  { write } for  pid=165 comm="systemd-journal" name="syslog" dev="tmpfs" ino=545 scontext=system_u:system_r:syslogd_t tcontext=system_u:object_r:syslogd_runtime_t tclass=sock_file permissive=0
=> logging: allow systemd-journal to write syslogd_runtime_t sock_file

policy/modules/admin/usbguard.fc, policy/modules/admin/usermanage.fc, policy/modules/services/dbus.if, policy/modules/services/git.fc, policy/modules/services/node_exporter.fc, policy/modules/services/rpc.if, policy/modules/services/rpc.te, policy/modules/services/zfs.te, policy/modules/system/init.fc, policy/modules/system/init.if, policy/modules/system/mount.te, policy/modules/system/systemd.te
A small batch of minor fixes. Notably:
- add file contexts for systemd units in `/lib/dracut/modules.d` so that the resulting services are `systemd_unit_t` instead of `bin_t`
- add file contexts for `git`'s subcommands. This fixes conflicting type specifications between `/usr/bin/git` and its many hardlinks.
- add a couple file contexts for some programs in `/usr/bin` or `/usr/sbin` as they appear in Gentoo
- minor fixes for `rpc` in support of NFS
- allow `systemd-generator` to perform DNS resolution in order to resolve hostnames in `/etc/fstab` for NFS mounts
A couple of these commits are split out from #511 since they are not strictly related.
=> A few minor fixes

policy/modules/system/udev.if
There are some link files under /run/udev directory: $ ls -lZ /run/udev/static_node-tags/uaccess/
total 0
lrwxrwxrwx. 1 root root system_u:object_r:udev_runtime_t:SystemLow 12 Oct 16 08:32 'snd\x2fseq' -> /dev/snd/seq lrwxrwxrwx. 1 root root system_u:object_r:udev_runtime_t:SystemLow 14 Oct 16 08:32 'snd\x2ftimer' -> /dev/snd/timer
Fixes:
avc:  denied  { read } for  pid=297 comm="systemd-logind" name="snd\x2fseq" dev="tmpfs" ino=125
scontext=system_u:system_r:systemd_logind_t:s0-s15:c0.c1023 tcontext=system_u:object_r:udev_runtime_t:s0 tclass=lnk_file permissive=1
=> udev: allow udev_read_runtime_files to read link files

policy/modules/services/watchdog.te
Allow watchdog to create log directory with correct label.
Fixes:
avc: denied { create } for pid=315 comm="watchdog" name="watchdog" scontext=system_u:system_r:watchdog_t tcontext=system_u:object_r:var_log_t tclass=dir permissive=1
=> watchdog: allow watchdog to create /var/log/watchdog directory

policy/modules/services/rngd.te
node=localhost type=AVC msg=audit(1669206851.792:438): avc:  denied  { getattr } for  pid=1008 comm="rngd" path="/usr/share/crypto-policies/FIPS/opensslcnf.txt" dev="dm-0" ino=401368 scontext=system_u:system_r:rngd_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1669206851.792:439): avc:  denied  { read } for  pid=1008 comm="rngd" name="opensslcnf.config" dev="dm-0" ino=401368 scontext=system_u:system_r:rngd_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1669206851.792:439): avc:  denied  { open } for  pid=1008 comm="rngd" path="/usr/share/crypto-policies/FIPS/opensslcnf.txt" dev="dm-0" ino=401368 scontext=system_u:system_r:rngd_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file …
=> rng-tools updated to 6.15 (on RHEL9) seeing the following denials:

policy/modules/system/udev.te
On a gentoo with openRC, udev is denied to read hwdb. On current policy, reading hwdb is only allowed for system with systemd.
In fact it is a common action (beyond openrc/systemd) so rules for reading it must be global.
=> udev: permit to read hwdb

.github/workflows/tests.yml
Fix this issue:
Version 3.5 was not found in the local cache
Error: The version '3.5' with architecture 'x64' was not found for Ubuntu 22.04.
=> tests.yml: Pin ubuntu 20.04.

policy/modules/system/fstools.fc, policy/modules/system/fstools.te
On a gentoo-hardened+selinux, I got denial from fsadm_t reading var_t. This is due to smartctl trying to read /var/db/smartmontools/drivedb.h
=> fstools: handle gentoo place for drivedb.h

support/gentemplates.sh
Template definitions might have a whitespace after the comma, e.g. su_restricted_domain_template
in /policy/modules/admin/su.if
template(\`su_restricted_domain_template', `
...
')
gentemplates.sh silently fails to parse it. This works unless 'set -e' is set, in which case the script fails non-silently.
This commit adds support of whitespace after comma, which is a valid syntax.
=> Fix templates parsing in gentemplates.sh

policy/modules/system/mount.te
On gentoo, when emerging selinux-base-policy, the post install (loading policy) fail due to a missing type. This is due to mount.te using a dbus interface and the dbus module is not present. Fix this by setting the dbus interface as optional;
=> mount: dbus interface must be optional

policy/modules/kernel/corecommands.fc
I got the following AVC:
allow mcelog_t mcelog_etc_t:file execute;
This is due do some trigger, not being set as bin_t
-rwxr-xr-x. 1 root root system_u:object_r:bin_t         801 nov.   1 19:11 bus-error-trigger
-rwxr-xr-x. 1 root root system_u:object_r:bin_t        1035 nov.   1 19:11 cache-error-trigger
-rwxr-xr-x. 1 root root system_u:object_r:bin_t        1213 nov.   1 19:11 dimm-error-trigger
-rwxr-xr-x. 1 root root system_u:object_r:bin_t         742 nov.   1 19:11 iomca-error-trigger
-rw-r-----. 1 root root system_u:object_r:mcelog_etc_t 7415 nov.   1 19:11 mcelog.conf
-rwxr-xr-x. 1 root root system_u:object_r:mcelog_etc_t 1209 nov.   1 19:11 page-error-counter-replacement-trigger
-rwxr-xr-x. 1 root root system_u:object_r:mcelog_etc_t 1656 nov.   1 19:11 …
=> mcelog: add missing file context for triggers

policy/modules/kernel/files.fc
Some Munin plugins need to read the plugin.sh file providing common functions.
=> munin: add file context for common functions file

policy/modules/services/munin.if, policy/modules/services/munin.te, policy/modules/system/fstools.te
smart_ plugin currently execute smartctl on the disk_munin_plugin_t domain. But lot of rules are still missing for a correct smartctl execution. Instead of duplicating most of all fsadm rules, it is easier to transition to the correct domain.
=> munin: disk-plugin: transition to fsadm

policy/modules/kernel/devices.fc, policy/modules/system/logging.fc
On gentoo, starting rsyslog give this:
allow syslogd_t var_t:dir { add_name remove_name }; allow syslogd_t var_t:sock_file { create setattr unlink };
This is due to the following piece of code in configuration: """
Create an additional socket for the default chroot location
(used by net-misc/openssh[hpn], see https://bugs.gentoo.org/490744)
input(type="imuxsock" Socket="/var/empty/dev/log")
"""
So let's add correct label for this file
=> rsyslog: add label for /var/empty/dev/log

policy/modules/services/munin.fc
Gentoo deploy munin-node plugin state in /var/lib/munin-node
=> munin: add fc for munin-node plugin state

policy/modules/admin/usermanage.te
When using groupadd, I got some AVC due to groupadd reading /proc/sys/kernel/cap_last_cap
=> usermanage: permit groupadd to read kernel sysctl

policy/modules/admin/portage.if, policy/modules/system/selinuxutil.te
Each time portage build and install a new SELinux policy I got the following AVC: allow load_policy_t portage_devpts_t:chr_file { read write };
=> selinuxutil: permit load_policy to use portage ptys

policy/modules/admin/portage.fc
go/hg source files context are added in old portage distfiles location, but are missing in new one.
=> portage: add missing go/hg context in new distfiles location

policy/modules/services/openvpn.te
OpenVPN 2.6 can use an OpenVPN specific kernel module to handle the VPN data channel.  The communication via userspace and kernel space happens over a generic netlink interface.
Without this access, the following denials can be found in the logs
[...] denied  { create } for pid=... comm="openvpn" scontext=system_u:system_r:openvpn_t:s0 tcontext=system_u:system_r:openvpn_t:s0 tclass=netlink_generic_socket
[...] denied  { setopt } for pid=... comm="openvpn" scontext=system_u:system_r:openvpn_t:s0 tcontext=system_u:system_r:openvpn_t:s0 tclass=netlink_generic_socket
[...] denied  { bind } for pid=... comm="openvpn" scontext=system_u:system_r:openvpn_t:s0 tcontext=system_u:system_r:openvpn_t:s0 tclass=netlink_generic_socket
[...] denied  { getattr } for pid=... comm="openvpn" …
=> openvpn: Allow netlink genl

policy/modules/apps/mandb.te
Each night /etc/cron.daily/man-db generates some AVC: allow mandb_t system_cronjob_tmp_t:file { read write };
Add the necessary rules for it.
=> mandb: permit to read inherited cron files

policy/modules/system/selinuxutil.te
When restarting services with run_init, I got some AVC due to run_init reading /proc/sys/kernel/cap_last_cap
=> selinuxutil: permit run_init to read kernel sysctl

policy/modules/services/container.fc, policy/modules/services/container.te
Add a missing file transition for the docker socket in `/run` as well as a missing file context for `/var/log/containerd`.
=> container: add missing filetrans and filecon for containerd/docker

policy/modules/system/init.fc
Feb 24 19:02:53 localhost audit[1664]: AVC avc:  denied  { write } for  pid=1664 comm="systemd-oomd" path=2F6D656D66643A646174612D6664202864656C6574656429 dev="tmpfs" ino=2051 scontext=system_u:system_r:initrc_t tcontext=system_u:object_r:tmpfs_t tclass=file permissive=1
Needs to manage cgroups and kill processes, so make it init_exec_t
=> Set label systemd-oomd

policy/modules/admin/portage.if, policy/modules/admin/portage.te
Add missing rules for portage I encountered while emerging or just calling gcc-config
=> portage: add misc mising rules

policy/modules/system/systemd.te
Fixes:
avc:  denied  { search } for  pid=233 comm="systemd-resolve" name="/" dev="tmpfs" ino=1 scontext=system_u:system_r:systemd_resolved_t tcontext=system_u:object_r:tmpfs_t tclass=dir permissive=1
avc:  denied  { search } for  pid=233 comm="systemd-resolve" name="/" dev="ramfs" ino=813 scontext=system_u:system_r:systemd_resolved_t tcontext=system_u:object_r:ramfs_t tclass=dir permissive=1
=> systemd: allow systemd-resolved to search directories on tmpfs and ramfs

policy/modules/apps/pulseaudio.te
The pulseaudio daemon and client do not normally need to use
the network for most computer systems that need to play and
record audio.
So, network access by pulseaudio should normally be restricted.
This patch restricts all network access by using tunable policy
and a new boolean to control it.
---
policy/modules/apps/pulseaudio.te |   47 ++++++++++++++++++++++++--------------
1 file changed, 30 insertions(+), 17 deletions(-)
=> pulseaudio: restrict network access

policy/modules/apps/mplayer.fc, policy/modules/apps/mplayer.te
path marking for vlc(https://www.videolan.org/vlc/)
*To write these paths, the domain still needs to be granted access to xdg_{data,config,cache}_t
=> path marking for vlc(mplayer_t)

policy/modules/services/dovecot.te
I use dovecot for IMAP hosting and several rules are missing.
=> dovecot: add missing permissions

policy/modules/services/smartmon.fc, policy/modules/services/smartmon.te, policy/modules/system/fstools.if
update-smart-drivedb is a fsadm_t like but with access to network, so Since it do network access, and dont access any hardware, let's add its own domain.
=> fsadm: add domain for update-smart-drivedb

policy/modules/services/container.fc
The kubernetes local-path-provisioner uses either
/opt/local-path-provisioner or
/var/local-path-provisioner for its physical volumes
=> container: set default context for local-path-provisioner

policy/modules/kernel/corecommands.fc
OpenRC reads zfs config during boot.
----
type=PROCTITLE msg=audit(04/27/23 13:56:20.937:11) : proctitle=/bin/sh /lib/rc/sh/gendepends.sh
type=SYSCALL msg=audit(04/27/23 13:56:20.937:11) : arch=x86_64 syscall=openat success=yes exit=4 a0=AT_FDCWD a1=0x558b0743b330 a2=O_RDONLY a3=0x0 items=0 ppid=356 pid=605 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=roo
t sgid=root fsgid=root tty=tty1 ses=unset comm=gendepends.sh exe=/bin/bash subj=system_u:system_r:initrc_t:s0-s15:c0.c1023 key=(null)
type=AVC msg=audit(04/27/23 13:56:20.937:11) : avc:  granted  { read open } for  pid=605 comm=gendepends.sh path=/etc/zfs/zfs-functions dev="dm-3" ino=658657 scontext=system_u:system_r:initrc_t:s0-s15:c0.c1023 tcontext=system_u:object_r:zf
s_config_t:s0 tclass=file
type=AVC …
=> Allow initrc_t read zfs config files.

policy/modules/services/zfs.te
During boot openrc service zfs-import creates /run/blkid/ dir and /run/blkid/blkid.tab file. There is file transition rule for both { dir file }, but policy lacks dir { create } permission.
As for cups.te config I believe manage dir permission should go there as well.
type=PROCTITLE msg=audit(05/03/23 09:33:15.202:10) : proctitle=/sbin/zpool import
type=PATH msg=audit(05/03/23 09:33:15.202:10) : item=1 name=(null) inode=986 dev=00:16 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:zfs_runtime_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(05/03/23 09:33:15.202:10) : item=0 name=(null) inode=1 dev=00:16 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:var_run_t:s0-s15:c0.c1023 nametype=PARENT cap_fp=none …
=> Dir transition goes with dir create perms.

policy/modules/services/zfs.te, policy/modules/system/fstools.if
Lot of fsadm tools is using /run/blkid/.
I've reached condition when zpool was one to create this dir/file.
This can be relabeled due to https://github.com/SELinuxProject/refpolicy/blob/8f563f58ea6b09ff18bc67b571f65f2e615cdff0/policy/modules/system/fstools.fc#L119
If this gets created by zpool it will break other tools:
type=PROCTITLE msg=audit(05/10/23 15:53:02.940:792) : proctitle=blkid
type=PATH msg=audit(05/10/23 15:53:02.940:792) : item=0 name=/run/blkid/blkid.tab inode=987 dev=00:16 mode=file,644 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:zfs_runtime_t:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(05/10/23 15:53:02.940:792) : cwd=/root
type=SYSCALL msg=audit(05/10/23 15:53:02.940:792) : arch=x86_64 syscall=newfstatat …
=> Keep context of blkid file/dir when created by zpool.

policy/modules/apps/chromium.te
Closes: https://github.com/SELinuxProject/refpolicy/issues/605
=> chromium: allow chromium-naclhelper to create user namespaces

policy/modules/services/container.te
Hello,
While testing Cilium CNI in a Kubernetes cluster, I noticed the following denials:
```
Jun 20 08:01:43 localhost audit[3480]: AVC avc:  denied  { open } for  pid=3480 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=perf_event permissive=1
Jun 20 08:01:43 localhost audit[3480]: AVC avc:  denied  { kernel } for  pid=3480 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=perf_event permissive=1
Jun 20 08:01:43 localhost audit[3480]: AVC avc:  denied  { cpu } for  pid=3480 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=perf_event permissive=1
Jun 20 08:01:43 localhost audit[3480]: AVC avc:  denied  { read } for  pid=3480 …
```
=> container: fix cilium denial

policy/modules/kernel/kernel.if, policy/modules/kernel/kernel.te
The pressure stall information (PSI) special files in /proc/pressure currently don't have a separate file context, and so default to proc_t. Since users need read/write permissions to those files to use PSI, and handing out blanket permissions to proc_t is strongly discouraged, introduce a new proc_psi_t label, as well as interfaces for it.
=> Add label and interfaces for kernel PSI files

policy/modules/services/container.te
Rework (primarily) non-namespaced capabilities. These accesses are leftovers from earlier policy versions before the container module was introduced that are most likely too coarse for most container applications.
Put all non-namespaced capability accesses for containers behind tunables, borrowing ideas from container-selinux. For the more privileged capabilities (sysadmin, mknod), add a tunable to control both namespaced and non-namespaced access to these operations.
I'm not hard-set on having a tunable for namespaced and a tunable for non-namespaced capabilities each, so if there is any opposition I'd be happy to change it.
=> container: rework capabilities

policy/modules/system/authlogin.if, policy/modules/system/locallogin.te
node=localhost type=AVC msg=audit(1689384764.155:53945): avc:  denied  { getattr } for  pid=5125 comm="login" path="/run/motd" dev="tmpfs" ino=1574 scontext=system_u:system_r:local_login_t:s0 tcontext=system_u:object_r:pam_motd_runtime_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1689384764.155:53946): avc:  denied  { read } for  pid=5125 comm="login" name="motd" dev="tmpfs" ino=1574 scontext=system_u:system_r:local_login_t:s0 tcontext=system_u:object_r:pam_motd_runtime_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1689384764.155:53946): avc:  denied  { open } for  pid=5125 comm="login" path="/run/motd" dev="tmpfs" ino=1574 scontext=system_u:system_r:local_login_t:s0 tcontext=system_u:object_r:pam_motd_runtime_t:s0 tclass=file permissive=1
=> Allow local login to read /run/motd

policy/modules/system/init.te
Need to allow this to open the file so the service starts properly.
node=localhost type=AVC msg=audit(1689883855.890:419): avc:  denied  { open } for  pid=1 comm="systemd" path="/dev/rfkill" dev="devtmpfs" ino=152 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:wireless_device_t:s0 tclass=chr_file permissive=1
node=localhost type=AVC msg=audit(1689883962.317:408): avc:  denied  { read write } for  pid=1 comm="systemd" name="rfkill" dev="devtmpfs" ino=152 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:wireless_device_t:s0 tclass=chr_file permissive=0
=> systemd-rfkill.socket reads and writes /dev/rfkill (with ListenSocket=) option.

policy/modules/services/dbus.if
node=localhost type=AVC msg=audit(1689811752.145:511): avc:  denied  { read } for  pid=2622 comm="lightdm-gtk-gre" name="machine-id" dev="dm-10" ino=262170 scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:system_dbusd_var_lib_t:s0 tclass=lnk_file permissive=0
node=localhost type=AVC msg=audit(1689811752.404:514): avc:  denied  { read } for  pid=2629 comm="at-spi-bus-laun" name="machine-id" dev="dm-10" ino=262170 scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:system_dbusd_var_lib_t:s0 tclass=lnk_file permissive=0
=> If domain can read system_dbusd_var_lib_t files, also allow symlinks

policy/modules/admin/usermanage.te, policy/modules/system/authlogin.fc, policy/modules/system/authlogin.te
pwhistory_helper is executed by pam_pwhistory (as configued in /etc/pam.d/sysem-auth).  It updates /etc/security/opasswd which contains old passwords.  Label /etc/security/opasswd as shadow_t to control access.
node=localhost type=AVC msg=audit(1689391847.287:8989): avc:  denied  { execute } for  pid=2667 comm="passwd" name="pwhistory_helper" dev="dm-1" ino=402516 scontext=toor_u:staff_r:passwd_t:s0 tcontext=system_u:object_r:updpwd_exec_t:s0 tclass=file permissive=1
node=localhost type=AVC msg=audit(1689391847.287:8989): avc:  denied  { read open } for  pid=2667 comm="passwd" path="/usr/sbin/pwhistory_helper" dev="dm-1" ino=402516 scontext=toor_u:staff_r:passwd_t:s0 tcontext=system_u:object_r:updpwd_exec_t:s0 tclass=file permissive=1
node=localhost type=AVC …
=> Label pwhistory_helper

policy/modules/services/xserver.te
node=localhost type=AVC msg=audit(1689822970.302:4180): avc:  denied  { write } for  pid=2610 comm="iceauth" path="/home/toor/.xsession-errors" dev="dm-9" ino=129541 scontext=toor_u:staff_r:iceauth_t:s0 tcontext=system_u:object_r:xsession_log_t:s0 tclass=file permissive=1
=> Allow iceauth write to xsession log

policy/modules/kernel/devices.fc, policy/modules/kernel/devices.if, policy/modules/kernel/devices.te, policy/modules/services/iiosensorproxy.fc, policy/modules/services/iiosensorproxy.if, policy/modules/services/iiosensorproxy.te
iio-sensor-proxy (Debian package iio-sensor-proxy)
IIO sensors to D-Bus proxy
Industrial I/O subsystem is intended to provide support for devices
that in some sense are analog to digital or digital to analog convertors
.
Devices that fall into this category are:
* ADCs
* Accelerometers
* Gyros
* IMUs
* Capacitance to Digital Converters (CDCs)
* Pressure Sensors
* Color, Light and Proximity Sensors
* Temperature Sensors
* Magnetometers
* DACs
* DDS (Direct Digital Synthesis)
* PLLs (Phase Locked Loops)
* Variable/Programmable Gain Amplifiers (VGA, PGA)
Signed-off-by: Russell Coker <russell@coker.com.au>
=> Add iio-sensor-proxy.

policy/modules/services/smartmon.te
Revert obsolete permissions that are no longer needed, after the database file got its own label:
Date:   Wed Feb 16 07:24:34 2011 +0100
patch to allow smartmon to read usr files
37ba0d04377033e44d3808d6c795c18edba191bb
policy/modules/services/smartmon.te |    1 -
1 file changed, 1 deletion(-)
=> Smartmon policy update

policy/modules/kernel/kernel.te
Remove misplaced or really obsolete permissions during kernel module loading.
policy/modules/kernel/kernel.te |   12 ------------
1 file changed, 12 deletions(-)
=> Update the kernel module to remove misplaced or obsolete permissions

policy/modules/services/dbus.te
Examples of denials I'm seeing requiring this type of access: 
node=localhost type=USER_AVC msg=audit(1689811749.504:399): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=81 path="/usr/lib/systemd/system/systemd-hostnamed.service" cmdline="/usr/bin/dbus-broker-launch --scope system --audit" function="bus_unit_method_start_generic" scontext=system_u:system_r:system_dbusd_t:s0 tcontext=system_u:object_r:systemd_unit_t:s0 tclass=service permissive=0 exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=?  terminal=?'␝UID="root" AUID="unset" AUID="root" UID="root" GID="dbus" SAUID="root" 
node=localhost type=USER_AVC msg=audit(1692287535.229:262): pid=1 uid=0 auid=4294967295 ses=4294967295 …
=> Allow system_dbusd_t to start/stop all units

policy/modules/system/authlogin.fc, policy/modules/system/authlogin.te
Fix label (for RedHat) which places utempter in /usr/libexec/utempter/utempter
Allow utempter to write to xsession log
Sep 07 01:30:50 localhost.localdomain audisp-syslog[1649]: node=localhost type=AVC msg=audit(1694050250.483:3994): avc:  denied  { write } for  pid=1927 comm="utempter" path="/home/toor/.xsession-errors" dev="dm-9" ino=129543 scontext=toor_u:staff_r:utempter_t:s0 tcontext=toor_u:object_r:xsession_log_t:s0 tclass=file permissive=1
Sep 07 01:30:50 localhost.localdomain audisp-syslog[1649]: node=localhost type=AVC msg=audit(1694050250.485:3997): avc:  denied  { getattr } for  pid=1927 comm="utempter" path="/home/toor/.xsession-errors" dev="dm-9" ino=129543 scontext=toor_u:staff_r:utempter_t:s0 tcontext=toor_u:object_r:xsession_log_t:s0 tclass=file permissive=1
=> Updates for utempter

policy/modules/services/xserver.te
Sep 01 01:53:02 localhost.localdomain audisp-syslog[1524]: node=localhost type=AVC msg=audit(1693533182.968:431): avc:  denied  { search } for  pid=1744 comm="sddm-greeter" name="hwdata" dev="dm-1" ino=1726 scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:hwdata_t:s0 tclass=dir permissive=1
Sep 01 01:53:02 localhost.localdomain audisp-syslog[1524]: node=localhost type=AVC msg=audit(1693533182.968:432): avc:  denied  { read } for  pid=1744 comm="sddm-greeter" name="pnp.ids" dev="dm-1" ino=1730 scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:hwdata_t:s0 tclass=file permissive=1
Sep 01 01:53:02 localhost.localdomain audisp-syslog[1524]: node=localhost type=AVC msg=audit(1693533182.968:432): avc:  denied  { open } for  pid=1744 comm="sddm-greeter" …
=> Allow display manager to read hwdata

policy/modules/apps/mplayer.te
Let vlc (mplayer) act as a dbus session client and read device sysctls.
=> mplayer module fixes for vlc

policy/modules/services/xserver.if
Sep 07 23:30:46 localhost audisp-syslog[1669]: node=localhost type=AVC msg=audit(1694129445.663:3622): avc:  denied  { search } for pid=1844 comm="xhost" name="lightdm" dev="tmpfs" ino=1504 scontext=toor_u:staff_r:staff_t:s0 tcontext=system_u:object_r:xdm_var_run_t:s0 tclass=dir permissive=0
=> Allow search xdm_var_run_t directories along with reading files.

policy/modules/system/logging.te
This patchset introduces a new "logging_syslog_can_network" boolean and corresponding tunable policy to isolate the syslog daemon from the network for increased security in most of its use cases.
See also: https://github.com/SELinuxProject/refpolicy/pull/644#issuecomment-1707302056
=> Increase general syslog daemon policy security by making network permissions tunable

policy/modules/system/userdomain.if
According to comments the interface has been moved to the xscreensaver module, but never removed from the userdomain module.
=> Remove an unneeded logging interface from the userdomain module

policy/modules/services/xserver.if, policy/modules/services/xserver.te
Separate the tunable permissions to write xserver tmpfs files from the tunable permissions to write X server shared memory.
This allows a stricter, yet more customizable policy.
Fix a security bug in one xserver module interface which allows to bypass existing tunable policy logic.
=> Stricter yet more customizable xserver policy and three security bug fixes

policy/modules/services/ssh.if
Aug 29 21:38:07 localhost.localdomain audisp-syslog[1582]: node=localhost type=AVC msg=audit(1693345086.894:3623): avc:  denied  { write } for  pid=1840 comm="ssh-agent" path="/home/sugar/.xsession-errors" dev="dm-9" ino=65541 scontext=staff_u:staff_r:staff_ssh_agent_t:s0 tcontext=system_u:object_r:xsession_log_t:s0 tclass=file permissive=1
Aug 29 21:38:07 localhost.localdomain audisp-syslog[1582]: node=localhost type=AVC msg=audit(1693345086.937:3634): avc:  denied  { getattr } for  pid=1840 comm="ssh-agent" path="/usr/share/crypto-policies/FIPS/opensslcnf.txt" dev="dm-1" ino=262231 scontext=staff_u:staff_r:staff_ssh_agent_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1
Aug 29 21:38:07 localhost.localdomain audisp-syslog[1582]: node=localhost type=AVC …
=> Fix some ssh agent denials

policy/modules/services/xserver.fc
based on denials, the fact that sddm runs as xdm_t and how other directories are labeled, xdm_var_lib_t seems more correct here.
Sep 13 14:57:10 localhost.localdomain audisp-syslog[1570]: node=localhost type=AVC msg=audit(1694617030.144:419): avc:  denied  { search } for  pid=1702 comm="sddm" name="sddm" dev="dm-10" ino=393297 scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:xkb_var_lib_t:s0 tclass=dir permissive=0
Sep 13 14:59:31 localhost.localdomain audisp-syslog[1571]: node=localhost type=AVC msg=audit(1694617171.431:477): avc:  denied  { add_name } for  pid=1768 comm="QQmlThread" name=".cache" scontext=system_u:system_r:xdm_t:s0 tcontext=system_u:object_r:xkb_var_lib_t:s0 tclass=dir permissive=1
Sep 13 14:59:31 localhost.localdomain audisp-syslog[1571]: node=localhost …
=> /var/lib/sddm should be xdm_var_lib_t

policy/modules/system/logging.te
Aug 28 19:01:43 localhost.localdomain audisp-syslog[1565]: node=localhost type=AVC msg=audit(1693249303.693:415): avc:  denied  { setpcap } for  pid=1722 comm="rsyslogd" capability=8 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:system_r:syslogd_t:s0 tclass=capability permissive=0
Aug 28 19:01:43 localhost.localdomain rsyslogd[1722]: libcap-ng used by "/usr/sbin/rsyslogd" failed dropping bounding set in capng_apply
=> Allow rsyslog to drop capabilities

policy/modules/system/systemd.te
systemd_hostnamed allowed to read/update/delete /run/systemd/default-hostname
○ systemd-hostnamed.service - Hostname Service
Loaded: loaded (/usr/lib/systemd/system/systemd-hostnamed.service; static)
Drop-In: /usr/lib/systemd/system/systemd-hostnamed.service.d
└─disable-privatedevices.conf
Active: inactive (dead)
Docs: man:systemd-hostnamed.service(8)
man:hostname(5)
man:machine-info(5)
man:org.freedesktop.resolve1(5)
Sep 13 12:51:32 localhost systemd[1]: Starting Hostname Service...
Sep 13 12:51:32 localhost systemd[1]: Started Hostname Service.
Sep 13 12:51:32 localhost systemd-hostnamed[1777]: Failed to read /run/systemd/default-hostname, ignoring: Permission denied
Sep 13 12:51:32 localhost.localdomain systemd-hostnamed[1777]: Hostname set to <localhost.localdomain> (transient)
Sep 13 …
=> For systemd-hostnamed service to run

policy/modules/services/xserver.te
I was having a problem where when booting to an X login screen (sddm or lightdm) on RHEL9, there was no keyboard/mouse access.  Thus I was stuck.  This one change seems to resolve.  
Sep 08 03:15:59 localhost audisp-syslog[1620]: node=localhost type=AVC msg=audit(1694142959.038:650): avc:  denied  { getattr } for  pid=1695 comm="Xorg" name="/" dev="sysfs" ino=1 scontext=system_u:system_r:xserver_t:s0 tcontext=system_u:object_r:sysfs_t:s0 tclass=filesystem permissive=0
=> Solve issue with no keyboard/mouse on X login screen

policy/modules/apps/gpg.te
Without the patch in this pull request the following error is produced:
$ gpg --recv-keys EA3A87F0A4EBA030E45DF2409E8C1AFBBEFFDB32
gpg: error running '/usr/bin/dirmngr': exit status 1
gpg: failed to start dirmngr '/usr/bin/dirmngr': Generic error
gpg: can't connect to the dirmngr: Generic error
gpg: keyserver receive failed: dirmngr is not installed
policy/modules/apps/gpg.te |    2 ++
1 file changed, 2 insertions(+)
=> Update the gpg module so that the application is able to fetch keys from the network

policy/modules/system/lvm.te
Errors:
Sep 06 15:27:15 localhost systemd-cryptsetup[1611]: Device luks-7e802906-791a-432d-8069-dd290fba6dcf is still in use. Sep 06 15:27:15 localhost systemd-cryptsetup[1611]: Failed to deactivate: Device or resource busy
Sep 06 15:27:15 localhost systemd[1]: systemd-cryptsetup@luks\x2d7e802906\x2d791a\x2d432d\x2d8069\x2ddd290fba6dcf.service: Control process exited, code=exited, status=1/FAILURE
Sep 06 15:27:15 localhost systemd[1]: systemd-cryptsetup@luks\x2d7e802906\x2d791a\x2d432d\x2d8069\x2ddd290fba6dcf.service: Failed with result 'exit-code'.
Denials:
Sep 06 15:25:19 localhost.localdomain audisp-syslog[1522]: node=localhost type=AVC msg=audit(1694013919.081:10597): avc:  denied  { getattr } for  pid=1996 comm="systemd-cryptse" name="/" dev="cgroup2" ino=1 …
=> resolve lvm_t issues at shutdown with LUKS encrypted devices

policy/modules/admin/shutdown.fc, policy/modules/admin/shutdown.te, policy/modules/kernel/files.if, policy/modules/system/init.fc, policy/modules/system/init.if, policy/modules/system/init.te
Fix the label and interface needed to manage the random seed file (additional entropy source) used during system boot/reboot.
Modify the init and shutdown policy accordingly and also fix some bugs in the latter module.
=> init and shutdown fixes

policy/modules/services/xserver.te, policy/modules/system/authlogin.fc, policy/modules/system/authlogin.if, policy/modules/system/authlogin.te, policy/modules/system/locallogin.te
Seting /etc/security/opasswd to shadow_t has some negative side effects like the fact that pam_unix needs to read that.  Once pam_unix can read shadow_t that changes the behavour of how pam_unix uses unix_update to update the password.  So, this change defines the new type, shadow_history_t, for /etc/secuirty/opasswd.
=> separate label for /etc/security/opasswd

policy/modules/apps/gpg.if, policy/modules/services/mta.if, policy/modules/services/spamassassin.if, policy/modules/services/spamassassin.te
Spamassassin is currently unable to fetch updates filtering rules from the network.
This pull request aims to fix https://github.com/SELinuxProject/refpolicy/issues/362
=> Let spamassassin update its rules from the network

policy/modules/system/unconfined.te
Since the `systemd --user` for `unconfined_t` runs in `unconfined_t` too, instead of a derived domain such as with regular users, e.g., `user_systemd_t`, this is required.
=> unconfined: Keys are linkable by systemd.

policy/modules/services/xserver.fc, policy/modules/services/xserver.if, policy/modules/services/xserver.te
Disable X11 server TCP/IP networking functionality by default, as it is generally insecure.
=> Remote X11 TCP/IP functionality is generally insecure: switch it off by default. Strengthen XDM authentication file access.

policy/modules/system/userdomain.if, policy/modules/system/userdomain.te
Aug 29 12:53:06 localhost.localdomain audisp-syslog[1550]: node=localhost type=AVC msg=audit(1693313586.678:437): avc:  denied  { write } for  pid=1757 comm="systemctl" name="socket" dev="tmpfs" ino=58 scontext=user_u:user_r:user_t:s0 tcontext=system_u:object_r:devlog_t:s0 tclass=sock_file permissive=1
Aug 29 12:53:06 localhost.localdomain audisp-syslog[1550]: node=localhost type=AVC msg=audit(1693313586.678:437): avc:  denied  { sendto } for  pid=1757 comm="systemctl" path="/run/systemd/journal/socket" scontext=user_u:user_r:user_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket permissive=1
Aug 29 13:10:01 localhost.localdomain audisp-syslog[1545]: node=localhost type=AVC msg=audit(1693314601.860:435): avc:  denied  { write } for  pid=1756 comm="systemctl" …
=> Allow all users to send syslog messages

policy/modules/services/colord.te
Sep 13 19:20:51 localhost.localdomain audisp-syslog[1531]: node=localhost type=AVC msg=audit(1694632851.771:656): avc:  denied  { read } for  pid=2039 comm="colord" name="hwdb.bin" dev="dm-1" ino=393952 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:object_r:systemd_hwdb_t:s0 tclass=file permissive=1
Sep 13 19:20:51 localhost.localdomain audisp-syslog[1531]: node=localhost type=AVC msg=audit(1694632851.771:656): avc:  denied  { open } for  pid=2039 comm="colord" path="/etc/udev/hwdb.bin" dev="dm-1" ino=393952 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:object_r:systemd_hwdb_t:s0 tclass=file permissive=1
Sep 13 19:20:51 localhost.localdomain audisp-syslog[1531]: node=localhost type=AVC msg=audit(1694632851.771:657): avc:  denied  { getattr } for  pid=2039 …
=> Resolve some denials with colord

policy/modules/system/systemd.te
systemd-networkd creates files in /run/systemd directory which should be labeled appropriately.
Fixes:
avc:  denied  { create } for  pid=136 comm="systemd-network" name=".#networkd2c6a2ac2dbf34a8"
scontext=system_u:system_r:systemd_networkd_t
tcontext=system_u:object_r:init_runtime_t tclass=file permissive=1
avc:  denied  { write } for  pid=136 comm="systemd-network" path="/run/systemd/.#networkd2c6a2ac2dbf34a8" dev="tmpfs" ino=81 scontext=system_u:system_r:systemd_networkd_t
tcontext=system_u:object_r:init_runtime_t tclass=file permissive=1
avc:  denied  { setattr } for  pid=136 comm="systemd-network" name=".#networkd2c6a2ac2dbf34a8" dev="tmpfs" ino=81 scontext=system_u:system_r:systemd_networkd_t
tcontext=system_u:object_r:init_runtime_t tclass=file permissive=1
avc:  denied  { rename } …
=> systemd: allow systemd-networkd to create file in /run/systemd directory

policy/modules/system/logging.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.te
Basically same permissions as it had when running in initrc_t with addition of manage for systemd_journal_t files
=> separate domain for journalctl during init

policy/modules/system/systemd.te
If /var/lib/systemd/catalog doesn't exist at first boot, systemd-journal-catalog-update.service would fail:
$ systemctl status systemd-journal-catalog-update.service
systemd-journal-catalog-update.service - Rebuild Journal Catalog
Loaded: loaded (/usr/lib/systemd/system/systemd-journal-catalog-update.service; static)
Active: failed (Result: exit-code) since Sat 2023-09-30 09:46:46 UTC; 50s ago
Docs: man:systemd-journald.service(8)
man:journald.conf(5)
Process: 247 ExecStart=journalctl --update-catalog (code=exited, status=1/FAILURE)
Main PID: 247 (code=exited, status=1/FAILURE)
Sep 30 09:46:45 qemux86-64 systemd[1]: Starting Rebuild Journal Catalog...
Sep 30 09:46:46 qemux86-64 journalctl[247]: Failed to create parent directories of /var/lib/systemd/catalog/database: Permission denied
Sep …
=> systemd: allow journalctl to create /var/lib/systemd/catalog

policy/modules/services/dbus.te, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
label systemd_runtime_notify_t
Allow daemon domains to write by default
=> Separate label for /run/systemd/notify

policy/modules/apps/gpg.te
Modify the gpg module so that gpg and the gpg_agent can manage gpg_runtime_t socket files.
See the gpg file contexts definition for further reference on the gpg_runtime_t label and the need for this patch.
---
policy/modules/apps/gpg.te |    2 ++
1 file changed, 2 insertions(+)
=> Modify the gpg module so that gpg and the gpg_agent

policy/modules/admin/rpm.fc, policy/modules/admin/rpm.if, policy/modules/admin/rpm.te, policy/modules/admin/usermanage.te
* Set labels for /var/lib/dnf/.
* Allow useradd/groupadd to read/append rpm temporary files.
* Allow rpm_t to send/receive messages from systemd-logind over dbus.
* Allow rpm_t to use inherited systemd-logind file descriptors.
Fixes:
avc:  denied  { send_msg } for msgtype=method_call interface=org.freedesktop.login1.Manager member=Inhibit dest=org.freedesktop.login1 spid=565 tpid=331
scontext=root:sysadm_r:rpm_t tcontext=system_u:system_r:systemd_logind_t tclass=dbus permissive=1
avc:  denied  { send_msg } for msgtype=method_return dest=:1.11 spid=331 tpid=565 scontext=system_u:system_r:systemd_logind_t tcontext=root:sysadm_r:rpm_t tclass=dbus permissive=1
avc:  denied  { use } for  pid=565 comm="python3"
path="/run/systemd/inhibit/1.ref" dev="tmpfs" ino=703 scontext=root:sysadm_r:rpm_t …
=> rpm: fixes for dnf

policy/modules/roles/webadm.te, policy/modules/services/certmonger.te, policy/modules/system/miscfiles.fc
Secure the Private Keys corresponding to SSL Certificates used by the HTTP daemon in order to fix a serious **Information Disclosure vulnerability** caused by the erroneous labeling of TLS Private Keys and CSR.
The new file contexts are based upon the official Apache HTTP Server recommended locations (see http://www.apache.com/how-to-setup-an-ssl-certificate-on-apache), have been extended to Debian and Gentoo locations, but might need to be further customized for other possible file locations which might still be exposed to the vulnerability.
RedHat distributions are not affected by this issue, thanks to https://github.com/SELinuxProject/refpolicy/commit/cc91fed88d4cedaa4488f045a2da1132d9aeddca but apparentlly such change was not taken up by other distributions file contexts …
=> Secure the Private Keys corresponding to SSL Certificates used by the HTTP daemon

policy/modules/system/init.te
The LDAP server only needs to read generic certificate files, not manage them.
Modify the init policy to match the comment and the LDAP server actual behavior.
---
policy/modules/system/init.te |    2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
=> Restrict LDAP server init script permissions on generic certificate files

policy/modules/services/smartmon.te
Make fstools optional to avoid the following build failure raised since version 2.20231002 and https://github.com/SELinuxProject/refpolicy/commit/cb068f09d224f90a97fa63a574fb423bbe1ceeda:
```
Compiling targeted policy.33
env LD_LIBRARY_PATH="/home/thomas/autobuild/instance-2/output-1/host/lib:/home/thomas/autobuild/instance-2/output-1/host/usr/lib" /home/thomas/autobuild/instance-2/output-1/host/usr/bin/checkpolicy -c 33 -U deny -S -O -E policy.conf -o policy.33
policy/modules/services/smartmon.te:146:ERROR 'type fsadm_exec_t is not within scope' at token ';' on line 237472:
allow smartmon_update_drivedb_t fsadm_exec_t:file { { getattr open map read execute ioctl } ioctl lock execute_no_trans };
#line 146
make[1]: *** …
```
=> policy/modules/services/smartmon.te: make fstools optional

policy/modules/system/miscfiles.fc
Additional file context fix for the following issue: https://github.com/SELinuxProject/refpolicy/issues/735
This patch extends the fix for a serious Information Disclosure vulnerability caused by the erroneous labeling of TLS Private Keys and CSR.
See: https://github.com/SELinuxProject/refpolicy/pull/737/commits/5c9038ec9863463de0eb82badf8f45fb2374780b
---
policy/modules/system/miscfiles.fc |    2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
=> Additional file context fix for issue 735 (Information Disclosure vulnerability)

policy/modules/services/git.fc
Avoid relabel loops if the helper binaries are hardlinked:
$ restorecon -vRF -T0 /usr/libexec/
Relabeled /usr/libexec/git-core/git from system_u:object_r:git_exec_t to system_u:object_r:bin_t
Relabeled /usr/libexec/git-core/git-rev-parse from system_u:object_r:bin_t to system_u:object_r:git_exec_t
Relabeled /usr/libexec/git-core/git-fsmonitor--daemon from system_u:object_r:bin_t to system_u:object_r:git_exec_t
=> git: add fcontext for default binary

policy/modules/kernel/devices.te
When start up adbd by adb initscript, there's a command like: mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
will cause below deny because lack of functionfs related contexts.
avc:  denied  { mount } for  pid=346 comm="mount" name="/" dev="functionfs" ino=17700 scontext=system_u:system_r:mount_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=filesystem permissive=1
=> filesystem:Add type contexts and interface for functionfs

policy/modules/services/firewalld.te
firewalld[1084]: Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/firewall/core/io/direct.py", line 372, in write
shutil.copy2(self.filename, "%s.old" % self.filename)
File "/usr/lib64/python3.9/shutil.py", line 445, in copy2
copystat(src, dst, follow_symlinks=follow_symlinks)
File "/usr/lib64/python3.9/shutil.py", line 388, in copystat
_copyxattr(src, dst, follow_symlinks=follow)
File "/usr/lib64/python3.9/shutil.py", line 338, in _copyxattr
os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/etc/firewalld/direct.xml.old'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/firewall/server/decorators.py", line 67, in …
=> Firewalld need to relabel direct.xml.old file

policy/modules/system/userdomain.if
node=localhost type=AVC msg=audit(1703021456.203:565): avc: denied  { search } for  pid=1247 comm="(systemd)" scontext=system_u:system_r:init_t:s0 tcontext=xguest_u:xguest_r:xguest_t:s0 tclass=key permissive=1
node=localhost type=AVC msg=audit(1703021456.203:565): avc: denied  { link } for  pid=1247 comm="(systemd)" scontext=system_u:system_r:init_t:s0 tcontext=xguest_u:xguest_r:xguest_t:s0 tclass=key permissive=1
node=localhost type=AVC msg=audit(1703021456.282:694): avc: denied  { create } for  pid=1247 comm="systemd" name="systemd" scontext=system_u:system_r:init_t:s0 tcontext=xguest_u:object_r:systemd_user_runtime_t:s0 tclass=dir permissive=1
node=localhost type=AVC msg=audit(1703021456.283:696): avc: denied  { create } for  pid=1247 comm="systemd" name="fifo" …
=> xguest needs 'systemd --user'

policy/modules/system/init.if, policy/modules/system/systemd.te
Like the name suggests only grant the permission getattr in init_getattr_generic_units_files().
Adjust the only caller to use init_read_generic_units_files() instead.
Reported-by: Laurent Bigonville
=> init: only grant getattr in init_getattr_generic_units_files()

.github/workflows/tests.yml, policy/modules/apps/chromium.if, policy/modules/kernel/kernel.te, policy/modules/services/devicekit.te, policy/modules/services/postgresql.if, policy/modules/services/xserver.if, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/systemd.if, policy/modules/system/systemd.te, policy/modules/system/unconfined.if, policy/modules/system/unconfined.te
* Bump SELint to version 1.5
* userspace class declaration tweaks for SELint 1.5
SELint version 1.5 emits issues for missing or unused declarations of userspace classes:
init.te:            270: (W): No explicit declaration for userspace class system.  You should access it via interface call or use a require block. (W-001)
init.te:            312: (W): No explicit declaration for userspace class service.  You should access it via interface call or use a require block. (W-001)
init.te:           1116: (W): No explicit declaration for userspace class system.  You should access it via interface call or use a require block. (W-001)
init.te:           1124: (W): No explicit declaration for userspace class service.  You should access it via interface call or use a require block. (W-001) …
=> SELint updates

policy/modules/admin/sudo.if, policy/modules/kernel/corecommands.fc, policy/modules/kernel/devices.if, policy/modules/kernel/files.if, policy/modules/roles/sysadm.te, policy/modules/services/chronyd.if, policy/modules/services/cockpit.fc, policy/modules/services/cockpit.if, policy/modules/services/cockpit.te, policy/modules/services/ssh.if, policy/modules/system/authlogin.if, policy/modules/system/init.if, policy/modules/system/init.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te, policy/modules/system/userdomain.if
This was started from #700 and tested on RHEL9 system.
It is a bunch of commits because I wanted to be clear about some of the denials I was seeing and why those rules were added.
I of course will squash before the final merge (if desired).
Please let me know questions and changes desired.
=> Add SELinux policy for cockpit

policy/modules/system/init.if
Dec 05 22:41:49 localhost.localdomain cockpit-tls[7887]: cockpit-tls: $RUNTIME_DIRECTORY environment variable must be set to a private directory
Dec 05 22:41:49 localhost.localdomain systemd[1]: cockpit.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 22:41:49 localhost.localdomain systemd[1]: cockpit.service: Failed with result 'exit-code'.
=> Needed to allow environment variable to process started (for cockpit)

policy/modules/kernel/devices.if, policy/modules/kernel/filesystem.if, policy/modules/kernel/kernel.te, policy/modules/services/container.fc, policy/modules/services/container.if, policy/modules/services/container.te, policy/modules/services/kubernetes.if, policy/modules/services/kubernetes.te, policy/modules/system/fstools.te, policy/modules/system/lvm.if, policy/modules/system/mount.if, policy/modules/system/mount.te
Various fixes which allows rook-ceph to operate using the kubernetes policy.
=> Add support for rook-ceph in kubernetes

policy/modules/system/libraries.fc
Drop a line containing a single space from the file context file to avoid SELint stumble on it:
libraries.mod.fc:   130: (E): Bad file context format (E-002)
=> libraries: drop space in empty line

policy/modules/system/systemd.if
Caused by the latest openssh version in Debian sid:
AVC avc:  denied  { getattr } for  pid=13544 comm="sshd" path="/run/systemd/notify" dev="tmpfs" ino=286 scontext=system_u:system_r:sshd_t:s0 tcontext=system_u:object_r:systemd_runtime_notify_t:s0 tclass=sock_file permissive=0
=> systemd: allow notify client to stat socket

policy/modules/system/init.if
IgnoreSIGPIPE is a feature that requires systemd to passdown the signal mask down to the fork process. To allow this the siginh permission must be allowed for all process domains that can be forked by systemd.
=> Allow systemd to pass down sig mask

policy/modules/services/cockpit.if
node=localhost type=AVC msg=audit(1714870999.370:3558): avc:  denied  { map } for  pid=7081 comm="cockpit-bridge" path=2F6465762F23373933202864656C6574656429 dev="devtmpfs" ino=793 scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:object_r:staff_cockpit_tmpfs_t:s0 tclass=file permissive=0
=> Need map perm for cockpit 300.4

policy/modules/admin/netutils.fc, policy/modules/admin/shutdown.fc, policy/modules/services/smartmon.fc, policy/modules/system/authlogin.fc, policy/modules/system/init.fc, policy/modules/system/lvm.fc
As per https://wiki.gentoo.org/wiki/Merge-usr  new gentoo profiles use merged-usr by default.
That also means: "/sbin and /usr/sbin are both actually merged to /usr/bin"
Hence these updates on files context.
=> files context for merged-usr profile on gentoo

policy/modules/apps/pulseaudio.te, policy/modules/services/bluetooth.if, policy/modules/services/dbus.te, policy/modules/services/obex.te
Required for using acquire-notify, acquire-write options (Gatt Client) and Sending notifications (Gatt Server)
Below are the avc denials that are fixed with this patch -
1. audit: type=1400 audit(315966559.395:444): avc:  denied  { use } for  pid=710 comm="dbus-daemon" path="socket:[13196]" dev="sockfs" ino=13196
scontext=system_u:system_r:system_dbusd_t:s0-s15:c0.c1023 tcontext=system_u:system_r:bluetooth_t:s0-s15:c0.c1023 tclass=fd permissive=0
2. audit: type=1400 audit(315999854.939:523): avc:  denied  { read write } for  pid=812 comm="dbus-daemon" path="socket:[99469]" dev="sockfs" ino=99469
scontext=system_u:system_r:system_dbusd_t:s0-s15:c0.c1023 tcontext=system_u:system_r:bluetooth_t:s0-s15:c0.c1023 tclass=bluetooth_socket permissive=1
Submitted-by: Naga Bhavani Akella …
=> Adding Sepolicy rules to allow bluetoothctl and dbus-daemon to access unix stream sockets.

policy/modules/kernel/devices.if, policy/modules/services/bluetooth.te
Resolve selinux premission for HID
Below avc denials that are fixed with this patch -
avc:  denied  { read write } for  pid=656 comm="bluetoothd" name="uhid" dev="devtmpfs" ino=841 scontext=system_u:system_r:bluetooth_t:s0-s15:c0.c1023 tcontext=system_u:object_r:uhid_device_t:s0 tclass=chr_file permissive=0
Submitted-by: Amisha Jain <quic_amisjain@quicinc.com>
=> Sepolicy changes for bluez to access uhid

policy/modules/system/selinuxutil.te
Make policykit optional to avoid a potential build error.
=> selinuxutil: make policykit optional

policy/modules/apps/pulseaudio.te
pulseaudio uses bluetooth sockets for HFP-AG and
HSP-HS profile to do SLC and SCO connection with
remote.
avc:  denied  { create } for  pid=1271 comm="pulseaudio" scontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tcontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tclass=bluetooth_socket permissive=1
avc:  denied  { bind } for  pid=1271 comm="pulseaudio" scontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tcontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tclass=bluetooth_socket permissive=1
avc:  denied  { listen } for  pid=1271 comm="pulseaudio" scontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tcontext=system_u:system_r:pulseaudio_t:s0-s15:c0.c1023 tclass=bluetooth_socket permissive=1
avc:  denied  { accept } for  pid=1271 comm="pulseaudio" …
=> Adding Sepolicy rules to allow pulseaudio to access bluetooth sockets.

policy/modules/services/bluetooth.fc, policy/modules/services/bluetooth.te
Required for fixing the below avc denials -
1. audit: type=1400 audit(1651238006.276:496):
avc:  denied  { read write } for  pid=2165 comm="bluetoothd"
path="socket:[43207]" dev="sockfs" ino=43207
scontext=system_u:system_r:bluetooth_t:s0-s15:c0.c1023
tcontext=system_u:system_r:initrc_t:s0-s15:c0.c1023
tclass=unix_stream_socket permissive=1
2. audit: type=1400 audit(1651238006.276:497):
avc:  denied  { getattr } for  pid=2165 comm="bluetoothd"
path="socket:[43207]" dev="sockfs" ino=43207
scontext=system_u:system_r:bluetooth_t:s0-s15:c0.c1023
tcontext=system_u:system_r:initrc_t:s0-s15:c0.c1023
tclass=unix_stream_socket permissive=1
3. audit: type=1400 audit(1651238006.272:495):
avc:  denied  { read write } for  pid=689 comm="dbus-daemon"
path="socket:[43207]" dev="sockfs" ino=43207 …
=> Setting bluetooth helper domain for bluetoothctl

policy/modules/services/ssh.fc
OpenSSH 9.8 splits out much of the session code from the main sshd binary into a new sshd-session binary. Allow the sshd server to execute this binary by labeling it as sshd_exec_t.
=> sshd: label sshd-session as sshd_exec_t

policy/modules/system/systemd.te
Allow systemd-logind to use locallogin pidfds.
=> systemd: allow logind to use locallogin pidfds

policy/modules/system/systemd.te
Make xdg optional to avoid a potential build error.
=> systemd: make xdg optional

policy/modules/kernel/devices.te, policy/modules/kernel/filesystem.te
It is a USB Gadget config pseudo-FS, not a network nor distributed FS
=> filesystem, devices: move gadgetfs to usbfs_t

Makefile
The variable is used quoted.
Improves: https://github.com/SELinuxProject/refpolicy/commit/f9595d30ff5b6323777928591a45a4cb241dd87b
=> Makefile: drop duplicate quotes

policy/modules/system/netlabel.te
Allow interactive user terminal output for the NetLabel management tool.
---
policy/modules/system/netlabel.te |    2 ++
1 file changed, 2 insertions(+)
=> Allow interactive user terminal output for the NetLabel management tool

policy/modules/admin/fapolicyd.te, policy/modules/kernel/files.if, policy/modules/kernel/filesystem.if
When fapolicyd is configured with allow_filesystem_mark = 1 it watches filesysems and mount points 
When fapolicyd is configured with integrituy = sha256 it mmaps files to perform hash
node=localhost type=AVC msg=audit(1726153668.013:418): avc:  denied  { watch } for  pid=1561 comm="fapolicyd" path="/dev/shm" dev="tmpfs" ino=1 scontext=system_u:system_r:fapolicyd_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
node=localhost type=AVC msg=audit(1726154081.718:403): avc:  denied  { watch } for  pid=1598 comm="fapolicyd" path="/" dev="dm-1" ino=2 scontext=system_u:system_r:fapolicyd_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=1
node=localhost type=AVC msg=audit(1726154081.718:403): avc:  denied  { watch_sb } for  pid=1598 comm="fapolicyd" …
=> Additional permissions when fapolicyd.conf more strict

policy/modules/services/mysql.fc
`.mylogin.cnf` is created by `mysql_config_editor`. The file location is the current user's home directory on non-Windows systems: https://dev.mysql.com/doc/refman/9.0/en/mysql-config-editor.html.
=> Define context for `.mylogin.cnf`

policy/modules/kernel/devices.fc, policy/modules/kernel/devices.if, policy/modules/kernel/devices.te
Added label for userfaultfd, udmabuf and dma_heap based on what is in fedora-policy
=> Fix complaints in STIG about unlabeled device files

policy/modules/services/container.te
Don't need to have mta policy loaded when loading container policy.
=> Make mta optional in container policy

policy/flask/access_vectors, policy/policy_capabilities
Add the netlink_xperm policy capability and nlmsg permission definitions. The policy capability is commented-out/disabled by default. Enabling it will require the next release version of libsepol (3.8+) and the next release version of the kernel (6.13+). When the policy capability is enabled, the kernel switches from checking the current nlmsg_read/write/... permissions to always checking a single nlmsg permission with the nlmsg_type value as an extended permission.
nlmsg permission is not added to the *_netlink_socket_perms macros to avoid unwittingly allowing all netlink message types when/if this policy capability is enabled.
=> add netlink_xperm policy capability and nlmsg permission definitions

.github/workflows/build-policy.yml, .github/workflows/build-setools.yml, .github/workflows/build-userspace.yml, .github/workflows/diff-policy.yml, .github/workflows/tests.yml, .github/workflows/validate-policy.yml, INSTALL, policy/modules/kernel/kernel.te, policy/modules/roles/guest.te, policy/modules/roles/xguest.te, policy/modules/services/xserver.te, policy/modules/system/unconfined.te, policy/users, support/validate-appconfig.py
New validations:
* default_type
* failsafe_context
* default_contexts
* seuser default_contexts
Additionally add GitHub annotations to logging.
=> validate-appconfig.py: Add further validations.

policy/modules/services/cron.fc
This regexp will match lots of unintended files, for example things created by tempfile patterns (could include "cron"), and also things inside subdirectories.
It feels like a better approach would be to find actual directories used, or at the very least to limit it to files directly under /run.
It's possible just removing it is too harsh, but I feel at least it should be changed.
=> cron: Remove too greedy file context grab

support/validate-appconfig.py
=> Changes to support python 3.9 (RHEL9)

policy/modules/system/init.if, policy/modules/system/systemd.if
The notify socket is SOCK_DGRAM. See sd_notify(3) NOTES section for details.
=> systemd: Fix systemd_write_notify_socket().

policy/modules/system/init.if, policy/modules/system/init.te
Move common daemon and system process rules to `init.te` for consistent permissions.
=> init: Move common rules out of daemon/system interfaces.

policy/modules/admin/sudo.if, policy/modules/admin/sudo.te
When using the sudoers option logfile=/var/log/sudo.log it needs to create (and append) to the log file.
node=test123 type=AVC msg=audit(1731031593.322:16399): avc:  denied  { write } for  pid=5792 comm="sudo" name="/" dev="dm-5" ino=2 scontext=toor_u:staff_r:staff_sudo_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=dir permissive=1
node=test123 type=AVC msg=audit(1731031593.322:16399): avc:  denied  { add_name } for  pid=5792 comm="sudo" name="sudo.log" scontext=toor_u:staff_r:staff_sudo_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=dir permissive=1
node=test123 type=AVC msg=audit(1731031593.322:16399): avc:  denied  { create } for  pid=5792 comm="sudo" name="sudo.log" scontext=toor_u:staff_r:staff_sudo_t:s0 tcontext=toor_u:object_r:var_log_t:s0 tclass=file permissive=1 …
=> Setup sudo log file type

policy/modules/system/systemd.if, policy/modules/system/systemd.te
node=localhost type=USER_AVC msg=audit(1731946583.709:17143): pid=962 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0 msg='avc:  denied  { send_msg } for  scontext=system_u:system_r:script_t:s0 tcontext=system_u:system_r:systemd_locale_t:s0 tclass=dbus permissive=1 exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?'␝UID="dbus" AUID="unset" SAUID="dbus"
Cleanup some denials seen for systemd_locale_t
node=localhost type=AVC msg=audit(1731946409.877:15089): avc:  denied  { read } for  pid=6038 comm="systemd-localed" name="language-fallback-map" dev="dm-0" ino=287302 scontext=system_u:system_r:systemd_locale_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=1 node=localhost type=AVC msg=audit(1731946409.877:15089): avc:  denied  { …
=> Communicate with locale via dbus

policy/modules/system/miscfiles.if
Even if you create a private key for a certificate in /etc/pki/tls/certs or private key in /etc/pki/tls/private as those directories are labeled cert_t and tls_privkey_t. So you need dir search perms to be able to access your new key type.
node=localhost type=AVC msg=audit(1731898795.566:33533): avc:  denied  { search } for  pid=961 comm="monitor" name="private" dev="dm-0" ino=524539 scontext=system_u:system_r:monitor_t:s0 tcontext=system_u:object_r:tls_privkey_t:s0 tclass=dir permissive=1`
=> Need search perms on cert_t/tls_privkey_t when using private types

policy/modules/admin/usermanage.te, policy/modules/system/userdomain.if
When the copy fails it stops copying any other files.
node=asdf type=AVC msg=audit(1731544222.421:251876): avc:  denied  { create } for  pid=14952 comm="useradd" name=".mozilla" scontext=system_u:system_r:useradd_t:s0 tcontext=user_u:object_r:mozilla_home_t:s0 tclass=dir permissive=0
node=asdf type=AVC msg=audit(1731545219.731:272250): avc:  denied  { create } for  pid=19939 comm="useradd" name=".mozilla" scontext=system_u:system_r:useradd_t:s0 tcontext=user_u:object_r:mozilla_home_t:s0 tclass=dir permissive=1
node=asdf type=AVC msg=audit(1731545219.731:272251): avc:  denied  { setattr } for  pid=19939 comm="useradd" name=".mozilla" dev="dm-7" ino=1703938 scontext=system_u:system_r:useradd_t:s0 tcontext=user_u:object_r:mozilla_home_t:s0 tclass=dir permissive=1
node=asdf type=AVC …
=> mozilla adds .mozilla directory to /etc/skel which useradd tries to copy

policy/modules/system/authlogin.te, policy/modules/system/locallogin.te, policy/modules/system/lvm.if, policy/modules/system/systemd.fc, policy/modules/system/systemd.if, policy/modules/system/systemd.te
Commit messages for each commit should explain more, let me know if you have any more questions.
Thanks!
=> systemd-homed: various fixups

policy/modules/system/authlogin.te
Container UID/GID lookups for utilities such as nspawn require nss clients to be able to make nsresourced lookups.
=> authlogin: connect to nsresourced

policy/modules/admin/bootloader.te, policy/modules/system/systemd.fc, policy/modules/system/systemd.te
systemd stores some early boot log files here, such as the userspace measurement event log for TPMs. The logfiles stored here aren't sensitive enough to warrant their own type, so let's just reuse systemd_log_t.
=> systemd: various changes

policy/modules/admin/usermanage.te
Just quiet down the denial seen in enforcing.
node=asdf type=AVC msg=audit(1731544222.422:251879): avc:  denied  { search } for  pid=14952 comm="useradd" name="spool" dev="dm-8" ino=1179650 scontext=system_u:system_r:useradd_t:s0 tcontext=system_u:object_r:var_spool_t:s0 tclass=dir permissive=0
node=asdf type=AVC msg=audit(1731545219.734:272283): avc:  denied  { search } for  pid=19939 comm="useradd" name="spool" dev="dm-8" ino=1179650 scontext=system_u:system_r:useradd_t:s0 tcontext=system_u:object_r:var_spool_t:s0 tclass=dir permissive=1
node=asdf type=AVC msg=audit(1731545219.734:272283): avc:  denied  { write } for  pid=19939 comm="useradd" name="mail" dev="dm-8" ino=1179652 scontext=system_u:system_r:useradd_t:s0 tcontext=system_u:object_r:var_spool_t:s0 tclass=dir permissive=1 …
=> If mta module is not installed useradd fails to create mailbox files

policy/modules/kernel/corecommands.fc
jspawnhelper is executed when using java's ProcessBuilder.start () or Runtime.exec ().  I'm seeing a denial for 'lib_t:file execute_no_trans' because jspawnhelper was labeled lib_t.  bin_t seems to be more correct as this can be executed.
https://github.com/openjdk/jdk/blob/master/src/java.base/unix/native/jspawnhelper/jspawnhelper.c
=> label jspawnhelper bin_t

policy/modules/system/authlogin.fc
Also add the proper context for the tcb_updpwd binary.
Complements: bc88a1ca4b37df37c3654fc9e5368d7d96b11548
=> authlogin: fix regex for /etc/tcb

policy/modules/admin/cloudinit.te, policy/modules/roles/sysadm.te, policy/modules/services/openarc.fc, policy/modules/services/openarc.if, policy/modules/services/openarc.te, policy/modules/services/postfix.te
This policy file particularly targets [OpenARC](https://github.com/flowerysong/OpenARC/). The OpenARC milter is both an open source library for adding Authenticated Received Chain (ARC) support to applications, and an example filter application using the milter protocol.
The policy files are based on the `dkim policy` in this repository, with adaptions where useful.
=> This is a policy for the ARC milter

policy/modules/system/authlogin.te
auth_use_pam_systemd requires dbus  :  
> /var/lib/selinux/targeted/tmp/modules/400/authlogin/cil:133 =
> (typeattributeset cil_gen_require dbusd_system_bus_client)
See : https://bugs.gentoo.org/941785
=> fixdep dbus

policy/modules/system/userdomain.if
cap_mac_admin is required to operate some LSM modules, such as selinux, apparmor, smack, etc. It is necessary to allow the security administrator role to grant this capability.
=> userdomain: allow grant mac_admin capability to security admin

policy/modules/admin/fapolicyd.te, policy/modules/system/sysnetwork.if
/run/netns is a tmpfs mountpoint
node=localhost type=AVC msg=audit(1738868630.348:1695): avc:  denied  { watch_sb watch_with_perm } for  pid=967 comm="fapolicyd" path="/run/netns" dev="tmpfs" ino=1954
Signed-of-by: Dave Sugar <dsugar100@gmail.com>
=> Allow fapolicyd to watch /run/netns

policy/modules/system/systemd.if
Fixes:
avc:  denied  { getattr } for  pid=502 comm="systemd" path="cgroup:[4026531835]" dev="nsfs" ino=4026531835 scontext=root:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:nsfs_t tclass=file permissive=0
avc:  denied  { getattr } for  pid=502 comm="systemd" path="pid:[4026531836]" dev="nsfs" ino=4026531836
scontext=root:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:nsfs_t tclass=file permissive=0
avc:  denied  { getattr } for  pid=506 comm="30-systemd-envi" path="cgroup:[4026531835]" dev="nsfs" ino=4026531835 scontext=root:sysadm_r:sysadm_systemd_t
tcontext=system_u:object_r:nsfs_t tclass=file permissive=0
avc:  denied  { getattr } for  pid=506 comm="30-systemd-envi" path="pid:[4026531836]" dev="nsfs" ino=4026531836
scontext=root:sysadm_r:sysadm_systemd_t …
=> systemd: allow system --user to get attributes of nsfs inodes

policy/modules/services/knot.if, policy/modules/services/knot.te
allow capabilities as it's the default behavior now
allow knotc cmd in init script: knotc conf-check (by default)
See https://github.com/CZ-NIC/knot/blob/master/distro/common/knot.service
=> Add setcap to knotd / add knotc_initrc_domtrans

policy/modules/services/chronyd.te
```
avc:  denied  { dac_read_search }
comm=chronyd
capability=dac_read_search
scontext=system_u:system_r:chronyd_t:s0
tcontext=system_u:system_r:chronyd_t:s0
tclass=capability
```
--
Fedora
[chronyd_t](https://github.com/fedora-selinux/selinux-policy/blob/281599ec3a5f0cc0d423b98bb76c71c1a5d76870/policy/modules/contrib/chronyd.te#L55)
[chronyc_t](https://github.com/fedora-selinux/selinux-policy/blob/281599ec3a5f0cc0d423b98bb76c71c1a5d76870/policy/modules/contrib/chronyd.te#L257)
--
[Why all the DAC_READ_SEARCH AVC messages? (Dan Walsh)](https://danwalsh.livejournal.com/77140.html)
=> chronyd: fix dac_read_search denials

policy/modules/apps/screen.if, policy/modules/system/init.te
This policy tweak permits running a screen/tmux session via a system service/unit file.
Given the interactive nature of the process it might be worth putting behind a boolean...
=> Permit init_t (systemd) to start a detached screen/tmux session

policy/modules/system/unconfined.te
```
type=PROCTITLE proctitle=mkhomedir_helper user123 0077
type=SYSCALL syscall=socket per=PER_LINUX success=yes exit=3 a0=local a1=SOCK_STREAM a2=ip a3=0xbee9d8a8 items=0 ppid=404 pid=1386 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=ttyAMA0 ses=unset comm=mkhomedir_helpe exe=/usr/sbin/mkhomedir_helper
subj=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 key=(null)
type=SELINUX_ERR op=security_compute_sid
invalid_context=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 scontext=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 tclass=unix_stream_socket
```
--
[Similar PR](https://github.com/SELinuxProject/refpolicy/pull/171)
-- …
=> unconfined: fix oddjob security_compute_sid

policy/modules/services/firewalld.te
```
type=PATH item=3 name=(null) inode=15343 dev=fe:00 mode=file,644 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:lib_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH item=2 name=(null) inode=3055 dev=fe:00 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:lib_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 type=PATH item=1 name=(null) nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH item=0 name=(null) inode=3055 dev=fe:00 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:lib_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD cwd=/
type=SYSCALL arch=armeb syscall=openat per=PER_LINUX success=yes exit=3 …
```
=> firewalld: fix lib_t Python cache denial auditing

policy/modules/kernel/kernel.if, policy/modules/services/lldpad.te
Addresses the error:
```
i40e driver detected for ens10f1, disabling LLDP in firmware
cannot open /sys/kernel/debug/i40e/0000:0f:00.1/command to disable LLDP in firmware for ens10f1: Permission Denied
```
Initial-implementation-by: Benjamin Mare
=> lldpad: Configure FW-LLDP on i40e NICs.

policy/modules/kernel/files.fc, policy/modules/kernel/files.if, policy/modules/system/init.te
```
type=PROCTITLE proctitle=/usr/lib/systemd/systemd-logind
type=SYSCALL arch=armeb syscall=openat per=PER_LINUX success=yes exit=21 a0=AT_FDCWD a1=0xb6eb6c2c a2=O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC a3=0x0 items=0 ppid=1 pid=435 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemd-logind exe=/usr/lib/systemd/systemd-logind subj=system_u:system_r:systemd_logind_t:s0 key=(null)
type=AVC avc:  denied  { open } for  pid=435 comm=systemd-logind path=/etc/machine-id dev="tmpfs" ino=13 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:init_runtime_t:s0 tclass=file
type=AVC avc:  denied  { read } for  pid=435 comm=systemd-logind name=machine-id dev="tmpfs" ino=13 …
```
=> files, init: filetrans /run/machine-id etc_runtime_t

policy/modules/system/locallogin.te
```
type=PROCTITLE proctitle=/usr/sbin/sulogin
type=SYSCALL arch=armeb syscall=ioctl per=PER_LINUX success=yes exit=0 a0=0x3 a1=0x5457 a2=0xbec20a90 a3=0xbec20a40 items=0 ppid=277 pid=278 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=ttyS0 ses=unset comm=sulogin exe=/usr/sbin/sulogin.util-linux subj=system_u:system_r:sulogin_t:s0 key=(null)
type=AVC avc:  denied  { checkpoint_restore } for  pid=278 comm=sulogin capability=checkpoint_restore  scontext=system_u:system_r:sulogin_t:s0 tcontext=system_u:system_r:sulogin_t:s0 tclass=capability2
```
--
[Checkpoint/Restore In Userspace](https://criu.org/Main_Page)
--
Fedora:
```
$ sesearch --dontaudit --source sulogin_t --target sulogin_t --class capability2
dontaudit sulogin_t …
```
=> locallogin: dontaudit sulogin_t checkpoint_restore

policy/modules/system/authlogin.te
/etc/shadow was getting labeled shadow_history_t due to the fact that when /usr/sbin/unix_update (labeled updpwd_exec_t) creates the temporary /etc/nshadow, it was getting shadow_history_t. When /etc/nshadow was renamed to /etc/shadow, shadow_history_t was retained, causing an issue.
This change is causing updpwd_t to label /etc/nshadow as shadow_t so when moved, /etc/shadow has the correct type.
=> Fix mislabeling of /etc/shadow

policy/modules/services/oddjob.te
```
type=PROCTITLE proctitle=mkhomedir_helper user123 0077
type=EXECVE argc=3 a0=mkhomedir_helper a1=user123 a2=0077
type=SYSCALL arch=armeb syscall=execve per=PER_LINUX success=yes exit=0 a0=0x5b79d8 a1=0x5a64d0 a2=0x5b0f10 a3=0x0 items=0 ppid=429 pid=1369 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=ttyAMA0 ses=unset comm=mkhomedir_helpe exe=/usr/sbin/mkhomedir_helper subj=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 key=(null)
type=AVC avc:  denied  { use } for  pid=1369 comm=mkhomedir_helpe path=/dev/ttyAMA0 dev="devtmpfs" ino=2 scontext=unconfined_u:unconfined_r:oddjob_mkhomedir_t:s0-s0:c0.c1023 tcontext=system_u:system_r:getty_t:s0 tclass=fd
```
--
[domain_interactive_fd(getty_t)](https://github.com/SELinuxProject/refpo …
=> oddjob: allow oddjob_mkhomedir_t privfd:fd use

policy/modules/system/systemd.te
=> systemd: Add log env to systemd-machine-id-setup.

policy/modules/system/systemd.te
```
type=PROCTITLE proctitle=/usr/lib/systemd/system-generators/systemd-getty-generator /run/systemd/generator /run/systemd/generator.early /run/systemd/gene
type=SYSCALL arch=armeb syscall=openat per=PER_LINUX success=yes exit=4 a0=AT_FDCWD a1=0xbea41b28 a2=O_RDWR|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC a3=0x0 items=0 ppid=1106 pid=1109 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemd-getty-g exe=/usr/lib/systemd/system-generators/systemd-getty-generator subj=system_u:system_r:systemd_generator_t:s0 key=(null)
type=AVC avc:  denied  { open } for  pid=1109 comm=systemd-getty-g path=/dev/ttyAMA0 dev="devtmpfs" ino=2 scontext=system_u:system_r:systemd_generator_t:s0 …
```
=> systemd: allow systemd_generator_t use user ttys

policy/modules/services/ssh.te
```
type=PROCTITLE proctitle=sshd -G -f /etc/ssh/sshd_config
type=SYSCALL arch=armeb syscall=socket per=PER_LINUX success=no exit=EAFNOSUPPORT(Address family not supported by protocol) a0=inet6 a1=SOCK_DGRAM a2=ip a3=0x0 items=0 ppid=1333 pid=1334 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=sshd exe=/usr/sbin/sshd subj=system_u:system_r:sshd_t:s0 key=(null)
type=AVC avc:  denied  { module_request } for  pid=1334 comm=sshd kmod="net-pf-10" scontext=system_u:system_r:sshd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system
```
--
Issue background:
[Red Hat - AVC "module_request" seen for various services for module "net-pf-10"](https://access.redhat.com/solutions/6768131)
-- …
=> ssh: allow sshd_t kernel_t:system module_request

policy/modules/system/logging.te
auditd doesn't actually need to be able to write logs, only create, append, read, rename, and setattr them. Given that great lengths are already taken to ensure audit log confidentiality and integrity (e.g. marking as mls_systemhigh and granting cap_sys_nice to prioritise over other processes to not miss audit events), it makes sense to not grant an unnecessary permission which would allow a comprimised audit daemon to tamper with the audit logs.
=> auditd: don't grant write as implied by manage_files_pattern for logs

policy/modules/system/systemd.te, policy/modules/system/udev.te
Over time, merges and rebases can introduce duplicated lines into the policy files.  This patch removes some redundancies.
All removed lines exist verbatim elsewhere in the same file.
=> Remove redundancies

policy/modules/services/ssh.if, policy/modules/system/userdomain.if
```
session    optional     pam_keyinit.so force revoke
```
--
```
type=PROCTITLE proctitle=sshd: user123 [priv]
type=SYSCALL arch=armeb syscall=keyctl per=PER_LINUX success=no exit=ENOKEY(Required key not available) a0=0x8 a1=0xfffffffc a2=0xfffffffd a3=0x3e8 items=0 ppid=1 pid=557 auid=unset uid=user123 gid=user123 euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=sshd exe=/usr/sbin/sshd subj=system_u:system_r:sshd_t:s0 key=(null)
type=AVC avc:  denied  { search } for  pid=557 comm=sshd scontext=system_u:system_r:sshd_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0 tclass=key
```
--
Fedora:
```
$ sesearch -A --source sshd_t --target unconfined_t --class key --perm search
allow domain domain:key { link search };
```
=> ssh: allow sshd_t userdomain:key search

policy/modules/system/unconfined.if
This class inherits the file common.
Also see https://lore.kernel.org/selinux/48916a70-2a89-4d24-8e36-d15ccc112519@ieee.org/
=> unconfined: Promote anon_inode access to full access.

policy/modules/admin/portage.if, policy/modules/kernel/files.if, policy/modules/services/kanidm.fc, policy/modules/services/kanidm.if, policy/modules/services/kanidm.te, policy/modules/system/authlogin.te, policy/modules/system/init.te, policy/modules/system/selinuxutil.if, policy/modules/system/systemd.te, policy/modules/system/userdomain.if
Add an initial policy implementation for [Kanidm](https://github.com/kanidm/kanidm).
From the README:
> Kanidm is a simple and secure identity management platform, allowing other applications and  services to offload the challenge of authenticating and storing identities to Kanidm.
>
> The goal of this project is to be a complete identity provider, covering the broadest possible set of requirements and integrations. You should not need any other components (like Keycloak) when you use Kanidm - we already have everything you need!
>
> To achieve this we rely heavily on strict defaults, simple configuration, and self-healing components. This allows Kanidm to support small home labs, families, small businesses, and all the way to the largest enterprise needs.
>
> If you want to host your own …
=> Initial policy for Kanidm

policy/modules/apps/qemu.te, policy/modules/kernel/devices.if, policy/modules/kernel/files.if, policy/modules/kernel/filesystem.if, policy/modules/kernel/kernel.if, policy/modules/kernel/storage.if, policy/modules/kernel/terminal.if, policy/modules/roles/sysadm.te, policy/modules/services/container.fc, policy/modules/services/container.if, policy/modules/services/container.te, policy/modules/services/dnsmasq.te, policy/modules/services/incus.fc, policy/modules/services/incus.if, policy/modules/services/incus.te, policy/modules/services/zfs.te, policy/modules/system/iptables.if, policy/modules/system/iptables.te, policy/modules/system/systemd.if
This PR adds a new module called `incus` for the incus container and VM manager
- add incus module
- extend container module by new container_init_t type of container
- add required interfaces to other modules
=> Add new module for incus (container and VM manager)

policy/modules/kernel/files.fc, policy/modules/kernel/kernel.fc
There are many situations where having a default label for /proc is helpful in early boot, generally before /proc is mounted in cases such as plymouth. Having a /proc label also doesn't really hurt here, and makes labelling more robust before the system is fully initalised.
Another example of this being useful is for mounting namespaces, such as used by systemd for auditd:
[   19.902620] audit: type=1400 audit(1663630933.439:3): avc:  denied  { mounton } for  pid=1062 comm="(auditd)" path="/run/systemd/unit-root/proc" dev="dm-3" ino=67581 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=1
Closes: https://bugs.gentoo.org/871966
=> files: add a default file context spec for /proc

policy/modules/services/container.fc
When creating a VM, incusd needs to read an incus-agent binary on the host to integrate it into the VM image.
If the agents delivered by incus are being stored inside /usr/libexec/incus/agents/ on the host the default file context of bin_t is sufficient whereas with container_engine_exec_t another allow rule would be required to search and read dirs and files in the agents/ sub-directory.
=> incus: rm explicit fcontext for /usr/libexec/incus(/.*)?

policy/modules/admin/portage.te
As udev.eclass executes udevadm[1], let's run udevadm in the udevadm_t domain as portage_t doesn't have any access to the udev control socket (and doesn't need it aside from running udevadm). As can be seen by the following AVC, comm="udevadm" when portage attempts access on a udev_t object:
type=AVC msg=audit(1657221248.009:859): avc:  denied  { connectto } for  pid=43001 comm="udevadm" path="/run/udev/control" scontext=unconfined_u:unconfined_r:portage_t tcontext=system_u:system_r:udev_t tclass=unix_stream_socket permissive=0
[1] https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/udev.eclass#n127
Closes: https://bugs.gentoo.org/856925
=> portage: domtrans udevadm out into udevadm_t

policy/modules/admin/blueman.te, policy/modules/admin/cloudinit.te, policy/modules/apps/vmware.te, policy/modules/services/accountsd.te, policy/modules/services/cockpit.te, policy/modules/services/colord.te, policy/modules/services/devicekit.te, policy/modules/services/eg25manager.te, policy/modules/services/geoclue.te, policy/modules/services/iiosensorproxy.te, policy/modules/services/kubernetes.te, policy/modules/services/lowmemorymonitor.te, policy/modules/services/powerprofiles.te, policy/modules/services/switcheroo.te
There's a few modules where `dbus_()` interfaces are used outside of an optional which causes policy build failures on systems without it. `kubernetes` and `cloud-init` are two such modules that don't actually strictly require it.
Let's go ahead and just blanket make `dbus` optional everywhere.
=> various: make dbus optional

policy/modules/system/sysnetwork.te
Fix issues like below log where denials are generated but the syscall still succeeds.
```
Aug 22 13:05:20 azure-linux dhcpcd[1044]: DUID 00:01:00:01:30:3b:27:90:7c:1e:52:7f:40:01
Aug 22 13:05:20 azure-linux dhcpcd[1044]: eth0: IAID 52:7f:40:01
Aug 22 13:05:20 azure-linux dhcpcd[1044]: eth0: soliciting a DHCP lease
Aug 22 13:05:20 azure-linux audit[1053]: AVC avc:  denied  { sys_admin } for  pid=1053 comm="dhcpcd" capability=21  scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:system_r:dhcpc_t:s0 tclass=capability permissive=0
Aug 22 13:05:20 azure-linux audit[1053]: AVC avc:  denied  { sys_admin } for  pid=1053 comm="dhcpcd" capability=21  scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:system_r:dhcpc_t:s0 tclass=capability permissive=0
Aug 22 13:05:20 azure-linux …
```
=> sysnetwork: Silence dhcpc sys_admin denials.

policy/policy_capabilities
Add definition for the policy capability netif_wildcard, which controls the support for wildcard matching of network interface names.
Add definition for the policy capability genfs_seclabel_wildcard, which controls the support for wildcard matching of genfscon paths.
=> policy_capabilities: add netif_wildcard and genfs_seclabel_wildcard

policy/modules/kernel/filesystem.te
Add task SID labeling for `pidfs`, which is the new backing pseudo filesystem for `pidfd`s.
The existing rules will allow domains to open pidfds and use them internally, but other domains will require additional access (`fd` and `file`) when passing around the pidfd.
=> filesystem: Add labeling for pidfs.

policy/modules/system/logging.fc, policy/modules/system/logging.te
Update rules for audit 4.1.2:
Allow auditd to create /run/audit/ directory
Allow auditctl to read /var/log/audit/audit.log
Fix:
avc:  denied  { create } for  pid=497 comm="auditd" name="audit" scontext=system_u:system_r:auditd_t:s15:c0.c1023
tcontext=system_u:object_r:var_run_t:s15:c0.c1023 tclass=dir permissive=0
avc:  denied  { read } for  pid=314 comm="auditctl" name="audit.log" dev="tmpfs" ino=9 scontext=system_u:system_r:auditctl_t:s0-s15:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s15:c0.c1023 tclass=file permissive=0
avc:  denied  { open } for  pid=314 comm="auditctl" path="/var/log/audit/audit.log" dev="tmpfs" ino=9
scontext=system_u:system_r:auditctl_t:s0-s15:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s15:c0.c1023 tclass=file permissive=0
=> logging: update rules for audit

policy/modules/services/ntp.te
Using timedatectl to set system time, seeing this denial
node=localhost type=USER_AVC msg=audit(1758319110.911:214791): pid=1156 uid=81 auid+4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0 msg='avc:  denied { send_msg } for scontext=system_u:system_r:ntpd_t:s0 tcontext=system_u:system_r:policykit_t:s0 tclass=dbus permissive=1 exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=?  terminal=?'UID="dbus" AUID="unset" SAUID="dbus"
=> fix: when using timedatectl to set system time
